<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		comment
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('config.config.title'));
?>

<div id="commentConfigConfigContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'app-container-border'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="commentConfigConfigSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("commentConfigConfigForm").validate()) {
					dijitRegistry.byId("commentConfigConfigStandby").show();
					that.set("disabled", true);
					
					dojoRequestXhr("<?php echo $this->url(array(), 'comment_config_config'); ?>", {
						data: dojoDomForm.toObject("commentConfigConfigForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("commentConfigConfigStandby").hide();
						dojoTopic.publish("/app/global/notification", {
							message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->_('config.config.success'); ?>" : "<?php echo $this->translator()->_('config.config.error'); ?>",
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					});
				}
			});
			</script>
		</button>
	</div>
	<!-- Toolbar -->
	
	<!-- ConfigForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
		<div id="commentConfigConfigForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('config.config.title'); ?></span></h2>
			
			<div class="app-form-row">
				<label for="auth_required">&nbsp;</label>
				<input id="commentConfigConfigAuthRequiredCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'auth_required', checked: <?php if ($this->config('comment', 'auth_required', 'false') == 'true') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('config.config.authenticationRequired'); ?>
			</div>
			
			<div class="app-form-row">
				<label for="akismet_api_key"><?php echo $this->translator()->_('config.config.akismetApiKey'); ?>:</label>
				<textarea id="commentConfigConfigAkismetTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'akismet_api_key', style: 'height: 100px; width: 300px'"><?php if ($this->akismetApiKey) : ?><?php echo $this->akismetApiKey; ?><?php endif; ?></textarea>
			</div>
			
			<input type="hidden" name="format" value="json" />
		</div>
	</div>
	<!-- /ConfigForm -->
</div>

<div id="commentConfigConfigStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'commentConfigConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/comment/languages')->_('config.config.title'); ?>";

require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/widget/Standby"
]);
</script>
