<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-11
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('photo.edit.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/media/css/admin/default/styles.css");
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/layout/resources/ResizeHandle.css");	
});
</script>

<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false" style="height: 100%; width: 100%">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false" style="margin: -8px">
		<button id="mediaPhotoEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-save'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/photo/edit/onSave");
			});
			</script>
		</button>
		
		<button id="mediaPhotoEditCloseButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-cancel'">
			<?php echo $this->translator()->_('global._share.closeAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/photo/edit/onClose");
			});
			</script>
		</button>
		
		<div data-dojo-type="dijit/ToolbarSeparator"></div>
		
		<!-- UndoRedo -->
		<button id="mediaPhotoEditUndoButton" type="button" disabled="disabled">
			<?php echo $this->translator()->_('global._share.undoAction'); ?>
		</button>
		
		<button id="mediaPhotoEditRedoButton" type="button" disabled="disabled">
			<?php echo $this->translator()->_('global._share.redoAction'); ?>
		</button>
		<!-- /UndoRedo -->
		
		<!-- ResizeDialog -->
		<div data-dojo-type="dijit/form/DropDownButton" data-dojo-props="showLabel: false, iconClass: 'app-icon module-media-icon-resize'">
			<span><?php echo $this->translator()->_('photo.edit.resizeAction'); ?></span>
			<div id="mediaPhotoEditResizeDialog" data-dojo-type="dijit/TooltipDialog" data-dojo-props="style: 'width: 250px', class: 'app-form'">
				<div class="app-form-row">
					<label for="by" style="width: 50px"><?php echo $this->translator()->_('photo.edit.resizeBy'); ?>:</label>
					<div id="mediaPhotoEditResizePercentageButton" data-dojo-type="dijit/form/RadioButton" data-dojo-props="type: 'radio', name: 'resizeBy', value: 'percentage', checked: true">
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						require(["dojo/topic"], function(dojoTopic) {
							dojoTopic.publish("/app/media/photo/edit/onSetResizeBy", "percentage");
						});
						</script>
					</div>
					<?php echo $this->translator()->_('photo.edit.resizeByPercentage'); ?>
					
					<div id="mediaPhotoEditResizePixelsButton" data-dojo-type="dijit/form/RadioButton" data-dojo-props="type: 'radio', name: 'resizeBy', value: 'pixels'">
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						require(["dojo/topic"], function(dojoTopic) {
							dojoTopic.publish("/app/media/photo/edit/onSetResizeBy", "pixels");
						});
						</script>
					</div>
					<?php echo $this->translator()->_('photo.edit.resizeByPixels'); ?>
				</div>
			
				<div class="app-form-row">
					<label for="width" style="width: 50px"><?php echo $this->translator()->_('photo._share.width'); ?>:</label>
					<div id="mediaPhotoEditResizeWidthTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="value: 100, intermediateChanges: true, style: 'width: 50px'">
						<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
						require(["dojo/topic"], function(dojoTopic) {
							dojoTopic.publish("/app/media/photo/edit/onSetResizeWidth", value);
						});
						</script>
					</div>
				</div>
				
				<div class="app-form-row">
					<label for="width" style="width: 50px"><?php echo $this->translator()->_('photo._share.height'); ?>:</label>
					<div id="mediaPhotoEditResizeHeightTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="value: 100, intermediateChanges: true, style: 'width: 50px'">
						<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
						require(["dojo/topic"], function(dojoTopic) {
							dojoTopic.publish("/app/media/photo/edit/onSetResizeHeight", value);
						});
						</script>
					</div>
				</div>
				
				<div class="app-form-row">
					<label style="width: 50px">&nbsp;</label>
					<div id="mediaPhotoEditMaintainRatioCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="type: 'checkBox', checked: true">
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="value">
						require(["dojo/topic"], function(dojoTopic) {
							dojoTopic.publish("/app/media/photo/edit/onSetMaintainRatio", value);
						});
						</script>
					</div>
					<?php echo $this->translator()->_('photo.edit.maintainAspectRatio'); ?>
				</div>
				
				<hr class="app-separator" />
				
				<div class="app-form-row">
					<label style="width: 50px">&nbsp;</label>
					<button id="mediaPhotoEditResizeButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('photo.edit.resizeAction'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						require(["dojo/topic"], function(dojoTopic) {
							dojoTopic.publish("/app/media/photo/edit/onResize");
						});
						</script>
					</button>
					
					<button id="mediaPhotoEditResizeCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('global._share.cancelAction'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						require(["dojo/dom-style"], function(dojoDomStyle) {
							dojoDomStyle.set("mediaPhotoEditResizeDialog", "display", "none");
						});
						</script>
					</button>
				</div>
			</div>
		</div>
		<!-- /ResizeDialog -->
		
		<!-- RotateAndFlip -->
		<div data-dojo-type="dijit/form/DropDownButton" data-dojo-props="showLabel: false, iconClass: 'app-icon module-media-icon-rotate-left'">
			<span><?php echo $this->translator()->_('photo.edit.rotateAction'); ?></span>
			
			<div data-dojo-type="dijit/Menu" style="display: none">
				<div id="mediaPhotoEditRotateLeftMenu" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon module-media-icon-rotate-left'">
					<?php echo $this->translator()->_('photo.edit.rotateLeftAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					require(["dojo/topic"], function(dojoTopic) {
						dojoTopic.publish("/app/media/photo/edit/onRotate", 90);
					});
					</script>
				</div>
				
				<div id="mediaPhotoEditRotateRightMenu" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon module-media-icon-rotate-right'">
					<?php echo $this->translator()->_('photo.edit.rotateRightAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					require(["dojo/topic"], function(dojoTopic) {
						dojoTopic.publish("/app/media/photo/edit/onRotate", -90);
					});
					</script>
				</div>
				
				<div id="mediaPhotoEditFlipHorizontalMenu" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon module-media-icon-flip-horizontal'">
					<?php echo $this->translator()->_('photo.edit.flipHorizontalAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					require(["dojo/topic"], function(dojoTopic) {
						dojoTopic.publish("/app/media/photo/edit/onFlip", "horizontal");
					});
					</script>
				</div>
				
				<div id="mediaPhotoEditFlipVerticalMenu" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon module-media-icon-flip-vertical'">
					<?php echo $this->translator()->_('photo.edit.flipVerticalAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					require(["dojo/topic"], function(dojoTopic) {
						dojoTopic.publish("/app/media/photo/edit/onFlip", "vertical");
					});
					</script>
				</div>
			</div>
		</div>
		<!-- /RotateAndFlip -->
		
		<!-- Crop -->
		<button id="mediaPhotoEditCropButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', showLabel: false, iconClass: 'app-icon module-media-icon-crop'">
			<?php echo $this->translator()->_('photo.edit.cropAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/photo/edit/onCrop");
			});
			</script>
		</button>
		<!-- /Crop -->
		
		<!-- Zoom -->
		<div id="mediaPhotoEditZoomSlider" data-dojo-type="dijit/form/HorizontalSlider" data-dojo-props="value: 100, minimum: 10, maximum: 200, discreteValues: 20, intermediateChanges: true, showButtons: true, style: 'width: 200px', class: 'app-right'">
			<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/photo/edit/onZoom", value);
			});
			</script>
		</div>
		<!-- /Zoom -->
	</div>
	<!-- /Toolbar -->
	
	<!-- ImageEditor -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top'" class="app-content-pane">
			<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('photo.edit.title'); ?></span></h2>
			<div><?php echo $this->translator()->_('photo.edit.' . $this->size . 'Size'); ?></div>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
			<div id="mediaPhotoEditEditorContainer" data-app-entity-props="<?php echo $this->encoder()->encode(array(
																												'photo_id' => $this->photo->photo_id,
																												'size'	   => $this->photo->size,
																												'path'	   => $this->photo->__get('image_' . $this->size),
																												'url'	   => $this->APP_ROOT_URL . $this->photo->__get('image_' . $this->size),
																											)); ?>" class="app-container-border" style="height: 100%; margin-top: -2px; overflow: auto; position: relative">
				<img src="<?php echo $this->APP_ROOT_URL . $this->photo->__get('image_' . $this->size); ?>" />
			</div>
		</div>
	</div>
	<!-- /ImageEditor -->
</div>

<script type="text/javascript">
require({
	paths: {
		"media": "<?php echo $this->APP_STATIC_URL; ?>/modules/media"
	}	
});

require([
	"dojo/dom-attr",
	"dojo/dom-style",
	"dojo/ready",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/DropDownButton",
	"dijit/form/HorizontalSlider",
	"dijit/form/RadioButton",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Menu",
	"dijit/MenuItem",
	"dijit/Toolbar",
	"dijit/ToolbarSeparator",
	"dijit/TooltipDialog",
	"core/js/base/Encoder",
	"media/js/controllers/PhotoEditor",
	"media/js/controllers/PhotoEditorMediator"
], function(dojoDomAttr, dojoDomStyle, dojoReady, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		var data = core.js.base.Encoder.decode(dojoDomAttr.get("mediaPhotoEditEditorContainer", "data-app-entity-props"));
		
		var mediaPhotoEditor = new media.js.controllers.PhotoEditor("mediaPhotoEditEditorContainer");
		mediaPhotoEditor.setOriginalImage(data.path, data.url)
						.setEditUrl("<?php echo $this->url(array(), 'media_photo_edit'); ?>" + "?photo_id=" + data.photo_id + "&size=" + data.size);
		
		var mediaPhotoEditorMediator = new media.js.controllers.PhotoEditorMediator();
		mediaPhotoEditorMediator.setUndoButton(new dijit.form.Button({
			showLabel: false,
			disabled: false,
			iconClass: "app-icon app-icon-undo-disabled",
			onClick: function() {
				mediaPhotoEditor.undo();
			}
		}, "mediaPhotoEditUndoButton"));
		mediaPhotoEditorMediator.setRedoButton(new dijit.form.Button({
			showLabel: false,
			disabled: true,
			iconClass: "app-icon app-icon-redo-disabled",
			onClick: function() {
				mediaPhotoEditor.redo();
			}
		}, "mediaPhotoEditRedoButton"));
		
		mediaPhotoEditor.setEditorMediator(mediaPhotoEditorMediator);
		
		dojoTopic.subscribe("/app/media/photo/edit/onSave", function() {
			mediaPhotoEditor.save();
		});
		dojoTopic.subscribe("/app/media/photo/edit/onClose", function() {
			mediaPhotoEditor.clean();
		});

		// Processing handler
		dojoTopic.subscribe("/app/media/photo/edit/onRotate", function(angle) {
			mediaPhotoEditor.rotate(angle);
		});
		dojoTopic.subscribe("/app/media/photo/edit/onFlip", function(direction) {
			mediaPhotoEditor.flip(direction);
		});
		dojoTopic.subscribe("/app/media/photo/edit/onCrop", function() {
			mediaPhotoEditor.toggleCropper();
		});
		dojoTopic.subscribe("/app/media/photo/edit/onZoom", function(numOfPercents) {
			mediaPhotoEditor.zoom(numOfPercents);
		});

		// Resize handler
		dojoTopic.subscribe("/app/media/photo/edit/onSetResizeBy", function(resizeBy) {
			mediaPhotoEditor.setResizeBy(resizeBy);
		});
		dojoTopic.subscribe("/app/media/photo/edit/onSetResizeWidth", function(width) {
			mediaPhotoEditor.setResizeWidth(width);
			if (mediaPhotoEditor.isMaintainRatio()) {
				dijitRegistry.byId("mediaPhotoEditResizeHeightTextBox").set("value", "percentage" == mediaPhotoEditor.getResizeBy() ? width : mediaPhotoEditor.getResizeHeight());
			}
		});
		dojoTopic.subscribe("/app/media/photo/edit/onSetResizeHeight", function(height) {
			mediaPhotoEditor.setResizeHeight(height);
			if (mediaPhotoEditor.isMaintainRatio()) {
				dijitRegistry.byId("mediaPhotoEditResizeWidthTextBox").set("value", "percentage" == mediaPhotoEditor.getResizeBy() ? height : mediaPhotoEditor.getResizeWidth());
			}
		});
		dojoTopic.subscribe("/app/media/photo/edit/onSetMaintainRatio", function(checked) {
			mediaPhotoEditor.setMaintainRatio("on" == checked);
		});
		dojoTopic.subscribe("/app/media/photo/edit/onResize", function() {
			dojoDomStyle.set("mediaPhotoEditResizeDialog", "display", "none");
			mediaPhotoEditor.resize();
		});
	});
});
</script>
