<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('photo.replace.title'));
?>

<div id="mediaPhotoReplaceForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '<?php echo $this->url(array(), 'media_photo_replace'); ?>', method: 'POST', encType: 'multipart/form-data', class: 'app-form'">
	<!-- Uploader -->
	<div class="app-form-row">
		<label for="uploader" style="width: 100px">&nbsp;</label>
		<div id="mediaPhotoReplaceUploader" data-dojo-type="dojox/form/Uploader" data-dojo-props="name: 'file', multiple: true, type: 'file', uploadOnSelect: false, label: '<?php echo $this->translator(true)->_('global._share.browseFileAction'); ?>', style: 'width: 150px'">
			<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="fileArray">
			require(["dijit/registry"], function(dijitRegistry) {
				dijitRegistry.byId("mediaPhotoReplaceSubmitButton").set("disabled", false);
			});
			</script>
			<script type="dojo/method" data-dojo-event="onBegin" data-dojo-args="dataArray">
			this.set("disabled", true);
			</script>
			<script type="dojo/method" data-dojo-event="onComplete" data-dojo-args="dataArray">
			var that = this;
			require(["dojo/topic"], function(dojoTopic) {
				that.set("disabled", false);
				dojoTopic.publish("/app/media/photo/replace/onSuccess", dataArray);
			});
			</script>
		</div>
	</div>
	<!-- /Uploader -->
	
	<div class="dijitDialogPaneActionBar">
		<button id="mediaPhotoReplaceSubmitButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit', disabled: true">
			<?php echo $this->translator()->_('global._share.uploadAction'); ?>
		</button>
	
		<button id="mediaPhotoReplaceCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/photo/replace/onCancel");
			});
			</script>
		</button>
	</div>
	
	<input type="hidden" name="photo_id" value="<?php echo $this->photo->photo_id; ?>" />
	<input type="hidden" name="format" value="json" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dojox/form/Uploader",
	"dojox/form/uploader/plugins/Flash"
]);
</script>
