<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('photo.update.title'));
?>

<div id="mediaPhotoUpdateContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="mediaPhotoUpdateSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				var form = dijitRegistry.byId("mediaPhotoUpdateForm");
				if (form.validate()) {
					dijitRegistry.byId("mediaPhotoUpdateStandby").show();
					dojoTopic.publish("/app/global/notification", {
						message: "<?php echo $this->translator()->_('global._share.savingAction'); ?>",
						type: "message"
					});
					that.set("disabled", true);
					
					dojoRequestXhr("<?php echo $this->url(array(), 'media_photo_update'); ?>", {
						data: dojoDomForm.toObject("mediaPhotoUpdateForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("mediaPhotoUpdateStandby").hide();
						dojoTopic.publish("/app/media/photo/update/onSuccess");
					});
				}
			});
			</script>
		</button>
		
		<button id="mediaPhotoUpdateCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/photo/update/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- UpdateForm -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('photo.update.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<div id="mediaPhotoUpdateForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('photo._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('photo._share.title'); ?></label>
							<div id="mediaPhotoUpdateTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'title', value: '<?php echo addslashes($this->photo->title); ?>', width: '200px', required: true, promptMessage: '<?php echo $this->translator(true)->_('photo._share.titleRequired'); ?>'">
								<script type="dojo/on">
								new core.js.views.CharacterCounter(this);
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="description"><?php echo $this->translator()->_('photo._share.description'); ?>:</label>
							<div id="mediaPhotoUpdateDescriptionTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'description', style: 'width: 300px; height: 100px'"><?php echo $this->photo->description; ?><script type="dojo/on">new core.js.views.CharacterCounter(this);</script></div>
						</div>
						
						<div class="app-form-row">
							<label for="photographer"><?php echo $this->translator()->_('photo._share.photographer'); ?>:</label>
							<input id="mediaPhotoUpdatePhotographerTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'photographer', <?php if ($this->photo->photographer) : ?>value: '<?php echo addslashes($this->photo->photographer); ?>',<?php endif; ?> style: 'width: 200px'">
						</div>
						
						<input type="hidden" name="format" value="json" />
						<input type="hidden" name="photo_id" value="<?php echo $this->photo->photo_id; ?>" />
					</div>
					<!-- /Properties -->
					
					<!-- Tags -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('photo._share.tags'); ?>', class: 'app-content-pane'">
						<div style="padding-bottom: 8px"><?php echo $this->translator()->_('photo._share.tagsHelp'); ?></div>
						
						<?php echo $this->helperLoader('tag')->tagCollector('mediaPhotoUpdateTagsContainer', 'tags[]', $this->tags); ?>
					</div>
					<!-- /Tags -->
				</div>
			</div>
		</div>
	</div>
	<!-- /UpdateForm -->
</div>

<div id="mediaPhotoUpdateStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'mediaPhotoUpdateContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
require([
	"dojo/ready",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/widget/Standby",
	"core/js/views/CharacterCounter"	
], function(dojoReady, dijitRegistry) {
	dojoReady(function() {
		// Tag suggestions
		tag.views.helpers.TagCollector.getContent = function() {
			return dijitRegistry.byId("mediaPhotoUpdateTitleTextBox").get("value") + " " + dijitRegistry.byId("mediaPhotoUpdateDescriptionTextarea").get("value");
		};
	});
});
</script>
