<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		tag
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-08-24
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div id="tagHooksTagProviderContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, iconClass: 'app-icon hook-tag-tagprovider-icon', title: '<?php echo $this->translator(true)->_('show.tags'); ?>'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: false">
		<div data-dojo-type="dijit/Toolbar">
			<input id="tagHooksTagProviderSearchTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', placeHolder: '<?php echo $this->translator(true)->_('show.keywordHelp'); ?>', style: 'width: 150px'" />
			
			<?php if ($this->languages) : ?>
			<div id="tagHooksTagProviderLanguageDropDown" data-dojo-type="dijit/form/DropDownButton" data-dojo-props="label: '<?php echo $this->translator(true)->_('show.allLanguages'); ?>'">
				<div data-dojo-type="dijit/Menu">
					<div data-dojo-type="dijit/MenuItem" data-dojo-props="label: '<?php echo $this->translator(true)->_('show.allLanguages'); ?>'">
						<script type="dojo/on" data-dojo-event="click">
						var that = this;
						require(["dijit/registry"], function(dijitRegistry) {
							dijitRegistry.byId("tagHooksTagProviderLanguageDropDown").set("label", that.label);
							dijitRegistry.byId("tagHooksTagProviderLanguageDropDown").set("iconClass", null);
							tag.hooks.tagprovider.TagController._criteria.language = null;
						});
						</script>
					</div>
					<div data-dojo-type="dijit/MenuSeparator"></div>
					<?php foreach ($this->languages as $language => $name) : ?>
					<div data-dojo-type="dijit/MenuItem" data-dojo-props="appLanguage: '<?php echo $language; ?>', label: '<?php echo $name; ?>', iconClass: 'app-icon app-flag-<?php echo $language; ?>'">
						<script type="dojo/on" data-dojo-event="click">
						var that = this;
						require(["dijit/registry"], function(dijitRegistry) {
							dijitRegistry.byId("tagHooksTagProviderLanguageDropDown").set("label", that.label);
							dijitRegistry.byId("tagHooksTagProviderLanguageDropDown").set("iconClass", "app-icon app-flag-" + that.get("appLanguage"));
							tag.hooks.tagprovider.TagController._criteria.language = that.get("appLanguage");
						});
						</script>
					</div>
					<?php endforeach; ?>
				</div>
			</div>
			<?php endif; ?>
			
			<button id="tagHooksTagProviderSearchButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', showLabel: false, iconClass: 'app-icon app-icon-search', label: '<?php echo $this->translator(true)->_('show.searchAction'); ?>'">
				<script type="dojo/on" data-dojo-event="click">
				require(["dijit/registry"], function(dijitRegistry) {
					var keyword = dijitRegistry.byId("tagHooksTagProviderSearchTextBox").get("value");
					tag.hooks.tagprovider.TagController.searchTags({
						keyword: keyword,
						page: 1
					});
				});
				</script>
			</button>
		</div>
	</div>
	<!-- /Toolbar -->
	
	<!-- TagsPane -->
	<div id="hook-tag-tagprovider-items" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'center', loadingMessage: '<div class=app-center><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>', style: 'height: 100%; width: 100%'">
		<div class="app-center">
			<div><?php echo $this->translator()->_('show.searchHelp'); ?></div>
		</div>
	</div>
	<!-- /TagsPane -->
</div>

<?php $this->script()->captureStart(); ?>
/* tag.hooks.tagprovider */
require([
	"dojo/_base/declare",
	"dojo/_base/lang",
	"dojo/io-query",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/DropDownButton",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Menu",
	"dijit/MenuItem",
	"dijit/MenuSeparator",
	"dijit/Toolbar",
	"dojox/layout/ContentPane",
	"core/js/base/Encoder"
], function(dojoDeclare, dojoLang, dojoIoQuery, dojoTopic, dijitRegistry) {
	dojoDeclare("tag.hooks.tagprovider.TagController", null, {});
	
	tag.hooks.tagprovider.TagController._criteria = {
		keyword: null,
		language: null,
		page: 1,
		per_page: 50
	};
	
	tag.hooks.tagprovider.TagController.searchTags = function(/*Object*/ criteria) {
		// summary:
		//		Searches for banners
		dojoLang.mixin(tag.hooks.tagprovider.TagController._criteria, criteria);
		var q = core.js.base.Encoder.encode(tag.hooks.tagprovider.TagController._criteria);
	
		var params = {
			_type: "hook",
			_mod: "tag",
			_name: "tagprovider",
			_method: "search",
			q: q
		};
		dijitRegistry.byId("hook-tag-tagprovider-items")
					 .set("href", "<?php echo $this->url(array(), 'core_extension_render'); ?>" + "?" + dojoIoQuery.objectToQuery(params));
	};
	
	dojoTopic.subscribe("/app/tag/hooks/tagprovider/search/onGotoPage", function(/*Integer*/ page) {
		// summary:
		//		Paging handler
		tag.hooks.tagprovider.TagController.searchTags({
			page: page
		});
	});
});
<?php $this->script()->captureEnd(); ?>
