<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-10-02
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="app-form-row">
	<label for="shorturl_service"><?php echo $this->translator()->_('config.shortUrlService'); ?>:</label>
	<select data-dojo-type="dijit/form/Select" data-dojo-props="name: 'shorturl_service', value: '<?php echo $this->shortUrlService; ?>'">
		<option value="TinyUrlCom">tinyurl.com</option>
		<option value="IsGd">is.gd</option>
		<option value="JdemCz">jdem.cz</option>
		<option value="MetamarkNet">metamark.net</option>
	</select>
</div>

<div class="app-form-row">
	<label><?php echo $this->translator()->_('config.statusTemplate'); ?>:</label>
	<?php echo $this->translator()->_('config.statusTemplateHelp'); ?>
</div>

<div class="app-form-row">
	<label for="status_template">&nbsp;</label>
	<input data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'status_template', required: true, style: 'width: 200px', value: '<?php echo $this->statusTemplate; ?>', missingMessage: '<?php echo $this->translator(true)->_('config.statusTemplateRequired'); ?>'" />
</div>

<div class="app-form-row">
	<label for="access_token"><?php echo $this->translator()->_('config.accessToken'); ?>:</label>
	<input id="utilHooksTwitterUpdaterConfigAccessToken" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'access_token', required: true, style: 'width: 200px', value: '<?php echo $this->accessToken; ?>', missingMessage: '<?php echo $this->translator(true)->_('config.accessTokenRequired'); ?>'" />
</div>

<div class="app-form-row">
	<label for="access_token_secret"><?php echo $this->translator()->_('config.accessTokenSecret'); ?>:</label>
	<input id="utilHooksTwitterUpdaterConfigAccessTokenSecret" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'access_token_secret', required: true, style: 'width: 200px', value: '<?php echo $this->accessTokenSecret; ?>', missingMessage: '<?php echo $this->translator(true)->_('config.accessTokenSecretRequired'); ?>'" />
</div>

<div class="app-form-row">
	<label>&nbsp;</label>
	<button data-dojo-type="dijit/form/Button" data-dojo-props="name: 'authorize', type: 'button'">
		<?php echo $this->translator()->_('config.authorizeAction'); ?>
		<script type="dojo/on" data-dojo-event="click">
		window.open("<?php echo $this->url(array(), 'core_extension_render') . '?' . http_build_query(array(
			'_type'	  => 'hook',
			'_mod'	  => 'util',
			'_name'	  => 'twitterupdater',
			'_method' => 'authorize',
			'step'	  => 'auth',
		)); ?>", "", "height=400, width=400, location=no");
		</script>
	</button>
</div>

<script type="text/javascript">
require([
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Select",
	"dijit/form/ValidationTextBox"
], function(dojoTopic, dijitRegistry) {
	function utilHooksTwitterUpdaterConfigDone(data) {
		switch (data.result) {
			case "APP_RESULT_OK":
				dijitRegistry.byId("utilHooksTwitterUpdaterConfigAccessToken").set("value", data.access_token);
				dijitRegistry.byId("utilHooksTwitterUpdaterConfigAccessTokenSecret").set("value", data.access_token_secret);
				break;
			case "APP_RESULT_ERROR":
				dojoTopic.publish("/app/global/notification", {
					message : "<?php echo $this->translator()->_('authorize.error'); ?>",
					type: "error"
				});
				break;
		}
	};
});
</script>
