<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		tag
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-24
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/tag/css/admin/default/styles.css");	
});
</script>

<div id="<?php echo $this->tagContainer; ?>" style="height: 100px; width: 100%"></div>

<!-- TagSuggestions -->
<?php if ($this->config('tag', 'suggestion_enabled', 'false') == 'true') : ?>
<div style="padding: 8px 0">
	<button id="tagCollectorSuggestButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', appCanAddTag: <?php if ($this->accessor()->route('tag_tag_add')) : ?>true<?php else : ?>false<?php endif; ?>">
		<?php echo $this->translator()->_('global._share.suggestAction'); ?>
		<script type="dojo/on" data-dojo-event="click">
		var that = this;
		require([
			"dojo/_base/array",
			"dojo/dom-attr",
			"dojo/dom-class",
			"dojo/dom-construct",
			"dojo/dom-style",
			"dojo/on",
			"dojo/request/xhr",
			"dojo/topic",
			"dojo/NodeList-dom",
			"dojo/query",
			"core/js/base/Encoder"
		], function(dojoArray, dojoDomAttr, dojoDomClass, dojoDomConstruct, dojoDomStyle, dojoOn, dojoRequestXhr, dojoTopic) {
			// I have to create a function to get the content for suggestions
			var content	= tag.views.helpers.TagCollector.getContent();
			if (!content) {
				dojoTopic.publish("/app/global/notification", {
					message: "<?php echo $this->translator(true)->_('tag.suggest.contentRequired'); ?>"
				});
				return;
			}
			var canAddTag = that.get("appCanAddTag");
			dojo.query(".module-tag-collection-item", "tagPartialTagCollector").orphan();
			dojoDomStyle.set("tagPartialTagCollectorLoading", "display", "block");
	
			dojoRequestXhr("<?php echo $this->url(array(), 'tag_tag_suggest'); ?>", {
				data: {
					text: content
				},
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				dojoDomStyle.set("tagPartialTagCollectorLoading", "display", "none");
	
				dojoArray.forEach(data, function(item) {
					var div = dojoDomConstruct.create("div", {
						className: "module-tag-collection-item"
					}, "tagPartialTagCollector");
					var span = dojoDomConstruct.create("span", {
						innerHTML: item.title
					}, div);
	
					if (item.tag_id) {
						// Tag already exists in the database
						dojoDomClass.add(div, "module-tag-collection-item-existing");
						dojoDomAttr.set(div, "data-app-tag", core.js.base.Encoder.encode(item));
					}
	
					dojoOn(span, "click", function() {
						var tagItem = dojoDomAttr.get(div, "data-app-tag");
						if (tagItem) {
							tag.views.helpers.TagCollector.getCollectorView().addTag(core.js.base.Encoder.decode(tagItem));
						} else if (canAddTag) {
							// Show a dialog to add new tag
							var dialog = new dojox.widget.DialogSimple({
								loadingMessage: "<div style='text-align: center'><span class='dijitContentPaneLoading'><?php echo $this->translator()->_('global._share.loadingAction'); ?></span></div>",
								title: "<?php echo $this->translator()->_('tag.add.title'); ?>",
								style: "width: 250px",
								refreshOnShow: true
							});
							dialog.set("href", "<?php echo $this->url(array(), 'tag_tag_add'); ?>?title=" + item.title);
							dialog.show();
							var onCancelHandler = dojoTopic.subscribe("/app/tag/tag/add/onCancel", function() {
								dialog.destroyRecursive();
								onCancelHandler.remove();
							});
							var onCompleteHandler = dojoTopic.subscribe("/app/tag/tag/add/onComplete", function(result) {
								if ("APP_RESULT_OK" == result.result) {
									tagItem = {
										tag_id: result.tag_id,
										title: result.title,
										slug: result.slug
									};
									tag.views.helpers.TagCollector.getCollectorView().addTag(tagItem);
									dojoDomClass.add(div, "module-tag-collection-item-existing");
									dojoDomAttr.set(div, "data-app-tag", core.js.base.Encoder.encode(tagItem));
								}
								dialog.destroyRecursive();
								onCompleteHandler.remove();
							});
						}
					});
				});
			});
		});
		</script>
	</button>
</div>

<div class="module-tag-collection-items" style="height: 100px; width: 100%; position: relative" id="tagPartialTagCollector">
	<div class="app-center" id="tagPartialTagCollectorLoading" style="display: none">
		<div>
			<span class="dijitContentPaneLoading"><?php echo $this->translator()->_('global._share.loadingAction'); ?></span>
		</div>
	</div>
</div>
<?php endif; ?>
<!-- /TagSuggestions -->

<script type="text/javascript">
require({
	paths: {
		"tag": "<?php echo $this->APP_STATIC_URL; ?>/modules/tag"
	}	
});

require([
	"dojo/_base/declare",
	"dojo/ready",
	"dojo/parser",
	"dijit/form/Button",
	"dojox/widget/DialogSimple",
	"core/js/base/Encoder",
	"tag/js/views/TagCollectionView"	
], function(dojoDeclare, dojoReady) {
	dojoDeclare("tag.views.helpers.TagCollector", null, {});

	tag.views.helpers.TagCollector._tagCollectionView = new tag.js.views.TagCollectionView("<?php echo $this->tagContainer; ?>", "<?php echo $this->tagInputName; ?>");
	
	// Get the instance of tag collection view
	tag.views.helpers.TagCollector.getCollectorView = function() {
		return tag.views.helpers.TagCollector._tagCollectionView;
	};

	dojoReady(function() {
		<?php foreach ($this->tags as $tag) : ?>
		tag.views.helpers.TagCollector.getCollectorView().addTag(core.js.base.Encoder.decode("<?php echo $this->encoder()->encode($tag); ?>"));
		<?php endforeach; ?>
	});
});
</script>
