<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-05
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('attachment.add.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/password-meter.css");	
});
</script>

<div id="fileAttachmentAddForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', encType: 'multipart/form-data', class: 'app-form'">
	<div id="fileAttachmentAddContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
			<button id="fileAttachmentAddSubmitButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit', disabled: true, iconClass: 'app-icon app-icon-save'">
				<?php echo $this->translator()->_('global._share.saveAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				var that = this;
				require([
					"dojo/dom-form",
					"dojo/request/xhr",
					"dojo/topic",
					"dijit/registry"
				], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
					var form		   = dijitRegistry.byId("fileAttachmentAddForm");
					var params		   = dojoDomForm.toObject("fileAttachmentAddForm");
					params.description = tinyMCE.getInstanceById("fileAttachmentAddDescriptionTextarea").getContent();
					
					if (!params.attachment) {
						dojoTopic.publish("/app/global/notification", {
							message: "<?php echo $this->translator()->_('attachment._share.fileRequired'); ?>",
							type: "error"
						});
						return;
					}

					if (form.validate()) {
						// Disable button
						that.set("disabled", true);
						dojoTopic.publish("/app/file/attachment/add/onStart");
						dojoRequestXhr("<?php echo $this->url(array(), 'file_attachment_add'); ?>", {
							data: params,
							handleAs: "json",
							method: "POST"
						}).then(function(data) {
							form.reset();
							that.set("disabled", false);
							dojoTopic.publish("/app/file/attachment/add/onComplete", data);
						});
					}
				});
				</script>
			</button>
			
			<button id="fileAttachmentAddCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-cancel'">
				<?php echo $this->translator()->_('global._share.cancelAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				require(["dojo/topic"], function(dojoTopic) {
					dojoTopic.publish("/app/file/attachment/add/onCancel");
				});
				</script>
			</button>
		</div>
		<!-- /Toolbar -->
		
		<!-- AddAttachmentForm -->
		<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, region: 'center'">
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
				<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('attachment.add.title'); ?></span></h2>
			</div>
		
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('attachment._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="language"><?php echo $this->translator()->_('attachment._share.language'); ?>:</label>
							<select id="fileAttachmentAddLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language'">
								<?php foreach ($this->languages as $language => $name) : ?>
								<option value="<?php echo $language; ?>"<?php if ($language == $this->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('attachment._share.title'); ?>:</label>
							<div id="fileAttachmentAddTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'title', value: '<?php if ($this->source) : ?><?php echo addslashes($this->source->title); ?><?php endif; ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('attachment._share.titleRequired'); ?>'">
								<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
								require([
									"dojo/request/xhr",
									"dijit/registry"
								], function(dojoRequestXhr, dijitRegistry) {
									dojoRequestXhr("<?php echo $this->url(array(), 'core_helper_slug'); ?>", {
										data: {
											locale: dijitRegistry.byId("fileAttachmentAddLanguageSelect").get("value"),
											input: value
										},
										handleAs: "json",
										method: "POST"
									}).then(function(data) {
										dijitRegistry.byId("fileAttachmentAddSlugTextBox").set("value", data.output);
									});
								});
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="slug"><?php echo $this->translator()->_('attachment._share.slug'); ?>:</label>
							<input id="fileAttachmentAddSlugTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('attachment._share.slugRequired'); ?>'" />
						</div>
						
						<div class="app-form-row">
							<label for="description"><?php echo $this->translator()->_('attachment._share.description'); ?>:</label>
							<textarea id="fileAttachmentAddDescriptionTextarea" name="description" style="height: 150px; width: 300px"><?php if ($this->source && $this->source->description) : ?><?php echo $this->escape($this->source->description); ?><?php endif; ?></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="auth_required">&nbsp;</label>
							<input id="fileAttachmentAddAuthRequiredCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'auth_required', checked: <?php if ($this->source && $this->source->auth_required == 1) : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('attachment._share.authRequiredHelp'); ?>
						</div>
						
						<div class="app-form-row">
							<label>&nbsp;</label>
							<div id="fileAttachmentAddPassRequiredCheckBox" data-dojo-type="dijit/form/CheckBox">
								<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
								require([
									"dojo/dom-style",
									"dijit/registry"
								], function(dojoDomStyle, dijitRegistry) {
									dojoDomStyle.set("fileAttachmentAddPasswordContainer", "display", value ? "block": "none");
									dijitRegistry.byId("fileAttachmentAddPasswordTextBox").set("disabled", value ? false : true);
								});
								</script>
							</div>
							<?php echo $this->translator()->_('attachment._share.passwordRequiredHelp'); ?>
						</div>
						
						<div id="fileAttachmentAddPasswordContainer" class="app-form-row" style="display: none">
							<label for="password"><?php echo $this->translator()->_('attachment._share.password'); ?>:</label>
							<div id="fileAttachmentAddPasswordTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'password', disabled: true, type: 'password', style: 'width: 200px', class: 'app-left'">
								<script type="dojo/on">
								this._passwordStrengthMeter = new core.js.views.PasswordStrengthMeter("fileAttachmentAddPasswordStrengthMeter");
								</script>
								<script type="dojo/on" data-dojo-event="keyup">
								this._passwordStrengthMeter.checkPassword(this.get("value"));
								</script>
							</div>
							
							<!-- PasswordStrengthMeter -->
							<div class="app-left" id="fileAttachmentAddPasswordStrengthMeter"></div>
							<!-- /PasswordStrengthMeter -->
							
							<div class="app-clear"></div>
						</div>
						
						<div class="app-form-row">
							<label for="uploadedfile">&nbsp;</label>
							<div id="fileAttachmentAddUploaderContainer"></div>
						</div>
						
						<div class="app-form-row">
							<label for="attachment">&nbsp;</label>
							<div id="fileAttachmentAddFileInfo"></div>
							<input type="hidden" name="attachment" value="" id="fileAttachmentAddUploadedFile" />
						</div>
						
						<input type="hidden" name="format" value="json" />
					</div>
					<!-- /Properties -->
					
					<!-- Localization -->
					<div id="fileAttachmentAddLocalizedContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('attachment._share.localization'); ?>', class: 'app-container-border', style: 'margin-top: 8px'">
						<?php if ($this->source) : ?>
						<div class="fileAttachmentAddLocalizedItem" style="padding: 2px 8px">
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($this->source->title); ?>', style: 'width: 300px', readOnly: true" />
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($this->source->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
							<input type="hidden" name="translations" value='<?php echo $this->source->translations; ?>' />
							
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
								<script type="dojo/on" data-dojo-event="click">
								var that = this;
								require([
									"dojo/dom-construct",
									"dojo/dom-style",
									"dojo/NodeList-traverse",
									"dojo/query"
								], function(dojoDomConstruct, dojoDomStyle) {
									dojoDomConstruct.destroy(dojo.query(that.domNode).closest(".fileAttachmentAddLocalizedItem")[0]);
									if (dojo.query(".fileAttachmentAddLocalizedItem", "fileAttachmentAddLocalizedContainer").length == 0) {
										// Show the guide
										dojoDomStyle.set("fileAttachmentAddLocalizedHelp", "display", "block");
									}
								});
								</script>
							</button>
						</div>
						<?php endif; ?>
						
						<div id="fileAttachmentAddLocalizedHelp" class="app-center" style="display: <?php if ($this->source) : ?>none<?php else : ?>block<?php endif; ?>">
							<div><?php echo $this->translator()->_('attachment._share.localizationHelp'); ?></div>
						</div>
					</div>
					<!-- /Localization -->
				</div>
			</div>
		</div>
		<!-- /AddAttachmentForm -->
	</div>
</div>

<script type="text/javascript">
require({
	paths: {
		"file": "<?php echo $this->APP_STATIC_URL; ?>/modules/file"
	}
});

require([
	"dojo/_base/array",
	"dojo/dom",
	"dojo/dom-attr",
	"dojo/dom-construct",
	"dojo/dom-style",
	"dojo/json",
	"dojo/on",
	"dojo/ready",
	"dojo/sniff",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dojo/query",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojox/grid/enhanced/plugins/GridSource",
	"file/js/views/FileFormatter",
	"core/js/base/Encoder",
	"core/js/base/Uploader",
	"core/js/views/PasswordStrengthMeter"
], function(dojoArray, dojoDom, dojoDomAttr, dojoDomConstruct, dojoDomStyle, dojoJson, dojoOn, dojoReady, dojoSniff, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		setTimeout(function() {
			tinyMCE.init({
				theme: "advanced",
				plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
				theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo",
				theme_advanced_buttons3: "link,unlink,anchor,image,media,cleanup,code,|,preview,|,forecolor,backcolor",
				theme_advanced_buttons4: "tablecontrols,ltr,rtl", //",tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
				theme_advanced_toolbar_location: "top",
				theme_advanced_toolbar_align: "left",
				theme_advanced_resizing: true,
				mode: "exact",
				elements: "fileAttachmentAddDescriptionTextarea",
				width: "300px",
				height: "350px",
				relative_urls: false,
				remove_script_host: false,
				setup: function(ed) {
					ed.onChange.add(function(ed, l) {
						dojo.query("#" + ed.id)[0].innerHTML = l.content;
					});
				}
			});
		}, 200);
		
		// Create the uploader
		var uploader = new core.js.base.Uploader({
			id: "fileAttachmentAddUploader",
			name: "uploadedfile",
			flashFieldName: "uploadedfile",
			deferredUploading: true,
			multiple: false,
			type: "file",
			uploadOnSelect: true,
			serverTimeout: 10000,
			label: "<?php echo $this->translator(true)->_('global._share.browseFilesAction'); ?>",
			url: dojoSniff("ie")
				 ? "<?php echo $this->url(array('format' => 'json', 'act' => 'upload', 'uploader' => 'flash'), 'file_attachment_add_upload'); ?>?PHPSESSID=<?php echo Zend_Session::getId(); ?>"
				 : "<?php echo $this->url(array('format' => 'json', 'act' => 'upload', 'uploader' => 'html5'), 'file_attachment_add_upload'); ?>?PHPSESSID=<?php echo Zend_Session::getId(); ?>",
			// Custom properties and override methods
			appUploadType: dojoSniff("ie") ? "flash" : "html5",
			onChange: function(fileArray) {
				dijitRegistry.byId("fileAttachmentAddSubmitButton").set("disabled", false);
			},
			onBegin: function(dataArray) {
				if ("html5" == this.get("appUploadType")) {
					this.set("disabled", true);
				}
			},
			onFileComplete: function(dataArray) {
				if ("flash" == this.get("appUploadType")) {
					dataArray = dataArray.additionalParams.appUploadedFiles;
					dataArray = core.js.base.Encoder.decode(dataArray);
					this.showUploadedAttachment(dataArray);
				}
			},
			onComplete: function(dataArray) {
				if ("html5" == this.get("appUploadType")) {
					this.set("disabled", false);
					this.showUploadedAttachment(dataArray);
				}
			},
			showUploadedAttachment: function(dataArray) {
				dojoDomAttr.set("fileAttachmentAddUploadedFile", "value", dojoJson.stringify(dataArray));
				dojoDom.byId("fileAttachmentAddFileInfo").innerHTML = "<b>" + dataArray.name + "</b> (." + dataArray.extension + ", " + file.js.views.FileFormatter.formatSize(dataArray.size, "0") + ")";
			}
		});
		dojoDom.byId("fileAttachmentAddUploaderContainer").appendChild(uploader.domNode);
		uploader.startup();
		
		// Allow to drag an attachment from the grid and drop on the localized container
		var target = new dojox.grid.enhanced.plugins.GridSource("fileAttachmentAddLocalizedContainer", {
			isSource: false,
			insertNodesForGrid: false
		});
		dojoOn(target, "dropgridrows", function(grid, rowIndexes) {
			var sourceItems = [];
			dojoArray.forEach(rowIndexes, function(rowIndex, index) {
				var item = grid.getItem(rowIndex);
				if (item) {
					sourceItems.push(item);
				}
			});

			if (sourceItems.length > 0) {
				// Hide the guide
				dojoDomStyle.set("fileAttachmentAddLocalizedHelp", "display", "none");
			}

			dojoArray.forEach(sourceItems, function(item) {
				var div = dojoDomConstruct.create("div", {
					className: "fileAttachmentAddLocalizedItem",
					style: "padding: 2px 8px"
				}, "fileAttachmentAddLocalizedContainer");

				new dijit.form.TextBox({
					value: item.title[0],
					style: "width: 300px",
					readOnly: true
				}).placeAt(div);
				
				new dijit.form.TextBox({
					value: item.language[0],
					style: "margin: 0 8px; width: 100px",
					readOnly: true
				}).placeAt(div);

				dojoDomConstruct.create("input", {
					name: "translations",
					type: "hidden",
					value: item.translations[0]
				}, div);

				new dijit.form.Button({
					label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
					onClick: function() {
						dojoDomConstruct.destroy(div);
						if (dojo.query(".fileAttachmentAddLocalizedItem", "fileAttachmentAddLocalizedContainer").length == 0) {
							// Show the guide
							dojoDomStyle.set("fileAttachmentAddLocalizedHelp", "display", "block");
						}
					}
				}).placeAt(div);
			});
		});
	});
});
</script>
