<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		comment
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-03
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('comment.list.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/comment/css/admin/default/styles.css");	
});
</script>

<div id="commentCommentListContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<!-- LeftPane -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'leading', gutters: false, minSize: 150, splitter: true, style: 'height: 100%; padding: 0; width: 15%'">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div class="app-container-bar" style="border-left: none; border-right: none; border-top: none">
				<?php echo $this->translator()->_('comment.list.status'); ?>
			</div>
		</div>
			
		<!-- Status -->
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'">
			<ul id="commentCommentListStatusContainer" class="module-comment-statuses">
				<li<?php if (!$this->criteria['status']) : ?> class="module-comment-status-active"<?php endif; ?>>
					<a data-app-status="" class="module-comment-status-label" href="javascript: void(0);"><?php echo $this->translator()->_('comment.list.viewAll'); ?></a>
					<span class="app-counter"><?php echo $this->commentCounter(array('status' => null)); ?></span>
				</li>
				<li class="module-comment-status-active<?php if ($this->criteria['status'] == Comment_Models_Comment::STATUS_ACTIVATED) : ?> module-comment-status-active<?php endif; ?>">
					<a data-app-status="<?php echo Comment_Models_Comment::STATUS_ACTIVATED; ?>" class="module-comment-status-label" href="javascript: void(0);"><?php echo $this->translator()->_('comment.list.statusActivated'); ?></a>
					<span class="app-counter"><?php echo $this->commentCounter(array('status' => Comment_Models_Comment::STATUS_ACTIVATED)); ?></span>
				</li>
				<li class="module-comment-status-unactive<?php if ($this->criteria['status'] == Comment_Models_Comment::STATUS_NOT_ACTIVATED) : ?> module-comment-status-active<?php endif; ?>">
					<a data-app-status="<?php echo Comment_Models_Comment::STATUS_NOT_ACTIVATED; ?>" class="module-comment-status-label" href="javascript: void(0);"><?php echo $this->translator()->_('comment.list.statusNotActivated'); ?></a>
					<span class="app-counter"><?php echo $this->commentCounter(array('status' => Comment_Models_Comment::STATUS_NOT_ACTIVATED)); ?></span>
				</li>
				<li class="module-comment-status-spam<?php if ($this->criteria['status'] == Comment_Models_Comment::STATUS_SPAM) : ?> module-comment-status-active<?php endif; ?>">
					<a data-app-status="<?php echo Comment_Models_Comment::STATUS_SPAM; ?>" class="module-comment-status-label" href="javascript: void(0);"><?php echo $this->translator()->_('comment.list.statusSpam'); ?></a>
					<span class="app-counter"><?php echo $this->commentCounter(array('status' => Comment_Models_Comment::STATUS_SPAM)); ?></span>
				</li>
			</ul>
		</div>
		<!-- /Status -->
	</div>
	<!-- /LeftPane -->

	<!-- CenterPane -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'app-container-border'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="commentCommentListToolbar" style="height: 27px"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Comments -->
		<div id="commentCommentListGridContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'">
		</div>
		<!-- /Comments -->
		
		<!-- Paginator -->
		<div id="commentCommentListPaginator" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'height: 27px; padding: -8px'">
		</div>
		<!-- /Paginator -->
	</div>
	<!-- /CenterPane -->
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/comment/languages')->_('comment.list.title'); ?>";

require({
	paths: {
		"comment": "<?php echo $this->APP_STATIC_URL; ?>/modules/comment"
	}
});

require([
	"dojo/ready",
	"dojo/parser",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dojox/layout/ContentPane",
	"core/js/base/Config",
	"core/js/base/controllers/ActionProvider",
	"comment/js/controllers/CommentController",
	"comment/js/views/CommentGrid",
	"comment/js/views/CommentStatusListView",
	"comment/js/views/CommentToolbar"
], function(dojoReady, dojoParser) {
	dojoReady(function() {
		// Provide the actions
		<?php foreach (array(
						'comment_comment_activate', 'comment_comment_delete', 'comment_comment_edit', 'comment_comment_list', 'comment_comment_reply',
						'comment_comment_spam', 'comment_comment_view',
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
		});	
		<?php endforeach; ?>

		// Localization
		core.js.base.Config.set("core", "localization_languages", <?php echo $this->config("core", "localization_languages", '{"en_US":"English"}'); ?>);

		var commentController = new comment.js.controllers.CommentController("commentCommentListContainer");
		commentController.setCommentToolbar(new comment.js.views.CommentToolbar("commentCommentListToolbar"))
						 .setCommentGrid(new comment.js.views.CommentGrid("commentCommentListGridContainer"))
						 .setCommentPaginator("commentCommentListPaginator")
						 .setStatusListView(new comment.js.views.CommentStatusListView("commentCommentListStatusContainer"))
						 .initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>)
						 .searchComments();
	});	
});
</script>
