<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		category
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('category.edit.title'));
?>

<div id="categoryCategoryEditContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="categoryCategoryEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', disabled: <?php if ($this->category) : ?>false<?php else : ?>true<?php endif; ?>">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("categoryCategoryEditForm").validate()) {
					dojoTopic.publish("/app/category/category/edit/onStart");
					dojoRequestXhr("<?php echo $this->url(array(), 'category_category_edit'); ?>", {
						data: dojoDomForm.toObject("categoryCategoryEditForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						dojoTopic.publish("/app/category/category/edit/onComplete", data);
					});
				}
			});
			</script>
		</button>
		
		<button id="categoryCategoryEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/category/category/edit/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- Toolbar -->	

	<!-- EditCategoryForm -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, region: 'center'">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('category.edit.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', design: 'sidebar', gutters: false, class: 'app-content-pane'">
			<?php if (!$this->category) : ?>
				<?php echo $this->translator()->_('category.edit.notFound'); ?>
			<?php else : ?>
			
			<div id="categoryCategoryEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('category._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="language"><?php echo $this->translator()->_('category._share.language'); ?>:</label>
							<select id="categoryCategoryEditLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language'">
								<?php foreach ($this->languages as $language => $name) : ?>
								<option value="<?php echo $language; ?>"<?php if ($language == $this->category->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
					
						<div class="app-form-row">
							<label for="name"><?php echo $this->translator()->_('category._share.name'); ?>:</label>
							<div id="categoryCategoryEditNameTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'name', value: '<?php echo addslashes($this->category->name); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('category._share.nameRequired'); ?>'">
								<script type="dojo/on">
								new core.js.views.CharacterCounter(this);
								</script>
								<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
								require([
									"dojo/request/xhr",
									"dijit/registry"
								], function(dojoRequestXhr, dijitRegistry) {
									dojoRequestXhr("<?php echo $this->url(array(), 'core_helper_slug'); ?>", {
										data: {
											input: value
										},
										handleAs: "json",
										method: "POST"
									}).then(function(data) {
										dijitRegistry.byId("categoryCategoryEditSlugTextBox").set("value", data.output);
									});
								});
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="slug"><?php echo $this->translator()->_('category._share.slug'); ?>:</label>
							<input id="categoryCategoryEditSlugTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', value: '<?php if ($this->category->slug) : ?><?php echo addslashes($this->category->slug); ?><?php endif; ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('category._share.slugRequired'); ?>'" />
						</div>
						
						<div class="app-form-row">
							<label for="parent_id"><?php echo $this->translator()->_('category._share.parent'); ?>:</label>
							<?php
							echo $this->categorySelect($this->category->module, $this->category->language, array(
															'name'	   => 'parent_id',
															'selected' => $this->category->parent_id,
														));
							?>
						</div>
						
						<div class="app-form-row">
							<label for="image"><?php echo $this->translator()->_('category._share.image'); ?>:</label>
							<input id="categoryCategoryEditImageTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'image', <?php if ($this->category->image) : ?>value: '<?php echo addslashes($this->category->image); ?>',<?php endif; ?> style: 'width: 300px'" />
						</div>
						
						<div class="app-form-row">
							<label for="meta_keyword"><?php echo $this->translator()->_('category._share.metaKeywordTag'); ?>:</label>
							<textarea id="categoryCategoryEditMetaKeywordTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'meta_keyword', style: 'height: 100px; width: 300px'"><?php echo $this->category->meta_keyword; ?></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="meta_description"><?php echo $this->translator()->_('category._share.metaDescriptionTag'); ?>:</label>
							<div id="categoryCategoryEditMetaDescTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'meta_description', style: 'height: 100px; width: 300px'"><?php echo $this->category->meta_description; ?><script type="dojo/on">new core.js.views.CharacterCounter(this);</script></div>
						</div>
						
						<input type="hidden" name="category_id" value="<?php echo $this->category->category_id; ?>" />
						<input type="hidden" name="format" value="json" />
					</div>
					<!-- /Properties -->
					
					<!-- Localization -->
					<div id="categoryCategoryEditLocalizedContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('category._share.localization'); ?>', class: 'app-container-border', style: 'margin-top: 8px'">
						<?php if ($this->translations) : ?>
						<?php foreach ($this->translations as $tranlation) : ?>
						<div class="categoryCategoryEditLocalizedItem" style="padding: 2px 8px" data-app-translations='<?php echo $tranlation->translations; ?>'>
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->name); ?>', style: 'width: 200px', readOnly: true" />
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
							<input type="hidden" name="translations" value='<?php echo $tranlation->translations; ?>' />
							
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
								<script type="dojo/on" data-dojo-event="click">
								var that = this;
								require([
									"dojo/dom-attr",
									"dojo/dom-style",
									"dojo/NodeList-dom",
									"dojo/NodeList-traverse",
									"dojo/query"
								], function(dojoDomAttr, dojoDomStyle) {
									var localizedItem = dojo.query(that.domNode).closest(".categoryCategoryEditLocalizedItem")[0];
									var translations  = dojoDomAttr.get(localizedItem, "data-app-translations");
									dojo.query(".categoryCategoryEditLocalizedItem[data-app-translations='" + translations + "']", "categoryCategoryEditLocalizedContainer").orphan();
									if (dojo.query(".categoryCategoryEditLocalizedItem", "categoryCategoryEditLocalizedContainer").length == 0) {
										// Show the guide
										dojoDomStyle.set("categoryCategoryEditLocalizedHelp", "display", "block");
									}
								});
								</script>
							</button>
						</div>
						<?php endforeach; ?>
						<?php endif; ?>
						
						<div id="categoryCategoryEditLocalizedHelp" class="app-center" style="display: <?php if ($this->translations && count($this->translations) > 0) : ?>none<?php else : ?>block<?php endif; ?>">
							<div><?php echo $this->translator()->_('category._share.localizationHelp'); ?></div>
						</div>
					</div>
					<!-- /Localization -->
				</div>
			</div>
			
			<?php endif; ?>
			</div>
	</div>
	<!-- /EditCategoryForm -->
</div>

<script type="text/javascript">
require([
	"dojo/dom-attr",
	"dojo/dom-construct",
	"dojo/dom-style",
	"dojo/ready",
	"dijit/registry",
	"dojo/parser",
	"dojo/dnd/Target",
	"dojo/NodeList-dom",
	"dojo/NodeList-traverse",
	"dojo/query",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"core/js/views/CharacterCounter"
], function(dojoDomAttr, dojoDomConstruct, dojoDomStyle, dojoReady, dijitRegistry) {
	dojoReady(function() {
		// Allow to drag tree node and drop on the localized container
		new dojo.dnd.Target("categoryCategoryEditLocalizedContainer", {
			accept: ["treeNode"],
			onDropExternal: function(source, nodes, copy) {
				var treeNode = dijitRegistry.byNode(nodes[0]);
				if (treeNode) {
					var item = treeNode.item;
					if (item.root) {
						return;
					}

					// Hide the guide
					dojoDomStyle.set("categoryCategoryEditLocalizedHelp", "display", "none");

					var div = dojoDomConstruct.create("div", {
						className: "categoryCategoryEditLocalizedItem",
						style: "padding: 2px 8px",
						"data-app-translations": item.translations[0]
					}, "categoryCategoryEditLocalizedContainer");
					new dijit.form.TextBox({
						value: item.name[0],
						style: "width: 200px",
						readOnly: true
					}).placeAt(div);
					
					new dijit.form.TextBox({
						value: item.language[0],
						style: "margin: 0 8px; width: 100px",
						readOnly: true
					}).placeAt(div);

					dojoDomConstruct.create("input", {
						name: "translations",
						type: "hidden",
						value: item.translations[0]
					}, div);

					new dijit.form.Button({
						label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
						onClick: function() {
							var localizedItem = dojo.query(this.domNode).closest(".categoryCategoryEditLocalizedItem")[0];
							var translations  = dojoDomAttr.get(localizedItem, "data-app-translations");
							dojo.query(".categoryCategoryEditLocalizedItem[data-app-translations='" + translations + "']", "categoryCategoryEditLocalizedContainer").orphan();
							if (dojo.query(".categoryCategoryEditLocalizedItem", "categoryCategoryEditLocalizedContainer").length == 0) {
								// Show the guide
								dojoDomStyle.set("categoryCategoryEditLocalizedHelp", "display", "block");
							}
						}
					}).placeAt(div);
				}
			}
		});
	});
});
</script>
