<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	tasks
 * @since		1.0
 * @version		2012-10-01
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div style="padding-bottom: 8px"><?php echo $this->translator()->_('config.addFeedHelp'); ?></div>

<div style="padding-bottom: 16px">
	<input id="contentTasksFeedimporterUrl" data-dojo-type="dijit/form/TextBox" data-dojo-props="style: 'width: 200px', placeHolder: '<?php echo $this->translator(true)->_('config.url'); ?>'" />
	<select id="contentTasksFeedimporterLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="style: 'width: 150px', value: '<?php echo $this->language; ?>'">
		<option value="" disabled="disabled"><?php echo $this->translator()->_('config.selectLanguage'); ?></option>
		<?php foreach ($this->languages as $locale => $language) : ?>
		<option value="<?php echo $locale; ?>"><?php echo $language; ?></option>
		<?php endforeach; ?>
		
		<script type="dojo/on" data-dojo-event="change" data-dojo-args="language">
		require([
			"dojo/_base/array",
			"dojo/json",
			"dojo/request/xhr",
			"dijit/registry"
		], function(dojoArray, dojoJson, dojoRequestXhr, dijitRegistry) {
			dijitRegistry.byId("contentTasksFeedimporterStandby").show();
			dojoRequestXhr("<?php echo $this->url(array(), 'core_extension_render'); ?>", {
				data: {
					_type: "task",
					_mod: "content",
					_name: "feedimporter",
					_method: "category",
					language: language
				},
				method: "POST"
			}).then(function(data) {
				dijitRegistry.byId("contentTasksFeedimporterStandby").hide();
				data = dojoJson.parse(data);

				// Update the options of category select box
				var categorySelect = dijitRegistry.byId("contentTasksFeedimporterCategorySelect");
				
				var options = categorySelect.getOptions();
				dojoArray.forEach(options, function(option, index) {
					if (option.value != "") {
						categorySelect.removeOption(option);
					}
				});

				dojoArray.forEach(data, function(item) {
					var label = [], depth = parseInt(item.depth);
					while (label.length < depth) {
						label.push("---");
					}
					categorySelect.addOption({
						label: label.join("") + item.name,
						value: item.category_id + ""
					});
				});
			});
		});
		</script>
	</select>
	<select id="contentTasksFeedimporterCategorySelect" data-dojo-type="dijit/form/Select" data-dojo-props="maxHeight: 200">
		<option value="" disabled="disabled"><?php echo $this->translator()->_('config.selectCategory'); ?></option>
		<?php if ($this->categories) : ?>
		<?php foreach ($this->categories as $category) : ?>
		<option value="<?php echo $category->category_id; ?>"><?php echo str_repeat('---', $category->depth); ?> <?php echo $category->name; ?></option>
		<?php endforeach; ?>
		<?php endif; ?>
	</select>
	
	<button id="contentTasksFeedimporterAddButton" data-dojo-type="dijit/form/Button">
		<?php echo $this->translator()->_('config.addAction'); ?>
		<script type="dojo/on" data-dojo-event="click">
		require([
			"dojo/_base/array",
			"dojo/dom-construct",
			"dojo/dom-style",
			"dijit/registry",
			"dojo/query"
		], function(dojoArray, dojoDomConstruct, dojoDomStyle, dijitRegistry) {
			// Add feed entry
			var url		 = dijitRegistry.byId("contentTasksFeedimporterUrl").get("value");
			var language = dijitRegistry.byId("contentTasksFeedimporterLanguageSelect").get("value");
			var category = dijitRegistry.byId("contentTasksFeedimporterCategorySelect").get("value");
	
			if (url == "" || language == "" || category == "") {
				return;
			}
	
			dojoDomStyle.set("contentTasksFeedimporterFeedsHelp", {
				display: "block"
			});
	
			var div = dojoDomConstruct.create("div", {
				style: "padding-bottom: 4px",
				className: "contentTasksFeedimporterFeedItem"
			}, "contentTasksFeedimporterFeedsContainer");
			
			new dijit.form.TextBox({
				name: "urls[]",
				value: url,
				style: "width: 200px"
			}).placeAt(div);
	
			var languageSelect = new dijit.form.Select({
				name: "languages[]",
				value: language,
				style: "width: 150px",
				readOnly: true
			}).placeAt(div);
			dojoArray.forEach(dijitRegistry.byId("contentTasksFeedimporterLanguageSelect").getOptions(), function(option, index) {
				languageSelect.addOption(option);
			});
			languageSelect.set("value", language);
	
			var categorySelect = new dijit.form.Select({
				name: "categories[]"
			}).placeAt(div);
			dojoArray.forEach(dijitRegistry.byId("contentTasksFeedimporterCategorySelect").getOptions(), function(option, index) {
				categorySelect.addOption(option);
			});
			categorySelect.set("value", category);
	
			new dijit.form.Button({
				label: "<?php echo $this->translator()->_('config.deleteAction'); ?>",
				onClick: function() {
					dojoDomConstruct.destroy(div);
					var numFeeds = dojo.query("#contentTasksFeedimporterFeedsContainer .contentTasksFeedimporterFeedItem").length;
					dojoDomStyle.set("contentTasksFeedimporterFeedsHelp", {
						display: (numFeeds > 0) ? "block" : "none" 
					});
				}
			}).placeAt(div);
		});
		</script>
	</button>
</div>

<div id="contentTasksFeedimporterFeedsHelp" style="padding-bottom: 8px; display: <?php if ($this->feeds && count($this->feeds) > 0) : ?>block<?php else : ?>none<?php endif; ?>"><?php echo $this->translator()->_('config.listFeedsHelp'); ?></div>

<!-- Feeds -->
<div id="contentTasksFeedimporterFeedsContainer">
	<?php if ($this->feeds) : ?>
	<?php foreach ($this->feeds as $feed) : ?>
	<div style="padding-bottom: 4px" class="contentTasksFeedimporterFeedItem">
		<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'urls[]', style: 'width: 200px', value: '<?php echo $feed['url']; ?>'" />
		
		<select data-dojo-type="dijit/form/Select" data-dojo-props="name: 'languages[]', style: 'width: 150px', value: '<?php echo $feed['language']; ?>'">
			<option value="<?php echo $feed['language']; ?>"><?php echo $this->languages[$feed['language']]; ?></option>
		</select>
		
		<select data-dojo-type="dijit/form/Select" data-dojo-props="name: 'categories[]', maxHeight: 200, value: '<?php echo $feed['category']; ?>'">
			<?php if ($categories = $this->helper()->getCategories($feed['language'])) : ?>
			<?php foreach ($categories as $category) : ?>
			<option value="<?php echo $category->category_id; ?>"><?php echo str_repeat('---', $category->depth); ?> <?php echo $category->name; ?></option>
			<?php endforeach; ?>
			<?php endif; ?>
		</select>
		
		<button data-dojo-type="dijit/form/Button">
			<?php echo $this->translator()->_('config.deleteAction'); ?>
			<script type="dojo/on" data-dojo-event="click">
			var that = this;
			require([
				"dojo/dom-style",
				"dojo/NodeList-dom",
				"dojo/NodeList-traverse",
				"dojo/query"
			], function(dojoDomStyle) {
				var div = dojo.query(that.domNode).closest(".contentTasksFeedimporterFeedItem");
				dojo.query(div).orphan();
				
				var numFeeds = dojo.query("#contentTasksFeedimporterFeedsContainer .contentTasksFeedimporterFeedItem").length;
				dojoDomStyle.set("contentTasksFeedimporterFeedsHelp", {
					display: (numFeeds > 0) ? "block" : "none" 
				});
			});
			</script>
		</button>
	</div>
	<?php endforeach; ?>
	<?php endif; ?>
</div>
<!-- /Feeds -->

<div id="contentTasksFeedimporterStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'contentTasksFeedimporterCategorySelect', imageText: '<?php echo $this->translator(true)->_('config.loadingAction'); ?>'"></div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Select",
	"dijit/form/TextBox",
	"dojox/widget/Standby"	
]);
</script>
