<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		poll
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('poll.add.title'));
?>

<div id="pollPollAddContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="pollPollAddSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("pollPollAddForm").validate()) {
					dojoTopic.publish("/app/poll/poll/add/onStart");
					dojoRequestXhr("<?php echo $this->url(array(), 'poll_poll_add'); ?>", {
						data: dojoDomForm.toObject("pollPollAddForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						dojoTopic.publish("/app/poll/poll/add/onComplete", data);
					});
				}
			});
			</script>
		</button>
		
		<button id="pollPollAddCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/poll/poll/add/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, region: 'center'">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('poll.add.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<div id="pollPollAddForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('poll._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="language"><?php echo $this->translator()->_('poll._share.language'); ?>:</label>
							<select id="pollPollAddLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language'">
								<?php foreach ($this->languages as $language => $name) : ?>
								<option value="<?php echo $language; ?>"<?php if ($language == $this->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
					
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('poll._share.title'); ?>:</label>
							<input id="pollPollAddTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'title', type: 'text', value: '<?php if ($this->source) : ?><?php echo addslashes($this->source->title); ?><?php endif; ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('poll._share.titleRequired'); ?>'" />
						</div>
						
						<div class="app-form-row">
							<label for="description"><?php echo $this->translator()->_('poll._share.description'); ?>:</label>
							<textarea id="pollPollAddDescriptionTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'description', style: 'width: 300px; height: 150px'"><?php if ($this->source) : ?><?php echo $this->source->description; ?><?php endif; ?></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="multiple_options">&nbsp;</label>
							<input id="pollPollAddMultipleCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'multiple_options', value: true, checked: <?php if ($this->source && $this->source->multiple_options == "1") : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('poll._share.multipleOptionsHelp'); ?>
						</div>
						
						<input type="hidden" name="format" value="json" />
					</div>
					<!-- /Properties -->
					
					<!-- Options -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('poll._share.options'); ?>', class: 'app-content-pane'">
						<div style="padding: 8px 0">
							<?php echo $this->translator()->_('poll._share.optionHelp'); ?>
						</div>
						
						<div class="app-form-row">
							<div id="pollPollAddOptionsContainer" data-dojo-type="dojo/dnd/AutoSource" data-dojo-props="accept: ['pollOptionDnd'], selfAccept: true">
							<?php if ($this->sourceOptions) : ?>
								<?php foreach ($this->sourceOptions as $option) : ?>
								<div class="pollOption dojoDndItem" dndtype="pollOptionDnd">
									<input type="hidden" name="num_choices[]" value="<?php echo $option->num_choices; ?>" />
									<input data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'options[]', value: '<?php echo addslashes($option->title); ?>', style: 'width: 300px'" />
									<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
										<script type="dojo/on" data-dojo-event="click">
										var that = this;
										require([
											"dojo/dom-construct",
											"dojo/NodeList-traverse",
											"dojo/query"
										], function(dojoDomConstruct) {
											dojoDomConstruct.destroy(dojo.query(that.domNode).closest(".pollOption")[0]);	
										});
										</script>
									</button>
								</div>
								<?php endforeach; ?>
							<?php endif; ?>
							</div>
						</div>
						
						<div style="padding: 8px 0">
							<input id="pollPollAddNewOption" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', style: 'width: 300px', placeHolder: '<?php echo $this->translator(true)->_('poll._share.option'); ?>'" />
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.addAction'); ?>'">
								<script type="dojo/on" data-dojo-event="click">
								require([
									"dojo/dom-construct",
									"dijit/registry"
								], function(dojoDomConstruct, dijitRegistry) {
									// Add new option
									var div = dojoDomConstruct.create("div", {
										className: "pollOption dojoDndItem",
										dndtype: "pollOptionDnd"
									}, "pollPollAddOptionsContainer");
									new dijit.form.TextBox({
										name: "options[]",
										value: dijitRegistry.byId("pollPollAddNewOption").get("value"),
										style: "width: 300px"
									}).placeAt(div);
									new dijit.form.Button({
										label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
										onClick: function() {
											dojoDomConstruct.destroy(div);
										}
									}).placeAt(div);
								});
								</script>
							</button>
						</div>
					</div>
					<!-- /Options -->
					
					<!-- Localization -->
					<div id="pollPollAddLocalizedContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('poll._share.localization'); ?>', class: 'app-container-border', style: 'margin-top: 8px'">
						<?php if ($this->source) : ?>
						<div class="pollPollAddLocalizedItem" style="padding: 2px 8px">
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($this->source->title); ?>', style: 'width: 300px', readOnly: true" />
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($this->source->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
							<input type="hidden" name="translations" value='<?php echo $this->source->translations; ?>' />
							
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
								<script type="dojo/on" data-dojo-event="click">
								var that = this;
								require([
									"dojo/dom-construct",
									"dojo/dom-style",
									"dojo/NodeList-traverse",
									"dojo/query"
								], function(dojoDomConstruct, dojoDomStyle) {
									dojoDomConstruct.destroy(dojo.query(that.domNode).closest(".pollPollAddLocalizedItem")[0]);
									if (0 == dojo.query(".pollPollAddLocalizedItem", "pollPollAddLocalizedContainer").length) {
										// Show the guide
										dojoDomStyle.set("pollPollAddLocalizedHelp", "display", "block");
									}
								});
								</script>
							</button>
						</div>
						<?php endif; ?>
						
						<div id="pollPollAddLocalizedHelp" class="app-center" style="display: <?php if ($this->source) : ?>none<?php else : ?>block<?php endif; ?>">
							<div><?php echo $this->translator()->_('poll._share.localizationHelp'); ?></div>
						</div>
					</div>
					<!-- /Localization -->
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/_base/array",
	"dojo/dom-construct",
	"dojo/dom-style",
	"dojo/on",
	"dojo/ready",
	"dojo/parser",
	"dojo/query",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojo/dnd/AutoSource",
	"dojox/grid/enhanced/plugins/GridSource"	
], function(dojoArray, dojoDomConstruct, dojoDomStyle, dojoOn, dojoReady) {
	dojoReady(function() {
		// DOJO LESSON: Allow to drag poll from the grid and drop on the localized container
		var target = new dojox.grid.enhanced.plugins.GridSource("pollPollAddLocalizedContainer", {
			isSource: false,
			insertNodesForGrid: false
		});
		dojoOn(target, "dropgridrows", function(grid, rowIndexes) {
			var sourceItems = [];
			dojoArray.forEach(rowIndexes, function(rowIndex, index) {
				var item = grid.getItem(rowIndex);
				if (item) {
					sourceItems.push(item);
				}
			});

			if (sourceItems.length > 0) {
				// Hide the guide
				dojoDomStyle.set("pollPollAddLocalizedHelp", "display", "none");
			}

			dojoArray.forEach(sourceItems, function(item) {
				var div = dojoDomConstruct.create("div", {
					className: "pollPollAddLocalizedItem",
					style: "padding: 2px 8px"
				}, "pollPollAddLocalizedContainer");

				new dijit.form.TextBox({
					value: item.title[0],
					style: "width: 300px",
					readOnly: true
				}).placeAt(div);
				
				new dijit.form.TextBox({
					value: item.language[0],
					style: "margin: 0 8px; width: 100px",
					readOnly: true
				}).placeAt(div);

				dojoDomConstruct.create("input", {
					name: "translations",
					type: "hidden",
					value: item.translations[0]
				}, div);

				new dijit.form.Button({
					label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
					onClick: function() {
						dojoDomConstruct.destroy(div);
						if (dojo.query(".pollPollAddLocalizedItem", "pollPollAddLocalizedContainer").length == 0) {
							// Show the guide
							dojoDomStyle.set("pollPollAddLocalizedHelp", "display", "block");
						}
					}
				}).placeAt(div);
			});
		});
	});	
});
</script>
