<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		poll
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-11
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('poll.delete.title'));
?>

<?php if (!$this->poll) : ?>
	<div><?php echo $this->translator()->_('poll.delete.notFound'); ?></div>
<?php else : ?>
	<div>
		<?php echo sprintf($this->translator()->_('poll.delete.confirm'), $this->poll->title); ?>
	</div>
	
	<div class="dijitDialogPaneActionBar">
		<!-- YesButton -->
		<button id="pollPollDeleteYesButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.yesMessage'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/request/xhr",
				"dojo/topic"
			], function(dojoRequestXhr, dojoTopic) {
				dojoRequestXhr("<?php echo $this->url(array(), 'poll_poll_delete'); ?>", {
					data: {
						poll_id: "<?php echo $this->poll->poll_id; ?>",
						format: "json"
					},
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					dojoTopic.publish("/app/poll/poll/delete/onComplete", data);
				});
			});
			</script>
		</button>
		<!-- /YesButton -->
		
		<!-- NoButton -->
		<button id="pollPollDeleteNoButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.noMessage'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/poll/poll/delete/onCancel");
			});
			</script>
		</button>
		<!-- /NoButton -->
	</div>
<?php endif; ?>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button"
]);
</script>
