<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-08-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div id="mediaHooksVideoProviderContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, title: '<?php echo $this->translator(true)->_('show.title'); ?>'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: false">
		<div data-dojo-type="dijit/Toolbar">
			<input id="mediaHooksVideoProviderSearchTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', placeHolder: '<?php echo $this->translator(true)->_('show.keywordHelp'); ?>', style: 'width: 150px'" />
			<button id="mediaHooksVideoProviderSearchButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', showLabel: false, iconClass: 'app-icon app-icon-search', label: '<?php echo $this->translator(true)->_('show.searchAction'); ?>'">
				<script type="dojo/on" data-dojo-event="click">
				require(["dijit/registry"], function(dijitRegistry) {
					var keyword = dijitRegistry.byId("mediaHooksVideoProviderSearchTextBox").get("value");
					media.hooks.videoprovider.VideoController.searchVideos({
						title: keyword,
						page: 1
					});
				});
				</script>
			</button>
		</div>
	</div>
	<!-- /Toolbar -->
	
	<!-- VideosPane -->
	<div id="mediaHooksVideoProviderVideosContainer" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'center', loadingMessage: '<div class=app-center><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>', style: 'height: 100%; width: 100%'">
		<div class="app-center">
			<div><?php echo $this->translator()->_('show.searchHelp'); ?></div>
		</div>
	</div>
	<!-- /VideosPane -->
</div>

<?php $this->script()->captureStart(); ?>
/* media.hooks.videoprovider */
require([
	"dojo/_base/declare",
	"dojo/_base/lang",
	"dojo/io-query",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/layout/ContentPane",
	"core/js/base/Encoder"
], function(dojoDeclare, dojoLang, dojoIoQuery, dojoTopic, dijitRegistry) {
	dojoDeclare("media.hooks.videoprovider.VideoController", null, {});
	
	media.hooks.videoprovider.VideoController._criteria = {
		title: null,
		page: 1,
		per_page: 20
	};
	
	media.hooks.videoprovider.VideoController.searchVideos = function(/*Object*/ criteria) {
		// summary:
		//		Searches for videos
		dojoLang.mixin(media.hooks.videoprovider.VideoController._criteria, criteria);
		var q = core.js.base.Encoder.encode(media.hooks.videoprovider.VideoController._criteria);
	
		var params = {
			_type: "hook",
			_mod: "media",
			_name: "videoprovider",
			_method: "search",
			q: q
		};
		dijitRegistry.byId("mediaHooksVideoProviderVideosContainer")
					 .set("href", "<?php echo $this->url(array(), 'core_extension_render'); ?>" + "?" + dojoIoQuery.objectToQuery(params));
	};
	
	dojoTopic.subscribe("/app/media/hooks/videoprovider/search/onGotoPage", function(/*Integer*/ page) {
		// summary:
		//		Paging handler
		media.hooks.videoprovider.VideoController.searchVideos({
			page: page
		});
	});
});
<?php $this->script()->captureEnd(); ?>
