<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('playlist.add.title'));
?>

<div id="mediaPlaylistAddForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
	<script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
	e.preventDefault();
	var that = this;
	require([
		"dojo/dom-form",
		"dojo/request/xhr",
		"dojo/topic"
	], function(dojoDomForm, dojoRequestXhr, dojoTopic) {
		if (that.validate()) {
			dojoRequestXhr("<?php echo $this->url(array(), 'media_playlist_add'); ?>", {
				data: dojoDomForm.toObject("mediaPlaylistAddForm"),
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				dojoTopic.publish("/app/media/playlist/add/onComplete", data);
			});
		}
	});
	</script>
	
	<div class="app-form-row">
		<label for="slug"><?php echo $this->translator()->_('playlist._share.language'); ?>:</label>
		<select id="mediaPlaylistAddLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language', value: '<?php echo $this->language; ?>'">
			<?php foreach ($this->languages as $language => $name) : ?>
			<option value="<?php echo $language; ?>"<?php if ($language == $this->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
			<?php endforeach; ?>
		</select>
	</div>

	<div class="app-form-row">
		<label for="title"><?php echo $this->translator()->_('playlist._share.title'); ?>:</label>
		<div id="mediaPlaylistAddTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'title', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('playlist._share.titleRequired'); ?>'">
			<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
			require([
				"dojo/request/xhr",
				"dijit/registry"
			], function(dojoRequestXhr, dijitRegistry) {
				dojoRequestXhr("<?php echo $this->url(array(), 'core_helper_slug'); ?>", {
					data: {
						locale: dijitRegistry.byId("mediaPlaylistAddLanguageSelect").get("value"),
						input: value
					},
					handleAs: "json",
				}).then(function(data) {
					dijitRegistry.byId("mediaPlaylistAddSlugTextBox").set("value", data.output);
				});
			});
			</script>
		</div>
	</div>
	
	<div class="app-form-row">
		<label for="slug"><?php echo $this->translator()->_('playlist._share.slug'); ?>:</label>
		<input id="mediaPlaylistAddSlugTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('playlist._share.slugRequired'); ?>'" />
	</div>

	<div class="dijitDialogPaneActionBar">
		<button id="mediaPlaylistAddSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<?php echo $this->translator()->_('global._share.addAction'); ?>
		</button>

		<button id="mediaPlaylistAddCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/media/playlist/add/onCancel");
			});
			</script>
		</button>
	</div>

	<input type="hidden" name="format" value="json" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/ValidationTextBox"	
]);
</script>
