<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('playlist.list.title'));
?>

<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false">
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', splitter: false, class: 'app-content-pane'">
		<h2 class="app-heading" style="margin-top: 0">
			<span><?php echo sprintf($this->translator()->_('playlist.list.total'), '<b class="app-counter">' . $this->total . '</b>'); ?></span>
		</h2>

		<?php if ($this->total == 0) : ?>
		<?php echo $this->translator()->_('playlist.list.notFound'); ?>
		<?php else : ?>

		<ul>
			<li <?php if (!$this->criteria['active_playlist_id']) : ?>class="module-media-playlist-active" <?php endif; ?>style="padding-bottom: 8px">
				<a class="module-media-playlist-title" id="mediaPlaylistListFilterAll" href="javascript: void(0);">
					<?php echo $this->translator()->_('playlist.list.viewAll'); ?>
					<script type="dojo/on" data-dojo-event="click" data-dojo-args="e">
					var that = this;
					require(["dojo/topic"], function(dojoTopic) {
						dojoTopic.publish("/app/media/playlist/list/onViewAll", that.parentNode);
					});
					</script>
				</a>
			</li>
			
			<!-- Playlists -->
			<?php foreach ($this->playlists as $playlist) : ?>
			
			<li id="mediaPlaylistItem_<?php echo $playlist->playlist_id; ?>"
				class="module-media-playlist module-media-playlist-list<?php if ($playlist->playlist_id == $this->criteria['active_playlist_id']) : ?> module-media-playlist-active<?php endif; ?>"
				data-app-entity-props="<?php echo $this->encoder()->encode(array(
																		'playlist_id' => $playlist->playlist_id, 
																		'title'		  => $playlist->title,
																		'short_title' => $this->stringFormatter()->sub($playlist->title, 20),
																		'status'	  => $playlist->status,
																		'num_videos'  => $playlist->num_videos,
																		'poster'	  => $playlist->poster,
																		'view_type'   => $this->criteria['view_type'],
																	)); ?>">
				<div class="module-media-playlist-poster-container">
					<img class="module-media-playlist-poster" src="<?php if ($playlist->image_square) : ?><?php echo $playlist->getPoster('square'); ?><?php else : ?><?php echo $this->APP_ROOT_URL; ?>/modules/media/images/defaultPlaylistPoster.png<?php endif; ?>" />
				</div>
				
				<a class="module-media-playlist-title" href="javascript: void(0);"><?php echo $playlist->title; ?></a>
				
				<span class="app-counter"><?php echo $playlist->num_videos; ?></span>
			</li>
			
			<?php endforeach; ?>
			<!-- /Playlists -->

			<?php endif; ?>
		</ul>
	</div>

	<!-- Paginator -->
	<?php if ($this->paginator->count() > 1) : ?>
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'padding: -8px'">
		<?php echo $this->paginator('slidingToolbar')->render($this->paginator, "javascript: require(['dojo/topic'], function(dojoTopic) { dojoTopic.publish('/app/media/playlist/list/onGotoPage', __PAGE__); });"); ?>
	</div>
	<?php endif; ?>
	<!-- /Paginator -->
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar"	
]);
</script>
