<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-05
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('attachment.list.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/file/css/admin/default/styles.css");	
});
</script>

<div id="fileAttachmentListContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'app-container-border'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: false, style: 'height: 27px'">
			<div id="fileAttachmentListToolbar"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Attachments -->
		<div id="fileAttachmentListGridContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'">
		</div>
		<!-- /Attachments -->
		
		<!-- Paginator -->
		<div id="fileAttachmentListPaginator" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'height: 27px; padding: -8px'">
		</div>
		<!-- /Paginator -->
	</div>
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/file/languages')->_('attachment.list.title'); ?>";

require({
	paths: {
		"file": "<?php echo $this->APP_STATIC_URL; ?>/modules/file"
	}
});

require([
	"dojo/ready",
	"dojo/parser",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dojox/layout/ContentPane",
	"core/js/base/Config",
	"core/js/base/controllers/ActionProvider",
	"file/js/controllers/AttachmentController",
	"file/js/views/AttachmentGrid",
	"file/js/views/AttachmentToolbar"
], function(dojoReady) {
	dojoReady(function() {
		// Provide the actions
		<?php foreach (array(
						'file_attachment_add', 'file_attachment_delete', 'file_attachment_edit', 'file_attachment_list',
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
		});	
		<?php endforeach; ?>

		// Localization
		core.js.base.Config.set("core", "localization_languages", <?php echo $this->config("core", "localization_languages", '{"en_US":"English"}'); ?>);
		
		var attachmentController = new file.js.controllers.AttachmentController("fileAttachmentListContainer");
		attachmentController.setAttachmentToolbar(new file.js.views.AttachmentToolbar("fileAttachmentListToolbar"))
							.setAttachmentGrid(new file.js.views.AttachmentGrid("fileAttachmentListGridContainer"))
							.setAttachmentPaginator("fileAttachmentListPaginator")
							.initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>)
							.searchAttachments();
	});
});
</script>
