<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	views
 * @since		1.0
 * @version		2012-10-02
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('article.empty.title'));
?>

<div>
	<?php echo $this->translator()->_('article.empty.confirm'); ?>
</div>

<div class="dijitDialogPaneActionBar">
	<!-- YesButton -->
	<button id="contentArticleEmptyYesButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
		<?php echo $this->translator()->_('global._share.yesMessage'); ?>
		<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
		require([
			"dojo/request/xhr",
			"dojo/topic"
		], function(dojoRequestXhr, dojoTopic) {
			dojoRequestXhr("<?php echo $this->url(array(), 'content_article_empty'); ?>", {
				data: {
					format: "json"
				},
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				dojoTopic.publish("/app/content/article/empty/onComplete", data);
			});
		});
		</script>
	</button>
	<!-- /YesButton -->
	
	<!-- NoButton -->
	<button id="contentArticleEmptyNoButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
		<?php echo $this->translator()->_('global._share.noMessage'); ?>
		<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
		require(["dojo/topic"], function(dojoTopic) {
			dojoTopic.publish("/app/content/article/empty/onCancel");
		});
		</script>
	</button>
	<!-- /NoButton -->
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button"
]);
</script>
