<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('language.edit.title'));
?>

<div id="coreLanguageEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
	<script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
	e.preventDefault();
	var that = this;
	require([
		"dojo/dom-form",
		"dojo/request/xhr",
		"dojo/topic"
	], function(dojoDomForm, dojoRequestXhr, dojoTopic) {
		if (that.validate()) {
			dojoRequestXhr("<?php echo $this->url(array(), 'core_language_edit'); ?>", {
				data: dojoDomForm.toObject("coreLanguageEditForm"),
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				that.reset();
				dojo.publish("/app/core/language/edit/onComplete", [ data ]);
			});
		}
	});
	</script>
	
	<div class="app-form-row">
		<label for="path"><?php echo $this->translator()->_('language._share.path'); ?>:</label>
		<input id="coreLanguageEditPathTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'path', style: 'width: 250px', readOnly: true, value: '<?php echo addslashes($this->path); ?>'" />
	</div>
	
	<div class="app-form-row">
		<label for="text"><?php echo $this->translator()->_('language._share.text'); ?>:</label>
		<textarea id="coreLanguageEditTextTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="type: 'text', name: 'text', style: 'width: 250px; height: 50px'"><?php echo $this->text; ?></textarea>
	</div>
	
	<div class="dijitDialogPaneActionBar">
		<button id="coreLanguageEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>
		
		<button id="coreLanguageEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/core/language/edit/onCancel");
			});
			</script>
		</button>
	</div>
	
	<input type="hidden" name="format" value="json" />
	<input type="hidden" name="file" value="<?php echo addslashes($this->file); ?>" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox"	
]);
</script>
