<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<li id="mediaAlbumItem_<?php echo $this->album->album_id; ?>"
	class="module-media-album module-media-album-list<?php if ($this->album->album_id == $this->criteria['active_album_id']) : ?> module-media-album-active<?php endif; ?>"
	data-app-entity-props="<?php echo $this->encoder()->encode(array(
																'album_id'	  => $this->album->album_id,
																'title'		  => $this->album->title,
																'short_title' => $this->stringFormatter()->sub($this->album->title, 20),
																'status'	  => $this->album->status,
																'num_photos'  => $this->album->num_photos,
																'cover'		  => $this->album->cover,
																'view_type'	  => $this->criteria['view_type'],
															)); ?>">
	<div class="module-media-album-cover-container">
		<img class="module-media-album-cover" src="<?php if ($this->album->image_square) : ?><?php echo $this->album->getCover('square'); ?><?php else : ?><?php echo $this->APP_ROOT_URL; ?>/modules/media/images/defaultAlbumCover.png<?php endif; ?>" />
	</div>
	
	<a class="module-media-album-title" href="javascript: void(0);"><?php echo $this->album->title; ?></a>
	
	<span class="app-counter"><?php echo $this->album->num_photos; ?></span>
</li>
