<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('album.delete.title'));
?>

<div>
<?php if (!$this->album) : ?>
	<?php echo $this->translator()->_('album.delete.notFound'); ?>
<?php else : ?>
	<?php echo sprintf($this->translator()->_('album.delete.confirm'), $this->album->title); ?>
<?php endif; ?>
</div>

<div class="dijitDialogPaneActionBar">
	<!-- YesButton -->
	<?php if ($this->album) : ?>
	<button id="mediaAlbumDeleteYesButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
		<?php echo $this->translator()->_('global._share.yesMessage'); ?>
		<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
		require([
			"dojo/request/xhr",
			"dojo/topic"
		], function(dojoRequestXhr, dojoTopic) {
			dojoRequestXhr("<?php echo $this->url(array(), 'media_album_delete'); ?>", {
				data: {
					album_id: "<?php echo $this->album->album_id; ?>",
					format: "json"
				},
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				if ("APP_RESULT_OK" == data.result) {
					dojoTopic.publish("/app/media/album/delete/onSuccess", data);
				}
			});
		});
		</script>
	</button>
	<?php endif; ?>
	<!-- /YesButton -->

	<!-- NoButton -->
	<button id="mediaAlbumDeleteNoButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
		<?php if ($this->album) : ?>
			<?php echo $this->translator()->_('global._share.noMessage'); ?>
		<?php else : ?>
			<?php echo $this->translator()->_('global._share.closeAction'); ?>
		<?php endif; ?>
		<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
		require(["dojo/topic"], function(dojoTopic) {
			dojoTopic.publish("/app/media/album/delete/onCancel");
		});
		</script>
	</button>
	<!-- /NoButton -->
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button"
]);
</script>
