<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-08-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="app-form">
	<div class="app-form-row" style="width: 100%">
		<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%; width: 100%', closable: true, doLayout: false">
			<!-- Basic -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="selected: true, title: '<?php echo $this->translator(true)->_('config.basic'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row-vertical">
					<label for="introduction"><?php echo $this->translator()->_('config.introduction'); ?>:</label>
					<textarea data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'introduction', class: 'appWidgetInput', style: 'height: 100px; width: 90%'"></textarea>
				</div>
				
				<div class="app-form-row-vertical">
					<label for="rss"><?php echo $this->translator()->_('config.rss'); ?>:</label>
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'rss', class: 'appWidgetInput', style: 'width: 98%'" />
				</div>
				
				<div class="app-form-row-vertical">
					<label for="twitter"><?php echo $this->translator()->_('config.twitter'); ?>:</label>
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'twitter', class: 'appWidgetInput', style: 'width: 98%'" />
				</div>
				
				<div class="app-form-row-vertical">
					<label for="facebook"><?php echo $this->translator()->_('config.facebook'); ?>:</label>
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'facebook', class: 'appWidgetInput', style: 'width: 98%'" />
				</div>
				
				<div class="app-form-row-vertical">
					<label for="youtube"><?php echo $this->translator()->_('config.youtube'); ?>:</label>
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'youtube', class: 'appWidgetInput', style: 'width: 98%'" />
				</div>
			</div>
			<!-- /Basic -->
			
			<!-- Theme -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.theme'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row">
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'theme', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Theme -->
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer"	
]);
</script>
