<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		menu
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-27
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('menu.list.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");	
});
</script>

<div id="menuMenuListContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'app-container-border'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="menuMenuListToolbar" style="height: 27px"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Menus -->
		<div id="menuMenuListGridContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'">
		</div>
		<!-- /Menus -->
		
		<!-- Paginator -->
		<div id="menuMenuListPaginator" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'height: 27px; padding: -8px'">
		</div>
		<!-- /Paginator -->
	</div>
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/menu/languages')->_('menu.list.title'); ?>";

require({
	paths: {
		"menu": "<?php echo $this->APP_STATIC_URL; ?>/modules/menu"
	}
});

require([
	"dojo/ready",
	"dojo/parser",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dojox/layout/ContentPane",
	"core/js/base/Config",
	"core/js/base/controllers/ActionProvider",
	"menu/js/controllers/MenuController",
	"menu/js/views/MenuGrid",
	"menu/js/views/MenuToolbar"	
], function(dojoReady) {
	dojoReady(function() {
		// Provide the actions
		<?php foreach (array(
						'menu_menu_add', 'menu_menu_delete', 'menu_menu_edit', 'menu_menu_list',
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
		});	
		<?php endforeach; ?>

		// Localization
		core.js.base.Config.set("core", "localization_languages", <?php echo $this->config("core", "localization_languages", '{"en_US":"English"}'); ?>);

		var menuController = new menu.js.controllers.MenuController("menuMenuListContainer");
		menuController.setMenuToolbar(new menu.js.views.MenuToolbar("menuMenuListToolbar"))
					  .setMenuGrid(new menu.js.views.MenuGrid("menuMenuListGridContainer"))
					  .setMenuPaginator("menuMenuListPaginator")
					  .initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>)
					  .searchMenus();
	});	
});
</script>
