<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		message
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('filter.list.title'));
?>

<div id="messageFilterListContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="messageFilterListCloseButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.closeAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/message/filter/list/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', class: 'app-content-pane'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('filter.add.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
			<!-- AddNewFilter -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', class: 'app-content-pane'">
				<div id="messageFilterListAddFilterForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST'">
					<div class="app-left">
						<select id="messageFilterListObjectSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'object', style: 'width: 100px'">
							<option value="" disabled="disabled"><?php echo $this->translator()->_('filter._share.if'); ?></option>
							<option type="separator"></option>
							<option value="<?php echo Message_Models_Filter::OBJECT_SUBJECT; ?>"><?php echo $this->translator()->_('filter._share.subject'); ?></option>
							<option value="<?php echo Message_Models_Filter::OBJECT_CONTENT; ?>"><?php echo $this->translator()->_('filter._share.content'); ?></option>
							<option value="<?php echo Message_Models_Filter::OBJECT_FROM; ?>"><?php echo $this->translator()->_('filter._share.from'); ?></option>
							
							<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
							require([
								"dojo/dom-style",
								"dijit/registry"
							], function(dojoDomStyle, dijitRegistry) {
								// If user is going to create a "from" filter, show the container for droppping user from the User toolbox
								var condition		 = dijitRegistry.byId("messageFilterListConditionSelect").get("value");
								var showUserSelector = (value == "<?php echo Message_Models_Filter::OBJECT_FROM; ?>")
														&& (condition == "<?php echo Message_Models_Filter::CONDITION_IS; ?>" || condition == "<?php echo Message_Models_Filter::CONDITION_NOT; ?>");
								dojoDomStyle.set(dijitRegistry.byId("messageFilterListComparisonTextBox").domNode, "display", showUserSelector ? "none" : "block");
								dojoDomStyle.set("messageFilterListUserCollection", "display", showUserSelector ? "block" : "none");
							});
							</script>
						</select>
					</div>
		
					<div class="app-left" style="margin: 0 4px">			
						<select id="messageFilterListConditionSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'condition', style: 'width: 150px'">
							<option value="" disabled="disabled"><?php echo $this->translator()->_('filter._share.satifyCondition'); ?></option>
							<option type="separator"></option>
							<option value="<?php echo Message_Models_Filter::CONDITION_LIKE; ?>"><?php echo $this->translator()->_('filter._share.isLike'); ?></option>
							<option value="<?php echo Message_Models_Filter::CONDITION_NOT_LIKE; ?>"><?php echo $this->translator()->_('filter._share.isNotLike'); ?></option>
							<option value="<?php echo Message_Models_Filter::CONDITION_IS; ?>"><?php echo $this->translator()->_('filter._share.is'); ?></option>
							<option value="<?php echo Message_Models_Filter::CONDITION_NOT; ?>"><?php echo $this->translator()->_('filter._share.isNot'); ?></option>
							<option value="<?php echo Message_Models_Filter::CONDITION_BEGIN; ?>"><?php echo $this->translator()->_('filter._share.beginsWith'); ?></option>
							<option value="<?php echo Message_Models_Filter::CONDITION_END; ?>"><?php echo $this->translator()->_('filter._share.endsWith'); ?></option>
							
							<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
							require([
								"dojo/dom-style",
								"dijit/registry"
							], function(dojoDomStyle, dijitRegistry) {
								// If user is going to create a "from" filter, show the container for droppping user from the User toolbox
								var object			 = dijitRegistry.byId("messageFilterListObjectSelect").get("value");
								var showUserSelector = (object == "<?php echo Message_Models_Filter::OBJECT_FROM; ?>")
														&& (value == "<?php echo Message_Models_Filter::CONDITION_IS; ?>" || value == "<?php echo Message_Models_Filter::CONDITION_NOT; ?>");
								dojoDomStyle.set(dijitRegistry.byId("messageFilterListComparisonTextBox").domNode, "display", showUserSelector ? "none" : "block");
								dojoDomStyle.set("messageFilterListUserCollection", "display", showUserSelector ? "block" : "none");
							});
							</script>
						</select>
					</div>
					
					<div class="app-left" style="margin: 0 4px">
						<input id="messageFilterListComparisonTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'comparison_to', style: 'width: 300px'" />
						
						<!-- UserSelector -->
						<div id="messageFilterListUserCollection" style="display: none; width: 100px"></div>
						<!-- /UserSelector -->
					</div>
					
					<div style="clear: both"></div>
					
					<div style="padding: 8px 0">
						<div style="padding: 4px 0"><?php echo $this->translator()->_('filter._share.doActions'); ?>:</div>
						
						<?php if ($this->folders) : ?>
						<div style="padding: 4px 0">
							<div id="messageFilterListMoveFolderCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'actions[]', value: '<?php echo Message_Models_Filter::ACTION_MOVE; ?>'">
								<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
								require(["dijit/registry"], function(dijitRegistry) {
									dijitRegistry.byId("messageFilterListFolderSelect").set("disabled", value == false);
								});
								</script>
							</div>
							<?php echo $this->translator()->_('filter._share.moveToFolder'); ?>
							<select id="messageFilterListFolderSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'folder_id', disabled: true, style: 'width: 150px'">
								<?php foreach ($this->folders as $folder) : ?>
								<option value="<?php echo $folder->folder_id; ?>"><?php echo $folder->name; ?></option>
								<?php endforeach; ?>
								
								<script type="dojo/on">
								var that = this;
								require(["dojo/topic"], function(dojoTopic) {
									// Update the list of folders
									// after adding new folder
									dojoTopic.subscribe("/app/message/folder/add/onComplete", function(data) {
										if ("APP_RESULT_OK" == data.result) {
											that.addOption({
												label: data.name,
												value: data.folder_id + ""
											});
										}
									});
									// after deleting the folder
									dojoTopic.subscribe("/app/message/folder/delete/onComplete", function(data) {
										if ("APP_RESULT_OK" == data.result) {
											that.removeOption({
												label: data.name,
												value: data.folder_id + ""
											});
										}
									});
									// after renaming the folder
									dojoTopic.subscribe("/app/message/folder/rename/onSuccess", function(data) {
										that.updateOption({
											label: data.name,
											value: data.folder_id + ""
										});
									});
								});
								</script>
							</select>
						</div>
						<?php endif; ?>
						
						<div style="padding: 4px 0"><input id="messageFilterListMarkReadCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'actions[]', value: '<?php echo Message_Models_Filter::ACTION_MARK_READ; ?>'" /> <?php echo $this->translator()->_('filter._share.markAsRead'); ?></div>
						<div style="padding: 4px 0"><input id="messageFilterListStarCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'actions[]', value: '<?php echo Message_Models_Filter::ACTION_START; ?>'" /> <?php echo $this->translator()->_('filter._share.starMessage'); ?></div>
						<div style="padding: 4px 0"><input id="messageFilterListDeleteCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'actions[]', value: '<?php echo Message_Models_Filter::ACTION_DELETE; ?>'" /> <?php echo $this->translator()->_('filter._share.deleteMessage'); ?></div>
					</div>
					
					<button id="messageFilterListAddButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('global._share.addAction'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						require([
							"dojo/dom-form",
							"dojo/request/xhr",
							"dojo/topic",
							"dijit/registry"
						], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
							var params = dojoDomForm.toObject("messageFilterListAddFilterForm");

							// Validate the form
							if (params.object == "<?php echo Message_Models_Filter::OBJECT_FROM; ?>"
									&& (params.condition == "<?php echo Message_Models_Filter::CONDITION_IS; ?>" || params.condition == "<?php echo Message_Models_Filter::CONDITION_NOT; ?>")) {
								if (params.from_address == null) {
									dojoTopic.publish("/app/global/notification", {
										message: "<?php echo $this->translator()->_('filter._share.fromAddressRequired'); ?>",
										type: "error"
									});
									return;
								} else {
									params.comparison_to = params.from_address;
								}
							} else if (params.comparison_to == "") {
								dojoTopic.publish("/app/global/notification", {
									message: "<?php echo $this->translator()->_('filter._share.comparisonRequired'); ?>",
									type: "error"
								});
								return;
							}
							dijitRegistry.byId("messageFilterListStandby").show();
							dojoRequestXhr("<?php echo $this->url(array(), 'message_filter_add'); ?>", {
								data: params,
								handleAs: "json",
								method: "POST"
							}).then(function(data) {
								dijitRegistry.byId("messageFilterListAddFilterForm").reset();
								dijitRegistry.byId("messageFilterListStandby").hide();
								var message = ("APP_RESULT_OK" == data.result)
											? "<?php echo $this->translator()->_('filter.add.success'); ?>"
											: "<?php echo $this->translator()->_('filter.add.error'); ?>";
								dojoTopic.publish("/app/global/notification", {
									message: message,
									type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
								});
	
								// Reload the filters
								dijitRegistry.byId("messageFilterListFiltersPane").set("href", "<?php echo $this->url(array(), 'message_filter_list'); ?>?format=html");
							});
						});
						</script>
					</button>
					
					<input type="hidden" name="format" value="html" />
				</div>
				
				<div style="clear: both"></div>
			</div>
			<!-- /AddNewFilter -->
			
			<!-- Filters -->
			<div id="messageFilterListFiltersPane" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'center', href: '<?php echo $this->url(array(), 'message_filter_list'); ?>?format=html', loadingMessage: '<div class=app-center><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>'">
			</div>
			<!-- /Filters -->
		</div>
	</div>
</div>

<div id="messageFilterListStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'messageFilterListContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
require([
	"dojo/ready",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/layout/ContentPane",
	"dojox/widget/Standby",
	"core/js/views/UserCollectionView"
], function(dojoReady) {
	dojoReady(function() {
		var fromUserCollection = new core.js.views.UserCollectionView("messageFilterListUserCollection", "from_address");
	});
});
</script>
