<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-08-29
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="app-form">
	<div class="app-form-row" style="width: 100%">
		<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%; width: 100%', closable: true, doLayout: false">
			<!-- Basic -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="selected: true, title: '<?php echo $this->translator(true)->_('config.basic'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row-vertical">
					<label for="api_key"><?php echo $this->translator()->_('config.apiKey'); ?>:</label>
					<input data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'api_key', required: true, class: 'appWidgetInput', style: 'width: 98%', missingMessage: '<?php echo $this->translator(true)->_('config.apiKeyRequired'); ?>'" />
				</div>
			
				<div class="app-form-row-vertical">
					<label for="limit"><?php echo $this->translator()->_('config.numberOfPhotos'); ?>:</label>
					<input data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'limit', required: true, class: 'appWidgetInput', style: 'width: 100px', missingMessage: '<?php echo $this->translator(true)->_('config.numberOfPhotosRequired'); ?>'" />
				</div>
				
				<div class="app-form-row-vertical">
					<label for="size"><?php echo $this->translator()->_('config.size'); ?>:</label>
					<select data-dojo-type="dijit/form/Select" data-dojo-props="name: 'size', class: 'appWidgetInput'">
						<?php foreach (array('Square', 'Thumbnail', 'Small', 'Medium', 'Large', 'Original') as $size) : ?>
						<option value="<?php echo $size; ?>"><?php echo $this->translator()->_('config.size' . $size); ?></option>
						<?php endforeach; ?>
					</select>
				</div>
				
				<div class="app-form-row-vertical">
					<label for="search_by"><input data-dojo-type="dijit/form/RadioButton" data-dojo-props="name: 'search_by', value: 'tag', class: 'appWidgetInput'" /> <?php echo $this->translator()->_('config.searchByTag'); ?></label>
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'tag', class: 'appWidgetInput', style: 'width: 98%'" />
				</div>
				
				<div class="app-form-row-vertical">
					<label for="search_by"><input data-dojo-type="dijit/form/RadioButton" data-dojo-props="name: 'search_by', value: 'user', class: 'appWidgetInput'" /> <?php echo $this->translator()->_('config.searchByUser'); ?></label>
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'user', class: 'appWidgetInput', style: 'width: 50%'" />
				</div>
			</div>
			<!-- /Basic -->
			
			<!-- Theme -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.theme'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row">
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'theme', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Theme -->
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/CheckBox",
	"dijit/form/Select",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer"	
]);
</script>
