<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-08-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="app-form">
	<div class="app-form-row" style="width: 100%">
		<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%; width: 100%', closable: true, doLayout: false">
			<!-- Basic -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="selected: true, title: '<?php echo $this->translator(true)->_('config.basic'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row-vertical">
					<label for="address"><?php echo $this->translator()->_('config.address'); ?>:</label>
					<input id="utilWidgetsGooglemapConfigAddress_<?php echo $this->uid; ?>" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'address', class: 'appWidgetInput', style: 'width: 98%', missingMessage: '<?php echo $this->translator(true)->_('config.addressRequired'); ?>'" />
				</div>
				
				<div id="utilWidgetsGooglemapConfigMessage_<?php echo $this->uid; ?>" class="app-form-row">
				</div>
				
				<div class="app-form-row">
					<button data-dojo-type="dijit/form/Button">
						<?php echo $this->translator()->_('config.defineLocationAction'); ?>
						<script type="dojo/on" data-dojo-event="click">
						require([
							"dojo/dom-attr",
							"dojo/dom-style",
							"dojo/request/xhr",
							"dijit/registry"
						], function(dojoDomAttr, dojoDomStyle, dojoRequestXhr, dijitRegistry) {
							var addressBox = dijitRegistry.byId("utilWidgetsGooglemapConfigAddress_<?php echo $this->uid; ?>");
							dojoRequestXhr("<?php echo $this->url(array(), 'core_extension_render'); ?>", {
								data: {
									_mod: "util",
									_name: "googlemap",
									_type: "widget",
									_method: "config",
									_format: "json",
									noRenderScript: true,
									address: addressBox.get("value")
								},
								handleAs: "json",
								method: "POST"
							}).then(function(data) {
								if (data.latitude && data.longitude) {
									addressBox.set("value", data.address);
									dojoDomStyle.set("utilWidgetsGooglemapConfigMessage_<?php echo $this->uid; ?>", "display", "none");
									dijitRegistry.byId("utilWidgetsGooglemapConfigLatitude_<?php echo $this->uid; ?>").set("value", data.latitude);
									dijitRegistry.byId("utilWidgetsGooglemapConfigLongitude_<?php echo $this->uid; ?>").set("value", data.longitude);
								} else {
									dojoDomStyle.set("utilWidgetsGooglemapConfigMessage_<?php echo $this->uid; ?>", "display", "block");
									dojoDomAttr.set("utilWidgetsGooglemapConfigMessage_<?php echo $this->uid; ?>", "innerHTML", "<?php echo $this->translator()->_('config.cannotDefineLocation'); ?>");
								}
							});
						});
						</script>
					</button>
				</div>
				
				<div class="app-form-row-vertical">
					<label for="zoom"><?php echo $this->translator()->_('config.zoomLevel'); ?>:</label>
					<input data-dojo-type="dijit/form/NumberSpinner" id="utilWidgetsGooglemapConfigZoom_<?php echo $this->uid; ?>" data-dojo-props="name: 'zoom', 'class': 'appWidgetInput', smallDelta: 1, constraints: { min: 1, max: 21, places: 0 }" />
				</div>

				<div class="app-form-row-vertical">
					<label for="latitude"><?php echo $this->translator()->_('config.latitude'); ?>:</label>
					<input id="utilWidgetsGooglemapConfigLatitude_<?php echo $this->uid; ?>" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'latitude', class: 'appWidgetInput'" />
				</div>

				<div class="app-form-row-vertical">
					<label for="longitude"><?php echo $this->translator()->_('config.longitude'); ?>:</label>
					<input id="utilWidgetsGooglemapConfigLongitude_<?php echo $this->uid; ?>" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'longitude', 'class': 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Basic -->
			
			<!-- Theme -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.theme'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row">
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'theme', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Theme -->
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/NumberSpinner",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer"
]);
</script>
