<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		tag
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('config._share.title'));
?>

<div id="tagConfigConfigContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'app-container-border'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="tagConfigConfigSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("tagConfigConfigForm").validate()) {
					var params = dojoDomForm.toObject("tagConfigConfigForm");
	
					// Ask user to select at least one tag suggestions service if enabled
					if (params.suggestion_enabled == "on" && params.opencalais_enabled != "on" && params.yql_enabled != "on") {
						dojoTopic.publish("/app/global/notification", {
							message: "<?php echo $this->translator()->_('config.config.tagSuggestionsServiceRequired'); ?>",
							type: "error"
						});
						return;
					}
	
					dijitRegistry.byId("tagConfigConfigStandby").show();
					that.set("disabled", true);
	
					dojoRequestXhr("<?php echo $this->url(array(), 'tag_config_config'); ?>", {
						data: params,
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("tagConfigConfigStandby").hide();
						dojoTopic.publish("/app/global/notification", {
							message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->_('config.config.success'); ?>" : "<?php echo $this->translator()->_('config.config.error'); ?>",
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					});
				}
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- ConfigForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
		<div id="tagConfigConfigForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('config.config.title'); ?></span></h2>
			
			<div class="app-form-row">
				<div id="tagConfigConfigTagSuggestionsCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'suggestion_enabled', value: 1, checked: <?php if ($this->suggestionsEnabled) : ?>true<?php else : ?>false<?php endif; ?>">
					<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
					require(["dijit/registry"], function(dijitRegistry) {
						dijitRegistry.byId("tagConfigConfigOpenCalaisCheckBox").set("disabled", !value);
						dijitRegistry.byId("tagConfigConfigYqlCheckBox").set("disabled", !value);
						if (!value) {
							dijitRegistry.byId("tagConfigConfigOpenCalaisCheckBox").set("checked", false);
							dijitRegistry.byId("tagConfigConfigYqlCheckBox").set("checked", false);
						}
					});
					</script>
				</div>
				<?php echo $this->translator()->_('config.config.tagSuggestionsEnabled'); ?>
			</div>
			
			<div class="app-form-row">
				<div id="tagConfigConfigOpenCalaisCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'opencalais_enabled', value: 1, checked: <?php if ($this->suggestionsEnabled && $this->openCalaisEnabled) : ?>true<?php else : ?>false<?php endif; ?>">
					<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
					require(["dijit/registry"], function(dijitRegistry) {
						dijitRegistry.byId("tagConfigConfigOpenCalaisApiTextBox").set("disabled", !value);
					});
					</script>
				</div>
				<?php echo stripslashes($this->translator()->_('config.config.tagSuggestionsOpenCalaisService')); ?>
				<input id="tagConfigConfigOpenCalaisApiTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'opencalais_api_key', value: '<?php echo addslashes($this->config('tag', 'opencalais_api_key', '')); ?>', disabled: <?php if ($this->suggestionsEnabled && $this->openCalaisEnabled) : ?>false<?php else : ?>true<?php endif; ?>, style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config.config.tagSuggestionsOpenCalaisApiKeyRequired'); ?>'" />
			</div>
			
			<div class="app-form-row">
				<input id="tagConfigConfigYqlCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'yql_enabled', value: 1, checked: <?php if ($this->suggestionsEnabled && $this->yqlEnabled) : ?>true<?php else : ?>false<?php endif; ?>" />
				<?php echo stripslashes($this->translator()->_('config.config.tagSuggestionsYahooQueryLanguageService')); ?>
			</div>
			
			<input type="hidden" name="format" value="json" />
		</div>
	</div>
	<!-- /ConfigForm -->
</div>

<div id="tagConfigConfigStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'tagConfigConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/tag/languages')->_('config.config.title'); ?>";

require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/widget/Standby"	
]);
</script>
