<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-14
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('page.filter.title'));
?>

<div id="corePageFilterForm" data-dojo-type="dijit/form/Form" data-dojo-props="class: 'app-form'">
	<!-- Filters -->
	<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, region: 'center', style: 'height: 300px'">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('page.filter.availableFilters'); ?>'">
			<?php if (!$this->filters && count($this->filters) == 0) : ?>
				<?php echo $this->translator()->_('page.filter.notFound'); ?>
			<?php else : ?>
			
			<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, style: 'padding: 0'">
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'margin: 8px 0px'">
					<?php echo $this->translator()->_('page.filter.filterDndHelp'); ?>
				</div>
			
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-container-border'">
					<div data-dojo-type="dojo/dnd/AutoSource" data-dojo-props="accept: ['corePageFilterDnd'], selfAccept: true" class="app-content-pane">
						<?php foreach ($this->filters as $filter) : ?>
						<div style="padding-bottom: 8px" class="dojoDndItem" dndtype="corePageFilterDnd">
							<input id="corePageFilterCheckBox_<?php echo $filter->clazz; ?>" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'filters[]', value: '<?php echo $filter->clazz; ?>', checked: <?php if ($filter->used) : ?>true<?php else : ?>false<?php endif; ?>" />
							<?php echo $this->extensionTranslator()->translateTitle($filter); ?>: <?php echo $this->extensionTranslator()->translateDescription($filter); ?>
						</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
			
			<?php endif; ?>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('page.filter.additionalFilters'); ?>'">
			<div style="margin: 8px 0px">
				<?php echo $this->translator()->_('page.filter.setClassesHelp'); ?>:
			</div>
			<textarea id="corePageFilterClassesTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'classes', style: 'height: 100px; width: 95%'"><?php echo $this->classes; ?></textarea>	
		</div>
	</div>
	<!-- /Filters -->
		
	<div class="dijitDialogPaneActionBar">
		<!-- SaveButton -->
		<?php if ($this->filters && count($this->filters) > 0) : ?>
		<button id="corePageFilterSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/dom-form",
				"dojo/topic"
			], function(dojoDomForm, dojoTopic) {
				var data = dojoDomForm.toObject("corePageFilterForm");
				dojoTopic.publish("/app/core/page/filter/onSave", {
					container_id: data.container_id,
					filters: data["filters[]"],
					classes: data.classes
				});
			});
			</script>
		</button>
		<?php endif; ?>
		<!-- /SaveButton -->
		
		<!-- CancelButton -->
		<button id="corePageFilterCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/core/page/filter/onCancel");
			});
			</script>
		</button>
		<!-- /CancelButton -->
	</div>
	
	<input type="hidden" name="container_id" value="<?php echo $this->container_id; ?>" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dojo/dnd/AutoSource"
]);
</script>
