<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-09-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="coreWidgetsLogin">
	<?php if (!$this->user) : ?>
		<div data-dojo-type="dijit/form/Form" data-dojo-props="action: '<?php echo $this->url(array(), 'core_auth_login'); ?>', method: 'POST'">
			<script type="dojo/method" data-dojo-event="onSubmit">
			return (this.validate());
			</script>
		
			<div class="coreWidgetLoginTitle"><?php echo $this->translator()->_('show.title'); ?></div>
			
			<!-- DefaultAuthentication -->
			<div style="padding-bottom: 8px" id="coreWidgetsLoginDefaultContainer">
				<div style="padding-bottom: 4px">
					<input id="coreWidgetsLoginUsername" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'username', style: 'width: 150px', pattern: '[\\w]+', required: true, placeHolder: '<?php echo $this->translator(true)->_('show.username'); ?>', missingMessage: '<?php echo $this->translator(true)->_('show.usernameRequired'); ?>', invalidMessage: '<?php echo $this->translator(true)->_('show.usernameValidator'); ?>'" />
				</div>
				<div style="padding-bottom: 4px">
					<input id="coreWidgetsLoginPassword" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'password', name: 'password', style: 'width: 150px', required: true, placeHolder: '<?php echo $this->translator(true)->_('show.password'); ?>', missingMessage: '<?php echo $this->translator(true)->_('show.passwordRequired'); ?>'" />
				</div>
				<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
					<?php echo $this->translator()->_('show.loginButton'); ?>
				</button>
			</div>
			<!-- /DefaultAuthentication -->
			
			<!-- OpenIdAuthentication -->
			<?php if ($this->openIdEnabled) : ?>
			<div style="display: none; padding-bottom: 8px" id="coreWidgetsLoginOpenIdContainer">
				<div style="padding-bottom: 4px">
					<input id="coreWidgetsLoginOpenIdUrl" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'openid_url', style: 'width: 300px', disabled: true, required: true, placeHolder: '<?php echo $this->translator(true)->_('show.openIdUrl'); ?>', missingMessage: '<?php echo $this->translator(true)->_('show.openIdUrlRequired'); ?>', invalidMessage: '<?php echo $this->translator(true)->_('show.openIdUrlValidator'); ?>'" />
				</div>
				<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
					<?php echo $this->translator()->_('show.loginButton'); ?>
				</button>
			</div>
			<?php endif; ?>
			<!-- /OpenIdAuthentication -->
			
			<div style="padding-bottom: 16px">
				<?php if ($this->openIdEnabled) : ?><a href="javascript: void(0);" id="coreWidgetsLoginOpenId" data-app-login="openid"><?php echo $this->translator()->_('show.loginUsingOpenId'); ?></a> | <?php endif; ?><a href="<?php echo $this->url(array(), 'core_password_send'); ?>"><?php echo $this->translator()->_('show.forgotPassword'); ?></a>
				<?php if ($this->config('core', 'register_enabled') == 'true') : ?> | <a href="<?php echo $this->url(array(), 'core_registration_register'); ?>"><?php echo $this->translator()->_('show.registration'); ?></a><?php endif; ?>
			</div>
			
			<input type="hidden" name="return" value="<?php echo $this->returnUrl; ?>" />
		</div>
	<?php else : ?>
		<div class="coreWidgetsLoginWelcome"><?php echo sprintf($this->translator()->_('show.welcome', $this->user->user_name)); ?></div>
		<div class="coreWidgetsLoginLogout">
			<a href="<?php echo $this->url(array(), 'core_auth_logout'); ?>"><?php echo $this->translator()->_('show.logout'); ?></a>
		</div>
	<?php endif; ?>
</div>

<script type="text/javascript">
require([
	"dojo/cookie",
	"dojo/dom",
	"dojo/dom-attr",
	"dojo/dom-style",
	"dojo/on",
	"dojo/ready",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/ValidationTextBox"
], function(dojoCookie, dojoDom, dojoDomAttr, dojoDomStyle, dojoOn, dojoReady, dijitRegistry) {
	<?php if ($this->openIdEnabled) : ?>
	dojoReady(function() {
		dojoOn(dojoDom.byId("coreWidgetsLoginOpenId"), "click", function() {
			var type = dojoDomAttr.get(this, "data-app-login");
			dojoCookie("coreWidgetsLoginType", type, {
				expires: 1
			}); 
			
			switch (type) {
				case "openid":
					dojoDomStyle.set("coreWidgetsLoginDefaultContainer", "display", "none");
					dojoDomStyle.set("coreWidgetsLoginOpenIdContainer", "display", "block");
					dijitRegistry.byId("coreWidgetsLoginUsername").set("disabled", true);
					dijitRegistry.byId("coreWidgetsLoginPassword").set("disabled", true);
					dijitRegistry.byId("coreWidgetsLoginOpenIdUrl").set("disabled", false);
					
					dojoDomAttr.set(this, {
						"innerHTML": "<?php echo $this->translator()->_('show.cancelOpenIdLogin'); ?>",
						"data-app-login": "default"
					});
					break;
				case "default":
					dojoDomStyle.set("coreWidgetsLoginDefaultContainer", "display", "block");
					dojoDomStyle.set("coreWidgetsLoginOpenIdContainer", "display", "none");
					dijitRegistry.byId("coreWidgetsLoginUsername").set("disabled", false);
					dijitRegistry.byId("coreWidgetsLoginPassword").set("disabled", false);
					dijitRegistry.byId("coreWidgetsLoginOpenIdUrl").set("disabled", true);
					
					dojoDomAttr.set(this, {
						"innerHTML": "<?php echo $this->translator()->_('show.loginUsingOpenId'); ?>",
						"data-app-login": "openid"
					});
					break;
			}
		});
	});
	<?php endif; ?>
});
</script>
