<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-14
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('config._share.title'));
?>

<script type="text/javascript">
// DOJO LESSON: I have to use Javascript to load the CSS file for the Color Picker widget
// because if I don't, the page will show a horizontal scroll
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/widget/ColorPicker/ColorPicker.css");
});
</script>

<div id="fileConfigConfigContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'app-container-border'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="fileConfigConfigSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit', iconClass: 'app-icon app-icon-save'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("fileConfigConfigForm").validate()) {
					dijitRegistry.byId("fileConfigConfigStandby").show();
					that.set("disabled", true);
	
					var params = dojoDomForm.toObject("fileConfigConfigForm");
					dojoRequestXhr("<?php echo $this->url(array(), 'file_config_config'); ?>", {
						data: params,
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("fileConfigConfigStandby").hide();
						dojoTopic.publish("/app/global/notification", {
							message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->_('config.config.success'); ?>" : "<?php echo $this->translator()->_('config.config.error'); ?>",
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
						
						if ("APP_RESULT_OK" == data.result) {
							dojoTopic.publish("/app/file/config/config/onSetWatermark", params.watermark_using);
						}
					});
				}
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- ConfigForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
		<div id="fileConfigConfigForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0">
				<span><?php echo $this->translator()->_('config.config.title'); ?></span>
			</h2>
			
			<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: true, nested: true, style: 'height: 100%'">
				<!-- Uploader -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config._share.uploader'); ?>', class: 'app-content-pane'">
					<div class="app-form-row">
						<label for="uploadable_files"><?php echo $this->translator()->_('config._share.uploadableFileExtensions'); ?>:</label>
						<textarea id="fileConfigConfigUploadableFilesTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'uploadable_files', style: 'height: 100px; width: 300px'"><?php echo $this->config('file', 'uploadable_files', 'bmp,gif,jpeg,jpg,png,txt,zip'); ?></textarea>
					</div>
				
					<div class="app-form-row">
						<label for="upload_dir_template"><?php echo $this->translator()->_('config._share.uploadDirTemplate'); ?>:</label>
						<input id="fileConfigConfigUploadDirTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'upload_dir_template', value: '<?php if ($this->uploadDirTemplate) : ?><?php echo addslashes($this->uploadDirTemplate); ?><?php endif; ?>', style: 'width: 400px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config._share.uploadDirTemplateRequired'); ?>'" />
					</div>
					
					<div class="app-form-row">
						<label for="image_toolkit"><?php echo $this->translator()->_('config._share.imageToolkit'); ?>:</label>
						<select id="fileConfigConfigImageToolkitSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'image_toolkit', value: '<?php echo $this->imageToolkit; ?>'">
							<option value="gd"<?php if (!extension_loaded('gd')): ?> disabled="disabled"<?php endif; ?>><?php echo $this->translator()->_('config._share.imageToolkitGd'); ?></option>
							<option value="imagick"<?php if (!extension_loaded('imagick')): ?> disabled="disabled"<?php endif; ?>><?php echo $this->translator()->_('config._share.imageToolkitImagick'); ?></option>
						</select>
					</div>
					
					<div class="app-form-row">
						<label>&nbsp;</label>
						<?php echo $this->translator()->_('config._share.thumbnailSizes'); ?>:
					</div>
					
					<?php foreach ($this->thumbnailSizes as $thumb => $value) : ?>
					<div class="app-form-row">
						<label><?php echo $this->translator()->_('config._share.thumbnail' . ucfirst($thumb)); ?>:</label>
						<input id="fileConfigConfigThumbnailTextBox_<?php echo ucfirst($thumb); ?>" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'width[]', value: '<?php echo $value['width']; ?>', style: 'width: 50px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config._share.sizeWidthRequired'); ?>'" /> x <input data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'height[]', value: '<?php echo $value['height']; ?>', style: 'width: 50px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config._share.sizeHeightRequired'); ?>'" />
						<input type="hidden" name="thumb[]" value="<?php echo $thumb; ?>" />
						<input type="hidden" name="method[]" value="<?php echo $value['method']; ?>" />
					</div>
					<?php endforeach; ?>
					
					<!-- Watermark -->
					<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('config._share.watermarkImages'); ?></span></h2>
					
					<div class="app-form-row">
						<label for="watermark_using">&nbsp;</label>
						<select id="fileConfigConfigWatermarkSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'watermark_using', value: '<?php echo $this->watermarkOptions['using']; ?>'">
							<option value="none"><?php echo $this->translator()->_('config._share.watermarkNone'); ?></option>
							<option value="image"><?php echo $this->translator()->_('config._share.watermarkUsingImage'); ?></option>
							<option value="text"><?php echo $this->translator()->_('config._share.watermarkUsingText'); ?></option>
							
							<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
							require([
								"dojo/dom-style",
								"dijit/registry"
							], function(dojoDomStyle, dijitRegistry) {
								dojoDomStyle.set("fileConfigConfigWatermarkTextTextBoxContainer", "display", "text" == value ? "block" : "none");
								dojoDomStyle.set("fileConfigConfigWatermarkImageTextBoxContainer", "display", "image" == value ? "block" : "none");
								dojoDomStyle.set("fileConfigConfigWatermarkPositionContainer", "display", "none" == value ? "none" : "block");
								dijitRegistry.byId("fileConfigConfigWatermarkTextTextBox").set("disabled", value != "text");
								dijitRegistry.byId("fileConfigConfigWatermarkFontTextBox").set("disabled", value != "text");
								dijitRegistry.byId("fileConfigConfigWatermarkImageTextBox").set("disabled", value != "image");
							});
							</script>
						</select>
					</div>
					
					<div id="fileConfigConfigWatermarkTextTextBoxContainer" style="display: <?php if ($this->watermarkOptions['using'] == 'text') : ?>block<?php else : ?>none<?php endif; ?>">
						<div class="app-form-row">
							<label for="watermark_text"><?php echo $this->translator()->_('config._share.watermarkText'); ?>:</label>
							<input id="fileConfigConfigWatermarkTextTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'watermark_text', value: '<?php echo addslashes($this->watermarkOptions['text']); ?>', disabled: <?php if ($this->watermarkOptions['using'] == 'text') : ?>false<?php else : ?>true<?php endif; ?>, style: 'width: 400px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config._share.watermarkTextRequired'); ?>'" /> 
						</div>
						
						<div class="app-form-row">
							<label for="watermark_color"><?php echo $this->translator()->_('config._share.watermarkColor'); ?>:</label>
							<input id="fileConfigConfigWatermarkColorTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'watermark_color', value: '<?php echo $this->watermarkOptions['color']; ?>', style: 'width: 100px'" />
							<div data-dojo-type="dijit/form/DropDownButton">
								<span><?php echo $this->translator()->_('config._share.watermarkColor'); ?></span>
								<div data-dojo-type="dojox/widget/ColorPicker" data-dojo-props="value: '<?php echo $this->watermarkOptions['color']; ?>'">
									<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
									require(["dijit/registry"], function(dijitRegistry) {
										dijitRegistry.byId("fileConfigConfigWatermarkColorTextBox").set("value", value);
									});
									</script>
								</div>
							</div>
							<div class="app-clear"></div>
						</div>
						
						<div class="app-form-row">
							<label for="watermark_font"><?php echo $this->translator()->_('config._share.watermarkFont'); ?>:</label>
							<input id="fileConfigConfigWatermarkFontTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'watermark_font', value: '<?php echo addslashes($this->watermarkOptions['font']); ?>', disabled: <?php if ($this->watermarkOptions['using'] == 'text') : ?>false<?php else : ?>true<?php endif; ?>, style: 'width: 400px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config._share.watermarkFontRequired'); ?>'" />
						</div>
						
						<div class="app-form-row">
							<label for="watermark_font_size"><?php echo $this->translator()->_('config._share.watermarkFontSize'); ?>:</label>
							<input id="fileConfigConfigWatermarkFontSizeTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'watermark_font_size', value: '<?php echo $this->watermarkOptions['font_size']; ?>', style: 'width: 50px'" /> px
						</div>
						
						<div class="app-form-row">
							<label for="watermark_font_measured">&nbsp;</label>
							<input id="fileConfigConfigWatermarkFontMeasuredCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'watermark_font_measured', value: 1, checked: <?php if ($this->watermarkOptions['font_measured']) : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('config._share.watermarkFontSizeMeasuredAuto'); ?>
						</div>
						
						<div class="app-form-row">
							<label for="watermark_rotation_angle"><?php echo $this->translator()->_('config._share.watermarkRotationAngle'); ?>:</label>
							<input id="fileConfigConfigWatermarkAngleSpinner" data-dojo-type="dijit/form/NumberSpinner" data-dojo-props="name: 'watermark_rotation_angle', constraints: {min: 0, max: 360}, smallDelta: 1, value: '<?php echo $this->watermarkOptions['rotation_angle']; ?>', style: 'width: 50px'" />
						</div>
						
						<div class="app-form-row">
							<label for="watermark_opacity"><?php echo $this->translator()->_('config._share.watermarkOpacity'); ?>:</label>
							<input id="fileConfigConfigWatermarkOpacitySpinner" data-dojo-type="dijit/form/NumberSpinner" data-dojo-props="name: 'watermark_opacity', constraints: {min: 0, max: 100}, smallDelta: 1, value: '<?php echo $this->watermarkOptions['opacity']; ?>', style: 'width: 50px'" />
						</div>
					</div>
					
					<div id="fileConfigConfigWatermarkImageTextBoxContainer" style="display: <?php if ($this->watermarkOptions['using'] == 'image') : ?>block<?php else : ?>none<?php endif; ?>">
						<div class="app-form-row">
							<label for="watermark_image"><?php echo $this->translator()->_('config._share.watermarkImage'); ?>:</label>
							<input id="fileConfigConfigWatermarkImageTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="name: 'watermark_image', value: '<?php echo addslashes($this->watermarkOptions['image']); ?>', disabled: <?php if ($this->watermarkOptions['using'] == 'image') : ?>false<?php else : ?>true<?php endif; ?>, style: 'width: 400px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config._share.watermarkImageRequired'); ?>'" /> 
						</div>
					</div>
					
					<div id="fileConfigConfigWatermarkPositionContainer" style="display: <?php if ($this->watermarkOptions['using'] == 'none') : ?>none<?php else : ?>block<?php endif; ?>">
						<div class="app-form-row">
							<label for="watermark_horizontal_pos"><?php echo $this->translator()->_('config._share.watermarkPositionHorizontal'); ?>:</label>
							<select id="fileConfigConfigWatermarkHorPosSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'watermark_horizontal_pos', value: '<?php echo $this->watermarkOptions['horizontal_pos']; ?>'">
								<option value="left"><?php echo $this->translator()->_('config._share.watermarkPositionLeft'); ?></option>
								<option value="center"><?php echo $this->translator()->_('config._share.watermarkPositionCenter'); ?></option>
								<option value="right"><?php echo $this->translator()->_('config._share.watermarkPositionRight'); ?></option>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="watermark_vertical_pos"><?php echo $this->translator()->_('config._share.watermarkPositionVertical'); ?>:</label>
							<select id="fileConfigConfigWatermarkVerPosSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'watermark_vertical_pos', value: '<?php echo $this->watermarkOptions['vertical_pos']; ?>'">
								<option value="top"><?php echo $this->translator()->_('config._share.watermarkPositionTop'); ?></option>
								<option value="middle"><?php echo $this->translator()->_('config._share.watermarkPositionMiddle'); ?></option>
								<option value="bottom"><?php echo $this->translator()->_('config._share.watermarkPositionBottom'); ?></option>
							</select>
						</div>
						
						<div class="app-form-row">
							<label>&nbsp;</label>
							<?php echo $this->translator()->_('config._share.watermarkThumbnails'); ?>:
						</div>
						
						<?php foreach ($this->thumbnailSizes as $thumb => $value) : ?>
						<div class="app-form-row">
							<label>&nbsp;</label>
							<input id="fileConfigConfigWatermarkThumbnailCheckBox_<?php echo $thumb; ?>" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'watermark_thumbnails[]', value: '<?php echo $thumb; ?>', checked: <?php if ($this->watermarkOptions['thumbnails'] && in_array($thumb, explode(',', $this->watermarkOptions['thumbnails']))) : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('config._share.thumbnail' . ucfirst($thumb)); ?>
						</div>
						<?php endforeach; ?>
					</div>
					<!-- /Watermark -->
				</div>
				<!-- /Uploader -->
				
				<!-- FileExplorer -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config._share.explorer'); ?>', class: 'app-content-pane'">
					<div class="app-form-row">
						<label for="viewable_files"><?php echo $this->translator()->_('config._share.viewableFileExtensions'); ?>:</label>
						<textarea id="fileConfigConfigViewableFilesTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'viewable_files', style: 'height: 100px; width: 300px'"><?php echo $this->config('file', 'viewable_files', 'bmp,gif,jpeg,jpg,png,css,js,html,php,phtml,sql,txt,xml'); ?></textarea>
					</div>
					
					<div class="app-form-row">
						<label for="editable_files"><?php echo $this->translator()->_('config._share.editableFileExtensions'); ?>:</label>
						<textarea id="fileConfigConfigEditableFilesTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'editable_files', style: 'height: 100px; width: 300px'"><?php echo $this->config('file', 'editable_files', 'css,js,html,php,phtml,sql,txt,xml'); ?></textarea>
					</div>
				</div>
				<!-- /FileExplorer -->
			</div>
			
			<input type="hidden" name="format" value="json" />
		</div>
	</div>
	<!-- /ConfigForm -->
</div>

<div id="fileConfigConfigStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'fileConfigConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/file/languages')->_('config.config.title'); ?>";

require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/DropDownButton",
	"dijit/form/Form",
	"dijit/form/NumberSpinner",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojox/widget/ColorPicker",
	"dojox/widget/Standby"
]);
</script>
