<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('config.config.title'));
?>

<div id="mediaConfigConfigContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'app-container-border'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="mediaConfigConfigSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("mediaConfigConfigForm").validate()) {
					dijitRegistry.byId("mediaConfigConfigStandby").show();
					that.set("disabled", true);
					dojoRequestXhr("<?php echo $this->url(array(), 'media_config_config'); ?>", {
						data: dojoDomForm.toObject("mediaConfigConfigForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("mediaConfigConfigStandby").hide();
						dojoTopic.publish("/app/global/notification", {
							message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->_('config.config.success'); ?>" : "<?php echo $this->translator()->_('config.config.error'); ?>",
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					});
				}
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- ConfigForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
		<div id="mediaConfigConfigForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('config.config.title'); ?></span></h2>
			
			<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: true, nested: true, style: 'height: 100%'">
				<!-- FlickrImporter -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.config.flickr'); ?>', class: 'app-content-pane'">
					<div class="app-form-row">
						<label for="flickr_api_key"><?php echo $this->translator()->_('config.config.apiKey'); ?>:</label>
						<input id="mediaConfigConfigFlickrApiTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'flickr_api_key', value: '<?php echo $this->config('media', 'flickr_api_key'); ?>', style: 'width: 300px'" />
					</div>
					
					<div class="app-form-row">
						<label for="flickr_secret_key"><?php echo $this->translator()->_('config.config.secretKey'); ?>:</label>
						<input id="mediaConfigConfigFlickrSecretTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'flickr_secret_key', value: '<?php echo $this->config('media', 'flickr_secret_key'); ?>', style: 'width: 300px'" />
					</div>
				</div>
				<!-- /FlickrImporter -->
			</div>
			
			<input type="hidden" name="format" value="json" />
		</div>
	</div>
	<!-- /ConfigForm -->
</div>

<div id="mediaConfigConfigStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'mediaConfigConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/media/languages')->_('config.config.title'); ?>";

require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojox/widget/Standby"
]);
</script>
