<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	views
 * @since		1.0
 * @version		2012-10-02
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('article.add.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/layout/resources/GridContainer.css");
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/widget/Portlet/Portlet.css");	
});
</script>

<div id="contentArticleAddContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="contentArticleAddSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>
		
		<button id="contentArticleAddCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/topic",
				"core/js/base/controllers/Subscriber"
			], function(dojoTopic) {
				core.js.base.controllers.Subscriber.unsubscribe("/app/content/article/add", "/app/global/dnd/onDropImage");
				dojoTopic.publish("/app/content/article/add/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- Form -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('article.add.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<div id="contentArticleAddForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="language"><?php echo $this->translator()->_('article._share.language'); ?>:</label>
							<select id="contentArticleAddLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language'">
								<?php foreach ($this->languages as $language => $name) : ?>
								<option value="<?php echo $language; ?>"<?php if ($language == $this->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="type"><?php echo $this->translator()->_('article._share.type'); ?>:</label>
							<select id="contentArticleAddTypeSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'type', value: '<?php if ($this->source) : ?><?php echo $this->source->type; ?><?php else : ?>article<?php endif; ?>'">
								<option value="<?php echo Content_Models_Article::TYPE_ARTICLE; ?>"><?php echo $this->translator()->_('article._share.typeArticle'); ?></option>
								<option value="<?php echo Content_Models_Article::TYPE_PAGE; ?>"><?php echo $this->translator()->_('article._share.typePage'); ?></option>
								<option value="<?php echo Content_Models_Article::TYPE_BLOG; ?>"><?php echo $this->translator()->_('article._share.typeBlog'); ?></option>
							</select>
						</div>
					
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('article._share.title'); ?>:</label>
							<div id="contentArticleAddTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'title', value: '<?php if ($this->source) : ?><?php echo addslashes($this->source->title); ?><?php endif; ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('article._share.titleRequired'); ?>'">
								<script type="dojo/on">
								new core.js.views.CharacterCounter(this);
								</script>
								<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
								require([
									"dojo/request/xhr",
									"dijit/registry"						
								], function(dojoRequestXhr, dijitRegistry) {
									dojoRequestXhr("<?php echo $this->url(array(), 'core_helper_slug'); ?>", {
										data: {
											input: value
										},
										handleAs: "json",
										method: "POST"
									}).then(function(data) {
										dijitRegistry.byId("contentArticleAddSlugTextBox").set("value", data.output);
									});
								});
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="sub_title"><?php echo $this->translator()->_('article._share.subTitle'); ?>:</label>
							<input id="contentArticleAddSubTitleTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'sub_title', value: '<?php if ($this->source && $this->source->sub_title) : ?><?php echo addslashes($this->source->sub_title); ?><?php endif; ?>', style: 'width: 300px'" />
						</div>
						
						<div class="app-form-row">
							<label for="slug"><?php echo $this->translator()->_('article._share.slug'); ?>:</label>
							<div id="contentArticleAddSlugTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', value: '<?php if ($this->source) : ?><?php echo addslashes($this->source->slug); ?><?php endif; ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('article._share.slugRequired'); ?>'">
								<script type="dojo/on" data-dojo-event=change" data-dojo-args="value">
								require([
									"dojo/request/xhr",
									"dojo/topic"						
								], function(dojoRequestXhr, dojoTopic) {
									dojoRequestXhr("<?php echo $this->url(array(), 'content_article_slug'); ?>", {
										data: {
											slug: value
										},
										handleAs: "json",
										method: "POST"
									}).then(function(data) {
										if (data.available == false) {
											dojoTopic.publish("/app/global/notification", {
												message: "<?php echo $this->translator()->_('article._share.slugNotAvailable'); ?>",
												type: "error"
											});
										}
									});
								});
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="description"><?php echo $this->translator()->_('article._share.description'); ?>:</label>
							<div id="contentArticleAddDescTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'description', style: 'width: 250px; height: 100px'"><?php if ($this->source) : ?><?php echo $this->source->description; ?><?php endif; ?><script type="dojo/on">new core.js.views.CharacterCounter(this);</script></div>
						</div>
						
						<div class="app-form-row">
							<label for="meta_keyword"><?php echo $this->translator()->_('article._share.metaKeywordTag'); ?>:</label>
							<textarea id="contentArticleAddMetaKeywordTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'meta_keyword', style: 'width: 250px; height: 100px'"><?php if ($this->source) : ?><?php echo $this->source->meta_keyword; ?><?php endif; ?></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="meta_description"><?php echo $this->translator()->_('article._share.metaDescriptionTag'); ?>:</label>
							<textarea id="contentArticleAddMetaDescTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'meta_description', style: 'width: 250px; height: 100px'"><?php if ($this->source) : ?><?php echo $this->source->meta_description; ?><?php endif; ?></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="author"><?php echo $this->translator()->_('article._share.author'); ?>:</label>
							<input id="contentArticleAddAuthorTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'author', value: '<?php if ($this->source) : ?><?php echo addslashes($this->source->author); ?><?php endif; ?>', style: 'width: 200px'" />
						</div>
						
						<div class="app-form-row">
							<label for="credit"><?php echo $this->translator()->_('article._share.credit'); ?>:</label>
							<input id="contentArticleAddCreditTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'credit', value: '<?php if ($this->source) : ?><?php echo addslashes($this->source->credit); ?><?php endif; ?>', style: 'width: 200px'" />
						</div>
						
						<div class="app-form-row">
							<label><?php echo $this->translator()->_('article._share.icon'); ?>:</label>
							<input id="contentArticleAddImageIconCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'image_icon', value: 1, checked: <?php if ($this->source && $this->source->image_icon == '1') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('article._share.iconImage'); ?>
							<input id="contentArticleAddVideoIconCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'video_icon', value: 1, checked: <?php if ($this->source && $this->source->video_icon == '1') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('article._share.iconVideo'); ?>
						</div>
						
						<div class="app-form-row">
							<label for="publishing_date"><?php echo $this->translator()->_('article._share.publishingDate'); ?>:</label>
							<input id="contentArticleAddPublishingDateTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'publishing_date'" />
							<input id="contentArticleAddPublishingTimeTextBox" data-dojo-type="dijit/form/TimeTextBox" data-dojo-props="type: 'text', name: 'publishing_time', value: 'T00:00:00', constraints: { timePattern: 'HH:mm:ss' }" />
						</div>
						
						<div class="app-form-row">
							<label for="featured">&nbsp;</label>
							<input id="contentArticleAddFeaturedCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'featured', value: 1, checked: <?php if ($this->source && $this->source->featured == '1') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('article._share.markAsFeatured'); ?>
						</div>
						
						<div class="app-form-row">
							<label for="category"><?php echo $this->translator()->_('article._share.category'); ?>:</label>
							<?php 
							echo $this->helperLoader('category')
									  ->categorySelect('content', $this->language, array(
											'name'	   => 'category',
									  		'selected' => $this->source ? $this->source->category_id : null,
									  ));
							?>
						</div>
						
						<div class="app-form-row">
							<label for="categories"><?php echo $this->translator()->_('article._share.categories'); ?>:</label>
							<div id="contentArticleAddCategories" class="app-left">
								<?php 
								echo $this->helperLoader('category')
										  ->categoryCheckboxTree('content', $this->language, array(
												'id'	   => 'contentArticleAddCategories',
												'name'	   => 'categories[]',
												'selected' => $this->source ? $this->source->categories : null,
										  ));
								?>
							</div>
						</div>
						
						<input type="hidden" name="format" value="json" />
					</div>
					<!-- /Properties -->
					
					<!-- Cover -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.cover'); ?>', class: 'app-content-pane'">
						<div style="padding-bottom: 8px"><?php echo $this->translator()->_('article._share.coverHelp'); ?></div>
						
						<div id="contentArticleAddCoverTarget" class="app-container-border" style="height: 225px; width: 300px; margin-bottom: 8px" data-dojo-type="dojo/dnd/Target" data-dojo-props="accept: ['appDndImage']">
							<script type="dojo/on">
							var that = this;
							require([
								"dojo/dom-attr",
								"dijit/registry",
								"core/js/base/dnd/TargetManager"
							], function(dojoDomAttr, dijitRegistry) {
								// Automatically set the cover's title after dropping image to the cover area
								core.js.base.dnd.TargetManager.getInstance().addTarget(that);
								core.js.base.dnd.TargetManager.getInstance().add(that.node, ["appDndImage"], core.js.base.dnd.TargetManager.handleDropImage);
								core.js.base.controllers.Subscriber.subscribe("/app/content/article/add", "/app/global/dnd/onDropImage", that, function(data) {
									if (dojoDomAttr.get(data.target, "id") == dojoDomAttr.get(that.node, "id")) {
										dijitRegistry.byId("contentArticleAddCoverTitleBox").set("value", data.title);
									}
								});
							});
							</script>
							<script type="dojo/method" data-dojo-event="onDropExternal" data-dojo-args="source, nodes, copy">
							var that = this;
							require([
								"dojo/dom-attr",
								"dojo/dom-construct",
								"dojo/json",
								"dojo/NodeList-dom",
								"dojo/query",
								"core/js/base/dnd/TargetManager",
								"core/js/Constant"
							], function(dojoDomAttr, dojoDomConstruct, dojoJson) {
								var thumbs = core.js.base.dnd.TargetManager.getThumbnails(nodes[0]);
								if (thumbs == false) {
									return;
								}
								dojoDomAttr.set("contentArticleAddCover", "value", dojoJson.stringify(thumbs));
								dojo.query("img", that.node).orphan();
								dojoDomConstruct.create("img", {
									src: core.js.Constant.ROOT_URL + thumbs.crop
								}, that.node);
							});
							</script>
							
							<?php if ($this->source && $this->source->image_crop) : ?>
							<img src="<?php echo $this->APP_ROOT_URL . $this->source->image_crop; ?>" />
							<?php endif; ?>
						</div>
						<input type="hidden" id="contentArticleAddCover" name="thumbnails" value=<?php if ($this->source) : ?><?php echo (Zend_Json::encode($this->source->getCoverThumbnails())); ?><?php else : ?>""<?php endif; ?> />
						
						<input id="contentArticleAddCoverTitleBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'cover_title', style: 'width: 300px', placeHolder: '<?php echo $this->translator(true)->_('article._share.coverTitleHelp'); ?>'" />
					</div>
					<!-- /Cover -->
				
					<!-- Content -->
					<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="selected: true, gutters: true, style: 'height: 100%; width: 100%', title: '<?php echo $this->translator(true)->_('article._share.content'); ?>'">
						<div id="contentArticleAddContentEditor" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', style: 'height: 100%; width: 100%', class: 'app-container-border'">
						</div>
						
						<input type="hidden" id="contentArticleAddContent" name="content" value="<?php if ($this->source) : ?><?php echo addslashes($this->source->content); ?><?php endif; ?>" />
						<input type="hidden" id="contentArticleAddLayout" name="layout" value="<?php if ($this->source && $this->source->layout) : ?><?php echo htmlentities($this->source->layout); ?><?php endif; ?>" />
					</div>
					<!-- /Content -->
					
					<!-- Tags -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.tags'); ?>', class: 'app-content-pane'">
						<div style="padding-bottom: 8px"><?php echo $this->translator()->_('article._share.tagsHelp'); ?></div>
						
						<?php echo $this->helperLoader('tag')->tagCollector('contentArticleAddTagsContainer'); ?>
					</div>
					<!-- /Tags -->
					
					<!-- Localization -->
					<div id="contentArticleAddLocalizedContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.localization'); ?>', class: 'app-container-border', style: 'margin-top: 8px'">
						<?php if ($this->source) : ?>
						<div class="contentArticleAddLocalizedItem" style="padding: 2px 8px">
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($this->source->title); ?>', style: 'width: 200px', readOnly: true" />
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($this->source->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
							<input type="hidden" name="translations" value='<?php echo $this->source->translations; ?>' />
							
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
								<script type="dojo/on" data-dojo-event="click">
								var that = this;
								require([
									"dojo/dom-construct",
									"dojo/dom-style",
									"dojo/NodeList-traverse",
									"dojo/query"
								], function(dojoDomConstruct, dojoDomStyle) {
									dojoDomConstruct.destroy(dojo.query(that.domNode).closest(".contentArticleAddLocalizedItem")[0]);
									if (dojo.query(".contentArticleAddLocalizedItem", "contentArticleAddLocalizedContainer").length == 0) {
										// Show the guide
										dojoDomStyle.set("contentArticleAddLocalizedHelp", "display", "block");
									}
								});
								</script>
							</button>
						</div>
						<?php endif; ?>
					
						<div id="contentArticleAddLocalizedHelp" class="app-center" style="display: <?php if ($this->source) : ?>none<?php else : ?>block<?php endif; ?>">
							<div><?php echo $this->translator()->_('article._share.localizationHelp'); ?></div>
						</div>
					</div>
					<!-- /Localization -->
				</div>
			</div>
		</div>
	</div>
	<!-- /Form -->
</div>

<script type="text/javascript">
require([
	"dojo/_base/lang",
	"dojo/aspect",
	"dojo/dom-attr",
	"dojo/dom-construct",
	"dojo/dom-form",
	"dojo/dom-style",
	"dojo/on",
	"dojo/json",
	"dojo/ready",
	"dojo/request/xhr",
	"dojo/topic",
	"dijit/registry",
	"dojo/dnd/Target",
	"dojo/NodeList-traverse",
	"dojo/parser",
	"dojo/query",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/DateTextBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/TimeTextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"core/js/base/controllers/ActionProvider",
	"core/js/base/Encoder",
	"core/js/Constant",
	"core/js/controllers/LayoutController",
	"core/js/views/CharacterCounter",
	"core/js/views/LayoutToolbar"
], function(dojoLang, dojoAspect, dojoDomAttr, dojoDomConstruct, dojoDomForm, dojoDomStyle, dojoOn, dojoJson, dojoReady, dojoRequestXhr, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		// Provide the actions
		<?php foreach (array(
						'core_extension_render',	// Required by the content editor
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
		});	
		<?php endforeach; ?>

		// Allow to drag the article from the list view and drop to the localized container
		new dojo.dnd.Target("contentArticleAddLocalizedContainer", {
			accept: ["contentArticleItemDnd"],
			onDropExternal: function(source, nodes, copy) {
				// Hide the guide
				dojoDomStyle.set("contentArticleAddLocalizedHelp", "display", "none");
				
				var article = core.js.base.Encoder.decode(dojoDomAttr.get(nodes[0], "data-app-entity-props"));

				var div = dojoDomConstruct.create("div", {
					className: "contentArticleAddLocalizedItem",
					style: "padding: 2px 8px"
				}, "contentArticleAddLocalizedContainer");
				
				new dijit.form.TextBox({
					value: article.title,
					style: "width: 200px",
					readOnly: true
				}).placeAt(div);
				
				new dijit.form.TextBox({
					value: article.language,
					style: "margin: 0 8px; width: 100px",
					readOnly: true
				}).placeAt(div);

				dojoDomConstruct.create("input", {
					name: "translations",
					type: "hidden",
					value: article.translations
				}, div);

				new dijit.form.Button({
					label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
					onClick: function() {
						dojoDomConstruct.destroy(div);
						if (dojo.query(".contentArticleAddLocalizedItem", "contentArticleAddLocalizedContainer").length == 0) {
							// Show the guide
							dojoDomStyle.set("contentArticleAddLocalizedHelp", "display", "block");
						}
					}
				}).placeAt(div);
			}
		});

		var editorController = new core.js.controllers.LayoutController("contentArticleAddContentEditor");
		// editorController.setLayoutToolbar(null);

		<?php if ($this->source) : ?>
		editorController.setLayoutData(<?php echo $this->source->layout; ?>);
		<?php else : ?>
		// Get the title of Editor widget
		var title = "<?php echo $this->extensionTranslator()->translateTitle(new Core_Models_Widget(array('module' => 'content', 'name' => 'editor'))); ?>";
		// Set the default layout with the Editor widget inside a grid container
		var defaultLayout = {
			"containers": [{
			   	"containers": [{
					"containers": [],
					"cls": "core.js.views.LayoutPortlet",
					"zoneIndex": 0,
					"widget": {
						"title": title,
						"module": "content",
						"name": "editor",
						"params": {}
					}
				}],
				"cls": "dojox.layout.GridContainer",
				"numZones": 1
			}],
			"cls": "dijit/layout/BorderContainer",
			"region": "center",
			"style": "height: 100%; width: 100%"
		};
		editorController.setLayoutData(defaultLayout);
		<?php endif; ?>

		// Switch the layout editor to the edit mode
		editorController.getLayoutContainer().setShowPortletOutput(false);
		editorController.switchToMode("edit");

		// Tag suggestions
		tag.views.helpers.TagCollector.getContent = function() {
			return editorController.getHtmlData();
		};
		
		dojoAspect.after(editorController, "onSaveLayout", function(layoutData) {
			dojoDomAttr.set("contentArticleAddContent", "value", editorController.getHtmlData());
			dojoDomAttr.set("contentArticleAddLayout", "value", dojoJson.stringify(layoutData));
		}, true);
	
		dojoOn(dijitRegistry.byId("contentArticleAddSaveButton"), "click", function() {
			dijitRegistry.byId("contentArticleAddSaveButton").set("disabled", true);
			dojoDomAttr.set("contentArticleAddContent", "value", editorController.getHtmlData());
			dojoDomAttr.set("contentArticleAddLayout", "value", dojoJson.stringify(editorController.getLayoutData()));
	
			// Because dojo.formToObject("contentArticleAddForm") does not include the selected categories,
			// I have to determine it manually
			var categories = [];
			dojo.query("input[name='categories[]'][checked='checked']", "contentArticleAddForm").forEach(function(node) {
				categories.push(dojoDomAttr.get(node, "value"));
			});
			editorController.addPrefixToFields("app-widget-input-");
			dojoTopic.publish("/app/content/article/add/onStart");

			dojoRequestXhr("<?php echo $this->url(array(), 'content_article_add'); ?>", {
				data: dojoLang.mixin(dojoDomForm.toObject("contentArticleAddForm"), { "categories[]": categories }),
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				dijitRegistry.byId("contentArticleAddSaveButton").set("disabled", false);
				dojoTopic.publish("/app/content/article/add/onComplete", data);
			});
		});
	});
});
</script>
