<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-10-01
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="app-form">
	<div class="app-form-row" style="width: 100%">
		<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%; width: 100%', closable: true, doLayout: false">
			<!-- Basic -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="selected: true, title: '<?php echo $this->translator(true)->_('config.basic'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row-vertical">
					<label for="type"><?php echo $this->translator()->_('config.searchFor'); ?>:</label>
					<select data-dojo-type="dijit/form/Select" data-dojo-props="name: 'type', class: 'appWidgetInput'">
						<option value="<?php echo Content_Models_Article::TYPE_ARTICLE; ?>"><?php echo $this->translator()->_('config.searchForArticle'); ?></option>
						<option value="<?php echo Content_Models_Article::TYPE_PAGE; ?>"><?php echo $this->translator()->_('config.searchForPage'); ?></option>
						<option value="<?php echo Content_Models_Article::TYPE_BLOG; ?>"><?php echo $this->translator()->_('config.searchForBlog'); ?></option>
					</select>
				</div>
			</div>
			<!-- /Basic -->
			
			<!-- Theme -->
			<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.theme'); ?>', style: 'padding-top: 8px'">
				<div class="app-form-row">
					<input data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'theme', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Theme -->
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Select",
	"dijit/form/TextBox",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer"
]);
</script>
