<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		message
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('config.config.title'));
?>

<div id="messageConfigConfigContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'app-container-border'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="messageConfigConfigSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("messageConfigConfigForm").validate()) {
					dijitRegistry.byId("messageConfigConfigStandby").show();
					that.set("disabled", true);

					dojoRequestXhr("<?php echo $this->url(array(), 'message_config_config'); ?>", {
						data: dojoDomForm.toObject("messageConfigConfigForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("messageConfigConfigStandby").hide();
						dojoTopic.publish("/app/global/notification", {
							message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->_('config.config.success'); ?>" : "<?php echo $this->translator()->_('config.config.error'); ?>",
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					}, function(err) {
					}, function(evt) {
					});
				}
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- ConfigForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
		<div id="messageConfigConfigForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('config.config.title'); ?></span></h2>
			
			<!-- PrivateMessage -->
			<div class="app-form-row">
				<label for="attachments_dir"><?php echo $this->translator()->_('config.config.messageAttachmentDirectory'); ?>:</label>
				<input id="messageConfigConfigAttachmentDirTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'attachments_dir', value: '<?php echo addslashes($this->config('message', 'attachments_dir', Message_Services_Installer::DEFAULT_ATTACHMENTS_DIR)); ?>', style: 'width: 400px', required: true, missingMessage: '<?php echo $this->translator(true)->_('config.config.messageAttachmentDirectoryRequired'); ?>'" />		
			</div>
			
			<div class="app-form-row">
				<label><?php echo $this->translator()->_('config.config.messageAttachmentExtensions'); ?>:</label>
				<?php echo $this->translator()->_('config.config.messageAttachmentExtensionsHelp'); ?>
			</div>
			
			<div class="app-form-row">
				<label for="attachments_exts">&nbsp;</label>
				<textarea id="messageConfigConfigAttachmentExtsTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'attachments_exts', style: 'width: 400px; height: 150px'"><?php echo $this->config('message', 'attachments_exts', ''); ?></textarea>
			</div>
			<!-- /PrivateMessage -->
			
			<!-- PrivateMessageMailTemplate -->
			<div class="app-form-row" style="padding: 4px 0">
				<label for="email_enabled">&nbsp;</label>
				<div id="messageConfigConfigEmailCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'email_enabled', checked: <?php if ($this->config('message', 'email_enabled', 'false') == 'true') : ?>true<?php else : ?>false<?php endif; ?>">
					<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
					require(["dojo/dom-style"], function(dojoDomStyle) {
						dojoDomStyle.set("messageConfigConfigMessageMailTemplate", "display", value == true ? "block" : "none");
					});
					</script>
				</div>
				<?php echo $this->translator()->_('config.config.messageSentInformingEmail'); ?>
			</div>
			
			<div id="messageConfigConfigMessageMailTemplate" style="display: <?php if ($this->config('message', 'email_enabled') == 'true') : ?>block<?php else : ?>none<?php endif; ?>">
				<div class="app-form-row">
					<label for="sent_from_name"><?php echo $this->translator()->_('config.config.sendFromName'); ?>:</label>
					<input id="messageConfigConfigSentNameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'sent_from_name', style: 'width: 200px', value: '<?php echo addslashes($this->messageSentMailTemplate['from_name']); ?>'">
				</div>
				
				<div class="app-form-row">
					<label for="sent_from_email"><?php echo $this->translator()->_('config.config.sendFromEmail'); ?>:</label>
					<input id="messageConfigConfigSentEmailTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'sent_from_email', style: 'width: 200px', value: '<?php echo addslashes($this->messageSentMailTemplate['from_email']); ?>'">
				</div>
				
				<div class="app-form-row">
					<label><?php echo $this->translator()->_('config.config.subject'); ?>:</label>
					<?php echo $this->translator()->_('config.config.messageSentSubjectHelp'); ?>
				</div>
				
				<div class="app-form-row">
					<label for="sent_subject">&nbsp;</label>
					<input id="messageConfigConfigSentSubjectTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'sent_subject', value: '<?php echo $this->messageSentMailTemplate['subject']; ?>', style: 'width: 400px'" />
				</div>
				
				<div class="app-form-row">
					<label><?php echo $this->translator()->_('config.config.content'); ?>:</label>
					<?php echo $this->translator()->_('config.config.messageSentContentHelp'); ?>
				</div>
				
				<div class="app-form-row">
					<label for="sent_content">&nbsp;</label>
					<textarea id="messageConfigConfigSentContentTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'sent_content', style: 'width: 400px; height: 150px'"><?php echo $this->messageSentMailTemplate['content']; ?></textarea>
				</div>
				
				<div style="clear: both; padding: 4px 0"></div>
			</div>
			<!-- /PrivateMessageMailTemplate -->
			
			<input type="hidden" name="format" value="json" />
		</div>
	</div>
	<!-- /ConfigForm -->
</div>

<div id="messageConfigConfigStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'messageConfigConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/message/languages')->_('config.config.title'); ?>";

require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/widget/Standby"
]);
</script>
