<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		tag
 * @subpackage	views
 * @since		1.0
 * @version		2012-08-24
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('tag.edit.title'));
?>

<div id="tagTagEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
	<?php if (!$this->tag) : ?>
	<div>
		<?php echo sprintf($this->translator()->_('tag.edit.notFound'), $this->tagId); ?>
	</div>
	<?php else : ?>
	<script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
	e.preventDefault();
	var that = this;
	require([
		"dojo/dom-form",
		"dojo/request/xhr",
		"dojo/topic",
		"dijit/registry"
	], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
		dojoRequestXhr("<?php echo $this->url(array(), 'tag_tag_edit'); ?>", {
			data: dojoDomForm.toObject("tagTagEditForm"),
			handleAs: "json",
			method: "POST"
		}).then(function(data) {
			dijitRegistry.byId("tagTagEditSaveButton").set("disabled", true);
			dojoTopic.publish("/app/tag/tag/edit/onComplete", data);
		});
	});
	</script>
	
	<div class="app-form-row-vertical">
		<label for="slug"><?php echo $this->translator()->_('tag._share.language'); ?>:</label>
		<select id="tagTagEditLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language', value: '<?php echo $this->tag->language; ?>'">
			<?php foreach ($this->languages as $language => $name) : ?>
			<option value="<?php echo $language; ?>"><?php echo $name; ?></option>
			<?php endforeach; ?>
		</select>
	</div>
	
	<div class="app-form-row-vertical">
		<label for="title"><?php echo $this->translator()->_('tag._share.title'); ?>:</label>
		<div id="tagTagEditTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'title', value: '<?php echo addslashes($this->tag->title); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('tag._share.titleRequired'); ?>'">
			<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
			require([
				"dojo/request/xhr",
				"dijit/registry"
			], function(dojoRequestXhr, dijitRegistry) {
				dojoRequestXhr("<?php echo $this->url(array(), 'core_helper_slug'); ?>", {
					data: {
						locale: dijitRegistry.byId("tagTagEditLanguageSelect").get("value"),
						input: value
					},
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					dijitRegistry.byId("tagTagEditSlugTextBox").set("value", data.output);
				});
			});
			</script>
		</div>
	</div>
	
	<div class="app-form-row-vertical">
		<label for="slug"><?php echo $this->translator()->_('tag._share.slug'); ?>:</label>
		<div id="tagTagEditSlugTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', value: '<?php echo addslashes($this->tag->slug); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('tag._share.slugRequired'); ?>'">
			<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
			if (value == "") {
				return;
			}
			require([
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoRequestXhr, dojoTopic, dijitRegistry) {
				dojoRequestXhr("<?php echo $this->url(array(), 'tag_tag_validate'); ?>", {
					data: {
						language: dijitRegistry.byId("tagTagEditLanguageSelect").get("value"),
						slug: value
					},
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					if (data.result == true || data.result == "<?php echo $this->tag->tag_id; ?>") {
						dijitRegistry.byId("tagTagEditSaveButton").set("disabled", false);
					} else {
						dijitRegistry.byId("tagTagEditSaveButton").set("disabled", true);
						dojoTopic.publish("/app/global/notification", {
							message: "<?php echo $this->translator()->_('tag._share.slugValidator'); ?>",
							type: "error"
						});
					}
				});
			});
			</script>
		</div>
	</div>
	<?php endif; ?>

	<div class="dijitDialogPaneActionBar">
		<button id="tagTagEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit', disabled: true">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>

		<button id="tagTagEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/tag/tag/edit/onCancel");
			});
			</script>
		</button>
	</div>
	
	<input type="hidden" name="format" value="json" />
	<input type="hidden" name="tag_id" value="<?php echo $this->tagId; ?>" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/ValidationTextBox"
]);
</script>
