<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-11
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('connection.add.title'));
?>

<div id="fileConnectionAddContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="fileConnectionAddSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-save'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("fileConnectionAddForm").validate()) {
					dijitRegistry.byId("fileConnectionAddStandby").show();
					dojoRequestXhr("<?php echo $this->url(array(), 'file_connection_add'); ?>", {
						data: dojoDomForm.toObject("fileConnectionAddForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						dijitRegistry.byId("fileConnectionAddStandby").hide();
						if ("APP_RESULT_OK" == data.result) {
							dojoTopic.publish("/app/file/connection/add/onSuccess");
						}
					});
				}
			});	
			</script>
		</button>
		
		<button id="fileConnectionAddCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-cancel'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/file/connection/add/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- AddConnectionForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', design: 'sidebar', gutters: false, class: 'app-content-pane'">
		<div id="fileConnectionAddForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0">
				<span><?php echo $this->translator()->_('connection.add.title'); ?></span>
			</h2>
			
			<div class="app-form-row">
				<label for="name"><?php echo $this->translator()->_('connection._share.name'); ?>:</label>
				<input id="fileConnectionAddNameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'name', style: 'width: 200px'" />
			</div>
			
			<div class="app-form-row">
				<label for="type"><?php echo $this->translator()->_('connection._share.type'); ?>:</label>
				<select id="fileConnectionAddTypeSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'type'">
					<option value="local"><?php echo $this->translator()->_('connection._share.typeLocal'); ?></option>
					<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
					require([
						"dojo/_base/array",
						"dijit/registry"
					], function(dojoArray, dijitRegistry) {
						var disabled = ("local" == value);
						dojoArray.forEach(["fileConnectionAddServerTextBox", "fileConnectionAddPortTextBox", "fileConnectionAddUsernameTextBox", "fileConnectionAddPasswordTextBox"], function(id, index) {
							dijitRegistry.byId(id).set("disabled", disabled);
						});
					});
					</script>
				</select>
			</div>
			
			<div class="app-form-row">
				<label for="server"><?php echo $this->translator()->_('connection._share.server'); ?>:</label>
				<input id="fileConnectionAddServerTextBoxTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'server', disabled: true, style: 'width: 200px'" />
			</div>
			
			<div class="app-form-row">
				<label for="port"><?php echo $this->translator()->_('connection._share.port'); ?>:</label>
				<input id="fileConnectionAddPortTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'port', disabled: true, style: 'width: 100px'" />
			</div>
			
			<div class="app-form-row">
				<label for="init_path"><?php echo $this->translator()->_('connection._share.initPath'); ?>:</label>
				<input id="fileConnectionAddInitPathTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'init_path', style: 'width: 300px'" />
			</div>
			
			<div class="app-form-row">
				<label for="user_name"><?php echo $this->translator()->_('connection._share.username'); ?>:</label>
				<input id="fileConnectionAddUsernameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'user_name', disabled: true, style: 'width: 200px'" />
			</div>
			
			<div class="app-form-row">
				<label for="password"><?php echo $this->translator()->_('connection._share.password'); ?>:</label>
				<input id="fileConnectionAddPasswordTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'password', type: 'password', disabled: true, style: 'width: 200px'" />
			</div>
			
			<input type="hidden" name="format" value="json" />
		</div>
	</div>
	<!-- /AddConnectionForm -->
</div>

<div id="fileConnectionAddStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'fileConnectionAddContainer', imageText: '<?php echo $this->translator(true)->_('global._share.savingAction'); ?>'"></div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/widget/Standby"
]);
</script>
