<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-11
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('connection.edit.title'));
?>

<div id="fileConnectionEditContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<?php if ($this->connection) : ?>
		<button id="fileConnectionEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-save'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("fileConnectionEditForm").validate()) {
					dijitRegistry.byId("fileConnectionEditStandby").show();
					dojoRequestXhr("<?php echo $this->url(array(), 'file_connection_edit'); ?>", {
						data: dojoDomForm.toObject("fileConnectionEditForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						dijitRegistry.byId("fileConnectionEditStandby").hide();
						dojoTopic.publish("/app/file/connection/edit/onComplete", data);
					});
				}
			});
			</script>
		</button>
		<?php endif; ?>
		
		<button id="fileConnectionEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', iconClass: 'app-icon app-icon-cancel'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/file/connection/edit/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- EditConnectionForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', design: 'sidebar', gutters: false, class: 'app-content-pane'">
	<?php if (!$this->connection) : ?>
		<?php echo sprintf($this->translator()->_('connection.edit.notFound'), $this->connectionId); ?>
	<?php else : ?>
	
		<div id="fileConnectionEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0">
				<span><?php echo $this->translator()->_('connection.edit.title'); ?></span>
			</h2>
			
			<div class="app-form-row">
				<label for="name"><?php echo $this->translator()->_('connection._share.name'); ?>:</label>
				<input id="fileConnectionEditNameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'name', value: '<?php echo addslashes($this->connection->name); ?>', style: 'width: 200px'" />
			</div>
			
			<div class="app-form-row">
				<label for="type"><?php echo $this->translator()->_('connection._share.type'); ?>:</label>
				<select id="fileConnectionEditTypeSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'type', value: '<?php echo $this->connection->type; ?>'">
					<option value="local"><?php echo $this->translator()->_('connection._share.typeLocal'); ?></option>
	 				<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
					require([
						"dojo/_base/array",
						"dijit/registry"
					], function(dojoArray, dijitRegistry) {
						var disabled = ("local" == value);
						dojoArray.forEach(["fileConnectionEditServerTextBox", "fileConnectionEditPortTextBox", "fileConnectionEditUsernameTextBox", "fileConnectionEditPasswordTextBox"], function(id, index) {
							dijitRegistry.byId(id).set("disabled", disabled);
						});
					});
					</script>
				</select>
			</div>
			
			<div class="app-form-row">
				<label for="server"><?php echo $this->translator()->_('connection._share.server'); ?>:</label>
				<input id="fileConnectionEditServerTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'server', value: '<?php if ($this->connection && $this->connection->server) : ?><?php echo addslashes($this->connection->server); ?><?php endif; ?>', disabled: true, style: 'width: 200px'" />
			</div>
			
			<div class="app-form-row">
				<label for="port"><?php echo $this->translator()->_('connection._share.port'); ?>:</label>
				<input id="fileConnectionEditPortTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'port', value: '<?php if ($this->connection && $this->connection->port) : ?><?php echo addslashes($this->connection->port); ?><?php endif; ?>', disabled: true, style: 'width: 100px'" />
			</div>
			
			<div class="app-form-row">
				<label for="init_path"><?php echo $this->translator()->_('connection._share.initPath'); ?>:</label>
				<input id="fileConnectionEditInitPathTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'init_path', value: '<?php if ($this->connection && $this->connection->init_path) : ?><?php echo addslashes($this->connection->init_path); ?><?php endif; ?>', style: 'width: 300px'" />
			</div>
			
			<div class="app-form-row">
				<label for="user_name"><?php echo $this->translator()->_('connection._share.username'); ?>:</label>
				<input id="fileConnectionEditUsernameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'user_name', value: '<?php if ($this->connection && $this->connection->user_name) : ?><?php echo addslashes($this->connection->user_name); ?><?php endif; ?>', disabled: true, style: 'width: 200px'" />
			</div>
			
			<div class="app-form-row">
				<label for="password"><?php echo $this->translator()->_('connection._share.password'); ?>:</label>
				<input id="fileConnectionEditPasswordTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'password', type: 'password', value: '<?php if ($this->connection && $this->connection->password) : ?><?php echo addslashes($this->connection->password); ?><?php endif; ?>', disabled: true, style: 'width: 200px'" />
			</div>
			
			<input type="hidden" name="format" value="json" />
			<input type="hidden" name="connection_id" value="<?php echo $this->connection->connection_id; ?>" />
		</div>
	
	<?php endif; ?>
	</div>
	<!-- /EditConnectionForm -->
</div>

<div id="fileConnectionEditStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'fileConnectionEditContainer', imageText: '<?php echo $this->translator(true)->_('global._share.savingAction'); ?>'"></div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar",
	"dojox/widget/Standby"
]);
</script>
