<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	templates
 * @package		admin
 * @subpackage	layouts
 * @since		1.0
 * @version		2012-08-24
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>
<!DOCTYPE html>
<html dir="<?php echo $this->APP_LANGUAGE_DIR; ?>">
<head>
	<?php echo $this->headTitle(); ?>
	<meta http-equiv="Content-Type" content="text/html; charset=<?php echo $this->APP_CHARSET; ?>" />
	<meta name="robots" content="noindex, nofollow" />
	<?php echo $this->headMeta(); ?>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->APP_STATIC_URL; ?>/templates/admin/skins/default/images/favicon.ico" />
	<?php 
	$this->style()
		 ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dijit/themes/' . $this->dojoConfig()->getTheme() . '/' . $this->dojoConfig()->getTheme() . '.css')
		 ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dijit/themes/' . $this->dojoConfig()->getTheme() . '/document.css')
		 ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dojox/widget/Toaster/Toaster.css')
		 ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dojox/layout/resources/ExpandoPane.css')
		->appendStylesheet($this->APP_STATIC_URL . '/templates/admin/skins/default/styles.css');
	// Support RTL language
	if ('rtl' == $this->APP_LANGUAGE_DIR) {
		$this->style()
			 ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dijit/themes/' . $this->dojoConfig()->getTheme() . '/' . $this->dojoConfig()->getTheme() . '_rtl.css')
			 ->appendStylesheet($this->APP_STATIC_URL . '/templates/admin/skins/default/styles_rtl.css');
	}
	echo $this->style();
	// echo $this->style()->minify();
	?>
	<script type="text/javascript" src="<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojo/dojo.js" data-dojo-config="async: true, parseOnLoad: true, isDebug: true, ioPublish: true"></script>
	<script type="text/javascript" src="<?php echo $this->APP_STATIC_URL; ?>/static/js/tiny_mce/tiny_mce.js"></script>
	<script type="text/javascript">
	require({
		paths: {
			"core": "<?php echo $this->APP_STATIC_URL; ?>/modules/core"
		}
	});
	require(["core/js/base/I18N", "core/js/Constant"], function() {
		core.js.base.I18N.setLocale("<?php echo $this->APP_LANGUAGE; ?>");
		core.js.Constant.ROOT_URL = "<?php echo $this->APP_ROOT_URL; ?>";
	});
	</script>
</head>
<body class="<?php echo $this->dojoConfig()->getTheme(); ?>">
	<!-- Loader -->
	<div id="appLayoutLoader" class="app-layout-loader">
		<div><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global._share.loadingAction'); ?></div>
	</div>
	<!-- /Loader -->

	<!-- PoweredBy -->
	<div class="app-layout-poweredby">
		Powered by <a href="http://nextcms.org" target="_blank">NextCMS</a>
	</div>
	<!-- /PoweredBy -->

	<!-- Main -->
	<div id="appLayoutContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', gutters: true, class: 'app-layout-container'">
		<!-- Menu -->
		<div data-dojo-type="dijit/MenuBar" data-dojo-props="region:'top'">
			<div id="appLayoutAdminPersonalMenuBar" data-dojo-type="dijit/PopupMenuBarItem">
				<span><?php echo sprintf($this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.welcome'), Zend_Auth::getInstance()->getIdentity()->user_name); ?></span>

				<div data-dojo-type="dijit/Menu">
					<!-- DashboardMenuItem -->
					<div id="appLayoutAdminDashboardMenuItem" data-dojo-type="dijit/MenuItem">
						<a href="<?php echo $this->url(array(), 'core_dashboard_index'); ?>" class="appTopMenuItem" data-app-ajax="false"><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.dashboard'); ?></a>
					</div>
					<!-- /DashboardMenuItem -->

					<!-- HomepageMenuItem -->
					<div id="appLayoutAdminHomepageMenuItem" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon app-icon-home'">
						<a href="<?php echo $this->APP_URL; ?>" class="appTopMenuItem" data-app-ajax="false"><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.homepage'); ?></a>
					</div>
					<!-- /HomepageMenuItem -->
					
					<div data-dojo-type="dijit/MenuSeparator"></div>
					
					<!-- ProfileMenuItem -->
					<div id="appLayoutAdminProfileMenuItem" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon app-icon-profile'">
						<a href="<?php echo $this->url(array(), 'core_profile_edit'); ?>" class="appTopMenuItem" data-app-ajax="true"><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.profile'); ?></a>
					</div>
					<!-- /ProfileMenuItem -->
					
					<!-- OpenIdMenuItem -->
					<div id="appLayoutAdminOpenIdMenuItem" data-dojo-type="dijit/MenuItem" data-dojo-props="iconClass: 'app-icon app-icon-openid'">
						<a href="<?php echo $this->url(array(), 'core_openid_list'); ?>" class="appTopMenuItem" data-app-ajax="true"><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.openIdIdentities'); ?></a>
					</div>
					<!-- /OpenIdMenuItem -->
					
					<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowPersonalMenu'); ?>
					
					<div data-dojo-type="dijit/MenuSeparator"></div>
					
					<!-- LogoutMenuItem -->
					<div id="appLayoutAdminLogoutMenuItem" data-dojo-type="dijit/MenuItem">
						<a href="<?php echo $this->url(array(), 'core_auth_logout'); ?>" class="appTopMenuItem" data-app-ajax="false"><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.logout'); ?></a>
					</div>
					<!-- /LogoutMenuItem -->
				</div>
			</div>
			
			<!-- ModulesMenu -->
			<?php if ($modules = $this->backendMenu()->modules()) : ?>
			<div id="appLayoutAdminModulesMenuBar" data-dojo-type="dijit/PopupMenuBarItem">
				<span><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global.layout.modules'); ?></span>
				
				<div data-dojo-type="dijit/Menu">
					<?php foreach ($modules as $module => $items) : ?>
					<div id="appLayoutAdminModulesMenu_<?php echo $module; ?>" data-dojo-type="dijit/PopupMenuItem">
						<span><?php if ($items['icon']) : ?><img src="<?php echo $this->APP_STATIC_URL . $items['icon']; ?>" style="vertical-align: middle" /> <?php endif; ?><?php echo $items['name']; ?></span>
						
						<div data-dojo-type="dijit/Menu">
							<?php foreach ($items['items'] as $route => $data) : ?>
							<div id="appLayoutAdminModulesMenuItem_<?php echo $route; ?>" data-dojo-type="dijit/MenuItem">
								<a href="<?php echo $this->url(array(), $route); ?>" class="appTopMenuItem" data-app-ajax="<?php if ($data['ajax']) : ?>true<?php else : ?>false<?php endif; ?>"><?php if ($data['icon']) : ?><img src="<?php echo $this->APP_STATIC_URL . $data['icon']; ?>" style="vertical-align: middle" /> <?php endif; ?><?php echo $data['title']; ?></a>
							</div>
							<?php endforeach; ?>
							
							<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowMenu_' . $module); ?>
						</div>
					</div>
					<?php endforeach; ?>
				</div>
			</div>
			<?php endif; ?>
			<!-- /ModulesMenu -->
		</div>
		<!-- /Menu -->

		<!-- Content -->
		<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', region: 'center', gutters: true">
			<!-- Toolbox -->
			<div data-dojo-type="dojox/layout/ExpandoPane" data-dojo-props="region: 'left', splitter: true, previewOnDblClick: false, startExpanded: false, maxWidth: 300, title: '<?php echo $this->translator(true)->setLanguageDir('/modules/core/languages')->_('global.layout.toolbox'); ?>', style: 'width: 300px'">
				<div id="appLayoutToolboxContainer" data-dojo-type="dijit/layout/TabContainer" data-dojo-props="tabPosition: 'bottom', tabStrip: true">
					<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: false, nested: true, region: 'center', gutters: false, iconClass: 'app-icon app-icon-link', title: '<?php echo $this->translator(true)->setLanguageDir('/modules/core/languages')->_('global.layout.linkToolbox'); ?>'">
						<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowLinkToolbox'); ?>
					</div>
				
					<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: false, nested: true, region: 'center', gutters: false, iconClass: 'app-icon app-icon-image', title: '<?php echo $this->translator(true)->setLanguageDir('/modules/core/languages')->_('global.layout.imageToolbox'); ?>'">
						<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowImageToolbox'); ?>
					</div>
					
					<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: false, nested: true, region: 'center', gutters: false, iconClass: 'app-icon app-icon-video', title: '<?php echo $this->translator(true)->setLanguageDir('/modules/core/languages')->_('global.layout.videoToolbox'); ?>'">
						<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowVideoToolbox'); ?>
					</div>
				
					<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: false, nested: true, region: 'center', gutters: false, iconClass: 'app-icon app-icon-file', title: '<?php echo $this->translator(true)->setLanguageDir('/modules/core/languages')->_('global.layout.fileToolbox'); ?>'">
						<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowFileToolbox'); ?>
					</div>
					
					<?php Core_Base_Hook_Registry::getInstance()->executeAction('Core_Layout_Admin_ShowToolboxPane'); ?>
				</div>
			</div>
			<!-- /Toolbox -->
			
			<div id="appLayoutContentPane" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'center', loadingMessage: '<div class=app-center><div><span class=dijitContentPaneLoading><?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global._share.loadingAction'); ?></span></div></div>', style: 'border: none; padding: 0'">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
		<!-- /Content -->
	</div>
	<!-- /Main -->

	<!-- Notifications -->
	<div id="appLayoutNotification" data-dojo-type="dojox/widget/Toaster" data-dojo-props="positionDirection: '<?php echo $this->config('core', 'notification_position', 'tr-down'); ?>', messageTopic: '/app/global/notification', separator: '<hr />', duration: <?php echo $this->config('core', 'notification_duration', 2) * 1000; ?>">
		<script type="dojo/on">
		var that = this;
		require(["dojo/topic"], function(dojoTopic) {
			dojoTopic.subscribe("/app/global/updateNotificationSettings", function(data) {
				that.positionDirection = data.position || "tr-down";
				that.duration		   = data.duration || 2000;
			});
		});
		</script>
	</div>
	<!-- /Notifications -->

<?php $this->script()->captureStart(); ?>
require([
	"dojo/_base/array",
	"dojo/_base/fx",
	"dojo/_base/lang",
	"dojo/aspect",
	"dojo/dom-attr",
	"dojo/dom-style",
	"dojo/hash",
	"dojo/io-query",
	"dojo/on",
	"dojo/ready",
	"dojo/request/xhr",
	"dojo/topic",
	"dijit/registry",
	"dojo/NodeList-traverse",
	"dojo/parser",
	"dojo/query",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Menu",
	"dijit/MenuBar",
	"dijit/MenuBarItem",
	"dijit/MenuItem",
	"dijit/MenuSeparator",
	"dijit/PopupMenuBarItem",
	"dijit/PopupMenuItem",
	"dojox/layout/ContentPane",
	"dojox/layout/ExpandoPane",
	"dojox/widget/Standby",
	"dojox/widget/Toaster",
	"core/js/base/controllers/ActionProvider",
	"core/js/base/controllers/Subscriber",
	"core/js/base/dnd/TargetManager"
], function(dojoArray, dojoFx, dojoLang, dojoAspect, dojoDomAttr, dojoDomStyle, dojoHash, dojoIoQuery, dojoOn, dojoReady, dojoRequestXhr, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		/* ========== LOADING EFFECT ======================================== */
	
		// Create a Standby instance
		var appStandBy = new dojox.widget.Standby({
			target: "appLayoutContainer",
			imageText: "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('global._share.loadingAction'); ?>"
		});
		document.body.appendChild(appStandBy.domNode);
		appStandBy.startup();
		
		// Add pre-loading
		setTimeout(function() {
			dojoFx.fadeOut({
				node: "appLayoutLoader",
				duration: 500,
				onEnd: function() {
					dojoDomStyle.set("appLayoutLoader", "display", "none");
				}
			}).play();
		}, 500);
	
		/* ========== HANDLE MENU EVENT ===================================== */
		
		// DOJO LESSON: dijit.Menu widget is placed at the bottom of page.
		// Therefore the following query statement does NOT work:
		// 		dojo.query("#appHeader a.appTopMenuItem").forEach(...);
		dojo.query("a.appTopMenuItem").forEach(function(node, index, arr) {
			dojoOn(node, "click", function(e) {
				var ajax = dojoDomAttr.get(node, "data-app-ajax");
				if ("true" == ajax) {
					// Load the accessoring route
					e.preventDefault();
					// Update the location hash
					var href = dojoDomAttr.get(node, "href");
					var hash = "u=" + href;
					dojoHash(hash);
					dojoTopic.publish("/app/global/onHashChange", hash);
				} else {
					// Redirect user to desired page
					window.location = dojoDomAttr.get(node, "href");
				}
			});
		});
	
		/* ========== TOPICS ================================================ */
		
		dojoTopic.subscribe("/app/global/onSelectToolbox", function(/*String*/ toolboxIdContainer) {
			// summary:
			//		Activates the toolbox
			// toolboxIdContainer:
			//		The Id of toolbox container
			var pane = dijitRegistry.byId(toolboxIdContainer);
			if (!pane) {
				return;
			}
			var appLayoutToolboxContainer = dijitRegistry.byId("appLayoutToolboxContainer");
			var children = appLayoutToolboxContainer.getChildren();
	
			// Select the toolbox pane
			if (dojoArray.indexOf(children, pane) != -1) {
				appLayoutToolboxContainer.selectChild(pane);
			} else {
				// The pane belongs to a group of tab containers
				var parent = pane.getParent();
				if (dojoArray.indexOf(children, parent) != -1) {
					appLayoutToolboxContainer.selectChild(parent);
				}
				parent.selectChild(pane);
			}
	
			// Expand the toolbox pane if it is hidden
			var expandoPane = appLayoutToolboxContainer.getParent();
			if ("hidden" == dojoDomStyle.get(expandoPane.cwrapper, "visibility")) {
				expandoPane.toggle();
			}
		});
	
		dojoTopic.subscribe("/app/global/onRemoveToolbox", function(/*String|String[]*/ toolboxIdContainers) {
			// summary:
			//		Removes toolbox after uninstalling the hook
			// toolboxIdContainers:
			//		Id or array of container's Ids
			var appLayoutToolboxContainer = dijitRegistry.byId("appLayoutToolboxContainer");
			var ids = dojoLang.isArray(toolboxIdContainers) ? toolboxIdContainers : [ toolboxIdContainers ];
			dojoArray.forEach(ids, function(id) {
				var pane = dijitRegistry.byId(id);
				if (dojoArray.indexOf(appLayoutToolboxContainer.getChildren(), pane) != -1) {
					appLayoutToolboxContainer.removeChild(pane);
				} else {
					var parent = pane.getParent();
					parent.removeChild(pane);
				}
				pane.destroyRecursive();
			});
		});
	
		// Below are the topics which the sub-modules can subscribe to update UI
		dojoTopic.subscribe("/app/global/onHashChange", function(/*String*/ hash) {
			// I do not use the "dojo/hashchange" channel of Dojo, because I want 
			// to update the location hash without making new request
			var obj = dojoIoQuery.queryToObject(hash);
			var url = obj.u;
			
			// If you want to make new Ajax request, pass the param u=yourUrl to hash
			if (!url) {
				return;
			}
			
			core.js.base.controllers.Subscriber.unsubscribeAll("/app/global/dnd/onDropImage");
			core.js.base.controllers.Subscriber.unsubscribeAll("/app/global/dnd/onDropLink");
			core.js.base.controllers.Subscriber.unsubscribeAll("/app/global/dnd/onDropVideo");
	
			dijitRegistry.byId("appLayoutContentPane").set("preventCache", true).set("href", url);
		});
	
		// I cannot retrive any Dijit widget instances in the response of an Ajax request as follow:
		// 		<div data-dojo-type="..." id="widgetId"></div>
		//		...
		//		console.log(dijitRegistry.byId(widgetId));			// undefined
		//		dojoReady(function() {
		//			console.log(dijitRegistry.byId(widgetId));		// undefined
		//			setTimeout(function() {
		//				console.log(dijitRegistry.byId(widgetId));	// It works, but it is not a nice solution
		//			}, 100);
		//		});
		//
		// The solution is that publish a topic after the additional pane is fully loaded (by connecting "onDownloadEnd" event of the pane).
		// Publishing "/dojo/io/load" topic does not help, because it will be called before the response is fully loaded.
		// Below is sample usage:
		//		// At the page showing the pane
		//		<div data-dojo-type="..." id="pane"></div>
		//		...
		//		dijitRegistry.byId("pane").set("href", backendUrl);
		//		dojoOn(dijitRegistry.byId("pane"), "downloadEnd", function() {
		//			dojoTopic.publish("/app/global/onLoadComplete/moduleName_controllerName_actionName");
		//		});
		
		//		// The view script associating with backendUrl
		//		<div data-dojo-type="..." id="widgetId"></div>
		//		...
		//		var handler = dojoTopic.subscribe("/app/global/onLoadComplete/moduleName_controllerName_actionName", function() {
		//			var widget = dijitRegistry.byId(widgetId);
		//			... Do something with the widget ...
		//			handler.remove();
		//		});
		dojoTopic.subscribe("/app/global/onLoadComplete", function(/*String*/ url) {
			var prefixUrl = "<?php echo $this->backendUrl(); ?>";
			if (!url || url.substr(0, prefixUrl.length) != prefixUrl) {
				return;
			}
			url = url.substr(prefixUrl.length);
			// Now, url is in the format of /module/controller/action/query
			if (url.length > 0 && "/" == url[0]) {
				url = url.substr(1);
			}
			var paths = url.split("/");
			if (paths.length >= 3) {
				var module = paths[0], controller = paths[1], action = paths[2];
				if ((pos = action.indexOf("?")) != -1) {
					action = action.substr(0, pos);
				}
				dojoTopic.publish("/app/global/onLoadComplete/" + [module, controller, action].join("_"));
			}
		});
		
		var appLayoutContentPane = dijitRegistry.byId("appLayoutContentPane");
		appLayoutContentPane._onLoadHandler = function(data) {
			// Override the _onLoadHandler() method to prevent Javascript error on console window
			// which I don't know where it comes from
			dojoTopic.publish("/app/global/onLoadComplete", appLayoutContentPane.get("href"));
		};
	
		// Handle drag and drop
		// Provide the URL to embed a video
		core.js.base.controllers.ActionProvider.set("core_helper_play", {
			url: "<?php echo $this->url(array(), 'core_helper_play'); ?>",
			isAllowed: true
		});
		var targetManager = core.js.base.dnd.TargetManager.getInstance();
		dojoTopic.subscribe("/app/global/onLoadComplete", function(url) {
			dojo.query("textarea, input[type='text'], span.mceEditor").forEach(function(node) {
				targetManager.add(node, ["appDndImage"], core.js.base.dnd.TargetManager.handleDropImage);
				targetManager.add(node, ["appDndVideo"], core.js.base.dnd.TargetManager.handleDropVideo);
				targetManager.add(node, ["appDndLink"], core.js.base.dnd.TargetManager.handleDropLink);
			});
		});
	
		// Automatically make a request based on current location hash
		if (dojoHash()) {
			dojoTopic.publish("/app/global/onHashChange", dojoHash());
		}
	});
});
<?php $this->script()->captureEnd(); ?>

<?php 
// Place scripts at the bottom of page
echo $this->script();
?>
</body>
</html>
