<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		menu
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('menu.edit.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/menu/css/admin/default/styles.css");	
});
</script>

<div id="menuMenuEditContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<?php if ($this->menu) : ?>
		<button id="menuMenuEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>
		<?php endif; ?>
		
		<button id="menuMenuEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/topic",
				"core/js/base/controllers/Subscriber"
			], function(dojoTopic) {
				core.js.base.controllers.Subscriber.unsubscribe("/app/menu/menu/edit", "/app/global/dnd/onDropLink");
				dojoTopic.publish("/app/menu/menu/edit/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, region: 'center'">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('menu.edit.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<?php if (!$this->menu) : ?>
				<?php echo sprintf($this->translator()->_('menu.edit.notFound'), $this->menuId); ?>
			<?php else : ?>
		
			<div id="menuMenuEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('menu._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="language"><?php echo $this->translator()->_('menu._share.language'); ?>:</label>
							<select id="menuMenuEditLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language'">
								<?php foreach ($this->languages as $language => $name) : ?>
								<option value="<?php echo $language; ?>"<?php if ($language == $this->menu->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
					
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('menu._share.title'); ?>:</label>
							<input id="menuMenuEditTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', value: '<?php echo addslashes($this->menu->title); ?>', name: 'title', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('menu._share.titleRequired'); ?>'" />
						</div>
						
						<div class="app-form-row">
							<label for="description"><?php echo $this->translator()->_('menu._share.description'); ?>:</label>
							<textarea id="menuMenuEditDescriptionTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'description', style: 'width: 300px; height: 150px'"><?php if ($this->menu->description) : ?><?php echo $this->menu->description; ?><?php endif; ?></textarea>
						</div>
						
						<input type="hidden" name="format" value="json" />
						<input type="hidden" name="menu_id" value="<?php echo $this->menu->menu_id; ?>" />
					</div>
					<!-- /Properties -->
					
					<!-- Structure -->
					<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', gutters: false, title: '<?php echo $this->translator(true)->_('menu._share.structure'); ?>', style: 'margin-top: 8px'">
						<!-- Item -->
						<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, region: 'left', style: 'width: 50%', class: 'app-form module-menu-items-form'">
							<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top'">
								<div class="app-heading">
									<span><?php echo $this->translator()->_('menu._share.item'); ?></span>
								</div>
							</div>
							
							<div id="menuMenuEditItemContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'">
								<div id="menuMenuEditItemFormContainer" style="margin: 4px; padding: 4px">
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.title'); ?>:</label>
										<input id="menuMenuEditItemTitleTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="itemProperty: 'title', type: 'text', style: 'width: 95%', required: true, missingMessage: '<?php echo $this->translator(true)->_('menu._share.titleRequired'); ?>'" />
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.subTitle'); ?>:</label>
										<input id="menuMenuEditItemSubTitleTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="itemProperty: 'sub_title', type: 'text', style: 'width: 95%'" />
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.description'); ?>:</label>
										<textarea id="menuMenuEditItemDescriptionTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="itemProperty: 'description', style: 'width: 95%; height: 100px'"></textarea>
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.link'); ?>:</label>
										<div id="menuMenuEditItemLinkTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="itemProperty: 'link', type: 'text', style: 'width: 95%', required: true, missingMessage: '<?php echo $this->translator(true)->_('menu._share.linkRequired'); ?>'">
											<script type="dojo/on">
											var that = this;
											require([
												"dojo/dom-attr",
												"dijit/registry",
												"core/js/base/controllers/Subscriber"
											], function(dojoDomAttr, dijitRegistry) {
												core.js.base.controllers.Subscriber.subscribe("/app/menu/menu/edit", "/app/global/dnd/onDropLink", this, function(data) {
													if (dojoDomAttr.get(data.target, "id") == that.id) {
														dijitRegistry.byId("menuMenuEditItemTitleTextBox").set("value", data.title);
													}
												});
											});
											</script>
										</div>
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.image'); ?>:</label>
										<input id="menuMenuEditItemImageTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="itemProperty: 'image', type: 'text', style: 'width: 95%'" />
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.target'); ?>:</label>
										<select id="menuMenuEditItemTargetSelect" data-dojo-type="dijit/form/Select" data-dojo-props="itemProperty: 'target'">
											<option value="_self"><?php echo $this->translator()->_('menu._share.targetSelf'); ?></option>
											<option value="_blank"><?php echo $this->translator()->_('menu._share.targetBlank'); ?></option>
										</select>
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.htmlId'); ?>:</label>
										<input id="menuMenuEditItemIdTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="itemProperty: 'html_id', type: 'text', style: 'width: 95%'" />
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.cssClass'); ?>:</label>
										<input id="menuMenuEditItemCssClassTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="itemProperty: 'css_class', type: 'text', style: 'width: 95%'" />
									</div>
									
									<div class="app-form-row-vertical">
										<label><?php echo $this->translator()->_('menu._share.cssStyle'); ?>:</label>
										<textarea id="menuMenuEditItemCssStyleTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="itemProperty: 'css_style', style: 'width: 95%; height: 100px'"></textarea>
									</div>
									
									<div class="app-form-row">
										<button id="menuMenuEditItemAddButton" data-dojo-type="dijit/form/Button" data-dojo-props="label: '<?php echo $this->translator(true)->_('global._share.addAction'); ?>'"></button>
										
										<button id="menuMenuEditItemCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="label: '<?php echo $this->translator(true)->_('global._share.cancelAction'); ?>'">
											<script type="dojo/on" data-dojo-event="click">
											require([
												"dojo/_base/array",
												"dojo/dom-attr",
												"dijit/registry",
											], function(dojoArray, dojoDomAttr, dijitRegistry) {
												dojoDomAttr.set("menuMenuEditItemId", "value", "");
												var name;
												dojoArray.forEach(dijitRegistry.byId("menuMenuEditItemContainer").getChildren(), function(child) {
													if (name = child.get("itemProperty")) {
														child.set("value", "");
													}
												});
												dijitRegistry.byId("menuMenuEditItemTargetSelect").set("value", "_self");
												dijitRegistry.byId("menuMenuEditItemAddButton").set("label", "<?php echo $this->translator()->_('global._share.addAction'); ?>");
											});
											</script>
										</button>
									</div>
									
									<input type="hidden" id="menuMenuEditItemId" value="" />
								</div>
							</div>
						</div>
						<!-- /Item -->
						
						<!-- ItemTree -->
						<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters: false, region: 'center', style: 'padding: 0; width: 50%'"> 
							<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top'">
								<div class="app-heading">
									<span><?php echo $this->translator()->_('menu._share.itemsTree'); ?></span>
								</div>
							</div>
							
							<div id="menuMenuEditItemTreeContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'">
							</div>
						</div>
						<!-- /ItemTree -->
					</div>
					<!-- /Structure -->
					
					<!-- Localization -->
					<div id="menuMenuEditLocalizedContainer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('menu._share.localization'); ?>', class: 'app-container-border', style: 'margin-top: 8px'">
						<?php if ($this->translations) : ?>
						<?php foreach ($this->translations as $tranlation) : ?>
						<div class="menuMenuEditLocalizedItem" style="padding: 2px 8px" data-app-translations='<?php echo $tranlation->translations; ?>'>
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->title); ?>', style: 'width: 300px', readOnly: true" />
							<input data-dojo-type="dijit/form/TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
							<input type="hidden" name="translations" value='<?php echo $tranlation->translations; ?>' />
							
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
								<script type="dojo/on" data-dojo-event="click">
								var that = this;
								require([
									"dojo/dom-attr",
									"dojo/dom-style",
									"dojo/NodeList-dom",
									"dojo/NodeList-traverse",
									"dojo/query"
								], function(dojoDomAttr, dojoDomStyle) {
									var localizedItem = dojo.query(that.domNode).closest(".menuMenuEditLocalizedItem")[0];
									var translations  = dojoDomAttr.get(localizedItem, "data-app-translations");
									dojo.query(".menuMenuEditLocalizedItem[data-app-translations='" + translations + "']", "menuMenuEditLocalizedContainer").orphan();
									if (0 == dojo.query(".menuMenuEditLocalizedItem", "menuMenuEditLocalizedContainer").length) {
										// Show the guide
										dojoDomStyle.set("menuMenuEditLocalizedHelp", "display", "block");
									}
								});
								</script>
							</button>
						</div>
						<?php endforeach; ?>
						<?php endif; ?>
						
						<div id="menuMenuEditLocalizedHelp" class="app-center" style="display: <?php if ($this->translations && count($this->translations) > 0) : ?>none<?php else : ?>block<?php endif; ?>">
							<div><?php echo $this->translator()->_('menu._share.localizationHelp'); ?></div>
						</div>
					</div>
					<!-- /Localization -->
				</div>
			</div>
			
			<?php endif; ?>
		</div>
	</div>
</div>

<script type="text/javascript">
require({
	paths: {
		"menu": "<?php echo $this->APP_STATIC_URL; ?>/modules/menu"
	}
});

require([
	"dojo/_base/array",
	"dojo/aspect",
	"dojo/dom-attr",
	"dojo/dom-construct",
	"dojo/dom-form",
	"dojo/dom-style",
	"dojo/json",
	"dojo/on",
	"dojo/ready",
	"dojo/request/xhr",
	"dojo/topic",
	"dijit/registry",
	"dojo/dnd/Target",
	"dojo/NodeList-traverse",
	"dojo/parser",
	"dojo/query",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojox/grid/enhanced/plugins/GridSource",
	"menu/js/views/ItemTreeView"
], function(dojoArray, dojoAspect, dojoDomAttr, dojoDomConstruct, dojoDomForm, dojoDomStyle, dojoJson, dojoOn, dojoReady, dojoRequestXhr, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		var target = new dojox.grid.enhanced.plugins.GridSource("menuMenuEditLocalizedContainer", {
			isSource: false,
			insertNodesForGrid: false
		});
		dojoOn(target, "dropgridrows", function(grid, rowIndexes) {
			var sourceItems = [];
			dojoArray.forEach(rowIndexes, function(rowIndex, index) {
				var item = grid.getItem(rowIndex);
				if (item) {
					sourceItems.push(item);
				}
			});

			if (sourceItems.length > 0) {
				// Hide the guide
				dojoDomStyle.set("menuMenuEditLocalizedHelp", "display", "none");
			}

			dojoArray.forEach(sourceItems, function(item) {
				var div = dojoDomConstruct.create("div", {
					className: "menuMenuEditLocalizedItem",
					style: "padding: 2px 8px",
					"data-app-translations": item.translations[0]
				}, "menuMenuEditLocalizedContainer");

				new dijit.form.TextBox({
					value: item.title[0],
					style: "width: 300px",
					readOnly: true
				}).placeAt(div);
				
				new dijit.form.TextBox({
					value: item.language[0],
					style: "margin: 0 8px; width: 100px",
					readOnly: true
				}).placeAt(div);

				dojoDomConstruct.create("input", {
					name: "translations",
					type: "hidden",
					value: item.translations[0]
				}, div);

				new dijit.form.Button({
					label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
					onClick: function() {
						var localizedItem = dojo.query(this.domNode).closest(".menuMenuEditLocalizedItem")[0];
						var translations  = dojoDomAttr.get(localizedItem, "data-app-translations");
						dojo.query(".menuMenuEditLocalizedItem[data-app-translations='" + translations + "']", "menuMenuEditLocalizedContainer").orphan();
						if (0 == dojo.query(".menuMenuEditLocalizedItem", "menuMenuEditLocalizedContainer").length) {
							// Show the guide
							dojoDomStyle.set("menuMenuEditLocalizedHelp", "display", "block");
						}
					}
				}).placeAt(div);
			});
		});
		
		var itemTreeView = new menu.js.views.ItemTreeView("menuMenuEditItemTreeContainer");
		itemTreeView.setItems(<?php echo $this->items; ?>);

		// Quickly edit the node by dragging the node and dropping it on the form
		new dojo.dnd.Target("menuMenuEditItemFormContainer", {
			accept: ["treeNode"],
			onDropExternal: function(source, nodes, copy) {
				var treeNode = dijitRegistry.byNode(nodes[0]);
				if (treeNode) {
					if (2 == treeNode.getTreePath().length) {
						// User drop the root node
						// Do nothing
						// FIXME: Is there a better way to check if a node is the root one?
					} else {
						itemTreeView.onEditItem(treeNode.item);
					}
				}
			}
		});
		
		// Add new item handler
		dojoOn(dijitRegistry.byId("menuMenuEditItemAddButton"), "click", function() {
			var item = {
				item_id: dojoDomAttr.get("menuMenuEditItemId", "value")
			};
			var name;
			dojoArray.forEach(dijitRegistry.byId("menuMenuEditItemContainer").getChildren(), function(child) {
				if (name = child.get("itemProperty")) {
					item[name] = child.get("value");
				}
			});
			itemTreeView.saveItem(item);
		});

		// Edit item handler
		dojoAspect.after(itemTreeView, "onEditItem", function(/*dojo.data.Item*/ item) {
			// Change the label of "Add item" button
			dijitRegistry.byId("menuMenuEditItemAddButton").set("label", "<?php echo $this->translator()->_('global._share.saveAction'); ?>");
			
			// Populate data to the item form
			dojoDomAttr.set("menuMenuEditItemId", "value", item.item_id[0]);
			var name;
			dojoArray.forEach(dijitRegistry.byId("menuMenuEditItemContainer").getChildren(), function(child) {
				if (name = child.get("itemProperty")) {
					if (item[name] && item[name][0]) {
						child.set("value", item[name][0]);
					}
				}
			});
		}, true);

		// Submit form handler
		dojoOn(dijitRegistry.byId("menuMenuEditSaveButton"), "click", function() {
			var items = itemTreeView.getItems();
			if (dijitRegistry.byId("menuMenuEditForm").validate()) {
				var params   = dojoDomForm.toObject("menuMenuEditForm");
				params.items = dojoJson.stringify(items);
				dojoTopic.publish("/app/menu/menu/edit/onStart");
				dojoRequestXhr("<?php echo $this->url(array(), 'menu_menu_edit'); ?>", {
					data: params,
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					dojoTopic.publish("/app/menu/menu/edit/onComplete", data);
				});
			}
		});
	});
});
</script>
