<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	tasks
 * @since		1.0
 * @version		2012-09-15
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="app-form-row">
	<label for="max_mails" style="width: 400px"><?php echo $this->translator()->_('config.maxMails'); ?>:</label>
	<input id="coreTasksMailqueueConfigMaxMailsTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'max_mails', style: 'width: 100px', value: '<?php echo $this->maxMails; ?>'" />
</div>

<div class="app-form-row">
	<label for="max_attempts" style="width: 400px"><?php echo $this->translator()->_('config.maxAttempts'); ?>:</label>
	<input id="coreTasksMailqueueConfigMaxAttemptsTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="name: 'max_attempts', style: 'width: 100px', value: '<?php echo $this->maxAttempts; ?>'" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/TextBox"	
]);
</script>
