<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-14
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('page.import.title'));
?>

<div id="corePageImportForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', encType: 'multipart/form-data', class: 'app-form'">
	<!-- Uploader -->
	<div class="app-form-row">
		<div id="corePageImportUploaderContainer"></div>
	</div>
	<!-- /Uploader -->
	
	<div class="dijitDialogPaneActionBar">
		<button id="corePageImportCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/core/page/import/onCancel");
			});
			</script>
		</button>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/dom",
	"dojo/ready",
	"dojo/sniff",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"core/js/base/Uploader"
], function(dojoDom, dojoReady, dojoSniff, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		// Create uploader instance
		var uploader = new core.js.base.Uploader({
			id: "corePageImportUploader",
			name: "uploadedfile",
			flashFieldName: "uploadedfile",
			deferredUploading: true,
			multiple: false,
			type: "file",
			uploadOnSelect: true,
			serverTimeout: 10000,
			label: "<?php echo $this->translator(true)->_('global._share.browseFilesUploadAction'); ?>",
			url: dojoSniff("ie")
				 ? "<?php echo $this->url(array('page_id' => $this->page_id, 'format' => 'json', 'uploader' => 'flash'), 'core_page_import_upload'); ?>?PHPSESSID=<?php echo Zend_Session::getId(); ?>"
				 : "<?php echo $this->url(array('page_id' => $this->page_id, 'format' => 'json', 'uploader' => 'html5'), 'core_page_import_upload'); ?>",
			// Custom properties and override methods
			appUploadType: dojoSniff("ie") ? "flash" : "html5",
			onChange: function(fileArray) {
				// dijitRegistry.byId("corePageImportCancelButton").set("disabled", false);
			},
			onBegin: function(dataArray) {
				if ("html5" == this.get("appUploadType")) {
					this.set("disabled", true);
				}
				dijitRegistry.byId("corePageImportCancelButton").set("disabled", true);
			},
			onFileComplete: function(dataArray) {
				if ("flash" == this.get("appUploadType")) {
					dijitRegistry.byId("corePageImportCancelButton").set("disabled", false);
					
					dataArray = dataArray.additionalParams.appUploadedFiles;
					dataArray = core.js.base.Encoder.decode(dataArray);
					dojoTopic.publish("/app/core/page/import/onSuccess", dataArray);
				}
			},
			onComplete: function(dataArray) {
				if ("html5" == this.get("appUploadType")) {
					dijitRegistry.byId("corePageImportCancelButton").set("disabled", false);
					this.set("disabled", false);
					dojoTopic.publish("/app/core/page/import/onSuccess", dataArray);
				}
			}
		});
		dojoDom.byId("corePageImportUploaderContainer").appendChild(uploader.domNode);
		uploader.startup();
	});
});
</script>
