<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('profile.edit.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/password-meter.css");	
});
</script>

<div id="coreProfileEditContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'app-container-border'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="coreProfileEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				var form			= dijitRegistry.byId("coreProfileEditForm");
				var isValidUsername = dijitRegistry.byId("coreProfileEditUsernameTextbox").get("isValidUsername");
				var isValidEmail	= dijitRegistry.byId("coreProfileEditEmailTextbox").get("isValidEmail");
				if (isValidUsername && isValidEmail && form.validate()) {
					dijitRegistry.byId("coreProfileEditStandby").show();
				
					// Disable button
					that.set("disabled", true);
	
					dojoRequestXhr("<?php echo $this->url(array(), 'core_profile_edit'); ?>", {
						data: dojoDomForm.toObject("coreProfileEditForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dijitRegistry.byId("coreProfileEditStandby").hide();
						dojoTopic.publish("/app/global/notification", {
							message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->_('profile.edit.success'); ?>" : "<?php echo $this->translator()->_('profile.edit.error'); ?>",
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					});
				}
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- EditForm -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center'" class="app-content-pane">
		<div id="coreProfileEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
			<h2 class="app-heading" style="margin-top: 0"><span><?php echo $this->translator()->_('profile.edit.title'); ?></span></h2>
			
			<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: true, nested: true, style: 'height: 100%'">
				<!-- AccountTab -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('user._share.accountInfo'); ?>', class: 'app-content-pane'">
					<div class="app-form-row">
						<label for="user_name"><?php echo $this->translator()->_('user._share.username'); ?>:</label>
						<div id="coreProfileEditUsernameTextbox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="isValidUsername: true, type: 'text', name: 'user_name', value: '<?php echo $this->user->user_name; ?>', readOnly: <?php if ($this->user->isRootUser()) : ?>true<?php else : ?>false<?php endif; ?>, style: 'width: 200px', required: true, promptMessage: '<?php echo $this->translator(true)->_('user._share.usernameRequired'); ?>', invalidMessage: '<?php echo $this->translator(true)->_('user._share.usernameValidator'); ?>'">
							<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
							var that = this;
							require(["dojo/request/xhr"], function(dojoRequestXhr) {
								dojoRequestXhr("<?php echo $this->url(array(), 'core_user_checkusername'); ?>", {
									data: {
										user_name: value
									},
									handleAs: "json",
									method: "POST"
								}).then(function(data) {
									var isValid = data.result == true || data.result == "<?php echo $this->user->user_id; ?>";
									that.set("isValidUsername", isValid);
									if (!isValid) {
										// FIXME: How to show the error message and set the status as "error".
										// The following hack (because state is readonly property) does not 
										// always prevent user to submit form:
										// 		that.state = "Error";
										// 		dijit.regitry.byId("coreProfileEditForm").state = "Error";
										that.displayMessage(that.invalidMessage);
									}
								});
							});
							</script>
						</div>
					</div>
					
					<div class="app-form-row">
						<label for="password"><?php echo $this->translator()->_('user._share.password'); ?>:</label>
						<div id="coreProfileEditPasswordTextbox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'password', name: 'password', style: 'width: 200px', promptMessage: '<?php echo $this->translator(true)->_('user._share.passwordUnchangedHelp'); ?>', class: 'app-left'">
						</div>
						
						<!-- PasswordStrengthMeter -->
						<div class="app-left" id="coreProfileEditPasswordStrengthMeter"></div>
						<!-- /PasswordStrengthMeter -->
						
						<div class="app-clear"></div>
					</div>
					
					<div class="app-form-row">
						<label>&nbsp;</label>
						<?php echo $this->translator()->_('user._share.passwordUnchangedHelp'); ?>
					</div>
					
					<div class="app-form-row">
						<label for="email"><?php echo $this->translator()->_('user._share.email'); ?>:</label>
						<div id="coreProfileEditEmailTextbox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="isValidEmail: true, type: 'text', name: 'email', style: 'width: 200px', value: '<?php echo $this->user->email; ?>', required: true, promptMessage: '<?php echo $this->translator(true)->_('user._share.emailRequired'); ?>', invalidMessage: '<?php echo $this->translator(true)->_('user._share.emailValidator'); ?>'">
							<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
							var that = this;
							require(["dojo/request/xhr"], function(dojoRequestXhr) {
								dojoRequestXhr("<?php echo $this->url(array(), 'core_user_checkemail'); ?>", {
									data: {
										email: value
									},
									handleAs: "json",
									method: "POST"
								}).then(function(data) {
									var isValid = data.result == true || data.result == "<?php echo $this->user->user_id; ?>";
									that.set("isValidEmail", isValid);
									if (!isValid) {
										that.displayMessage(that.invalidMessage);
									}
								});
							});
							</script>
						</div>
					</div>
				</div>
				<!-- /AccountTab -->
				
				<!-- PersonalTab -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('user._share.personalInfo'); ?>', class: 'app-content-pane'">
					<div class="app-form-row">
						<label for="full_name"><?php echo $this->translator()->_('user._share.fullName'); ?>:</label>
						<input id="coreProfileEditFullNameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'full_name', value: '<?php echo $this->user->full_name; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="avatar"><?php echo $this->translator()->_('user._share.avatar'); ?>:</label>
						<input id="coreProfileEditAvatarTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'avatar', value: '<?php echo $this->user->avatar; ?>', style: 'width: 300px'">
					</div>
					
					<div class="app-form-row">
						<label for="dob"><?php echo $this->translator()->_('user._share.dob'); ?>:</label>
						<input id="coreProfileEditDobTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'dob', value: '<?php echo $this->user->dob; ?>'">
					</div>
					
					<div class="app-form-row">
						<label for="gender"><?php echo $this->translator()->_('user._share.gender'); ?>:</label>
						<select id="coreProfileEditGenderSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'gender', value: '<?php echo $this->user->gender; ?>'">
							<option value="f"><?php echo $this->translator()->_('user._share.genderFemale'); ?></option>
							<option value="m"><?php echo $this->translator()->_('user._share.genderMale'); ?></option>
						</select>
					</div>
					
					<div class="app-form-row">
						<label for="website"><?php echo $this->translator()->_('user._share.website'); ?>:</label>
						<input id="coreProfileEditWebsiteTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'website', value: '<?php if ($this->user->website) : ?><?php echo addslashes($this->user->website); ?><?php endif; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="bio"><?php echo $this->translator()->_('user._share.bio'); ?>:</label>
						<textarea id="coreProfileEditBioTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'bio', style: 'width: 350px; height: 100px'"><?php if ($this->user->bio) : ?><?php echo $this->user->bio; ?><?php endif; ?></textarea>
					</div>
					
					<div class="app-form-row">
						<label for="signature"><?php echo $this->translator()->_('user._share.signature'); ?>:</label>
						<textarea id="coreProfileEditSignatureTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'signature', style: 'width: 350px; height: 100px'"><?php if ($this->user->signature) : ?><?php echo $this->user->signature; ?><?php endif; ?></textarea>
					</div>
					
					<div class="app-form-row">
						<label for="twitter"><?php echo $this->translator()->_('user._share.twitter'); ?>:</label>
						<input id="coreProfileEditTwitterTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'twitter', value: '<?php if ($this->user->twitter) : ?><?php echo addslashes($this->user->twitter); ?><?php endif; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="facebook"><?php echo $this->translator()->_('user._share.facebook'); ?>:</label>
						<input id="coreProfileEditFacebookTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'facebook', value: '<?php if ($this->user->facebook) : ?><?php echo addslashes($this->user->facebook); ?><?php endif; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="flickr"><?php echo $this->translator()->_('user._share.flickr'); ?>:</label>
						<input id="coreProfileEditFlickrTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'flickr', value: '<?php if ($this->user->flickr) : ?><?php echo addslashes($this->user->flickr); ?><?php endif; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="youtube"><?php echo $this->translator()->_('user._share.youtube'); ?>:</label>
						<input id="coreProfileEditYoutubeTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'youtube', value: '<?php if ($this->user->youtube) : ?><?php echo addslashes($this->user->youtube); ?><?php endif; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="linkedin"><?php echo $this->translator()->_('user._share.linkedin'); ?>:</label>
						<input id="coreProfileEditLinkedInTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'linkedin', value: '<?php if ($this->user->linkedin) : ?><?php echo addslashes($this->user->linkedin); ?><?php endif; ?>', style: 'width: 200px'">
					</div>
					
					<div class="app-form-row">
						<label for="country"><?php echo $this->translator()->_('user._share.country'); ?>:</label>
						<select id="coreProfileEditCountrySelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'country', value: '<?php echo $this->user->country; ?>', maxHeight: 200, style: 'width: 350px'">
						<?php foreach ($this->countries as $code => $name) : ?>
							<option value="<?php echo $code; ?>"><?php echo $name; ?></option>
						<?php endforeach; ?>
						</select>
					</div>
					
					<div class="app-form-row">
						<label for="language"><?php echo $this->translator()->_('user._share.language'); ?>:</label>
						<select id="coreProfileEditLanguageSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'language', value: '<?php echo $this->user->language; ?>', maxHeight: 200, style: 'width: 350px'">
						<?php foreach ($this->languages as $code => $language) : ?>
							<option value="<?php echo $code; ?>"><?php echo $language; ?></option>
						<?php endforeach; ?>
						</select>
					</div>
					
					<div class="app-form-row">
						<label for="timezone"><?php echo $this->translator()->_('user._share.timezone'); ?>:</label>
						<select id="coreProfileEditTimezoneSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'timezone', value: '<?php echo $this->user->timezone; ?>', maxHeight: 200, style: 'width: 350px'">
						<?php foreach ($this->timeZones as $timeZone => $name) : ?>
							<option value="<?php echo $timeZone; ?>"><?php echo $timeZone; ?> (<?php echo $name; ?>)</option>
						<?php endforeach; ?>
						</select>
					</div>
				</div>
				<!-- /PersonalTab -->
				
				<input type="hidden" name="format" value="json" />
			</div>
		</div>
	</div>
	<!-- /EditForm -->
</div>

<div id="coreProfileEditStandby" data-dojo-type="dojox/widget/Standby" data-dojo-props="target: 'coreProfileEditContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('profile.edit.title'); ?>";

require([
	"dojo/on",
	"dojo/ready",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/DateTextBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojox/widget/Standby",
	"core/js/views/PasswordStrengthMeter"
], function(dojoOn, dojoReady, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		// Create new password strength meter instance
		var passwordStrengthMeter = new core.js.views.PasswordStrengthMeter("coreProfileEditPasswordStrengthMeter");
		passwordStrengthMeter.setUsername(dijitRegistry.byId("coreProfileEditUsernameTextbox").get("value"));
		
		dojoOn(dijit.byId("coreProfileEditUsernameTextbox"), "keyup", function() {
			passwordStrengthMeter.setUsername(dijitRegistry.byId("coreProfileEditUsernameTextbox").get("value"));
		});
		dojoOn(dijit.byId("coreProfileEditPasswordTextbox"), "keyup", function() {
			passwordStrengthMeter.checkPassword(dijitRegistry.byId("coreProfileEditPasswordTextbox").get("value"));
		});
	});
});
</script>
