<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		category
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('category.rename.title'));
?>

<div id="categoryCategoryRenameForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
	<script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
	e.preventDefault();
	var that = this;
	require([
		"dojo/dom-form",
		"dojo/request/xhr",
		"dojo/topic"
	], function(dojoDomForm, dojoRequestXhr, dojoTopic) {
		if (that.validate()) {
			var params = dojoDomForm.toObject("categoryCategoryRenameForm");
			dojoRequestXhr("<?php echo $this->url(array(), 'category_category_rename'); ?>", {
				data: params,
				handleAs: "json",
				method: "POST"
			}).then(function(data) {
				that.reset();
				dojoTopic.publish("/app/category/category/rename/onComplete", data);
			});
		}
	});
	</script>
	
	<div class="app-form-row">
		<label for="name" style="width: 100px"><?php echo $this->translator()->_('category._share.name'); ?>:</label>
		<div id="categoryCategoryRenameNameTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'name', value: '<?php echo addslashes($this->category->name); ?>', style: 'width: 150px', required: true, missingMessage: '<?php echo $this->translator(true)->_('category._share.nameRequired'); ?>'">
			<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
			require([
				"dojo/request/xhr",
				"dijit/registry"
			], function(dojoRequestXhr, dijitRegistry) {
				dojoRequestXhr("<?php echo $this->url(array(), 'core_helper_slug'); ?>", {
					data: {
						input: value
					},
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					dijitRegistry.byId("categoryCategoryRenameSlugTextBox").set("value", data.output);
				});
			});
			</script>
		</div>
	</div>
	
	<div class="app-form-row">
		<label for="slug" style="width: 100px"><?php echo $this->translator()->_('category._share.slug'); ?>:</label>
		<input id="categoryCategoryRenameSlugTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', value: '<?php if ($this->category->slug) : ?><?php echo addslashes($this->category->slug); ?><?php endif; ?>', style: 'width: 150px', required: true, missingMessage: '<?php echo $this->translator(true)->_('category._share.slugRequired'); ?>'" />
	</div>
	
	<div class="dijitDialogPaneActionBar">
		<button id="categoryCategoryRenameSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>
		
		<button id="categoryCategoryRenameCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/category/category/rename/onCancel");
			});
			</script>
		</button>
	</div>
	
	<input type="hidden" name="format" value="json" />
	<input type="hidden" name="category_id" value="<?php echo $this->category->category_id; ?>" />
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/ValidationTextBox"
]);
</script>
