<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		ad
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('banner.add.title'));
?>

<div id="adBannerAddContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="adBannerAddSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("adBannerAddForm").validate()) {
					that.set("disabled", true);
					dojoTopic.publish("/app/ad/banner/add/onStart");
					dojoRequestXhr("<?php echo $this->url(array(), 'ad_banner_add'); ?>", {
						data: dojoDomForm.toObject("adBannerAddForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dojoTopic.publish("/app/ad/banner/add/onComplete", data);
					});
				}
			});
			</script>
		</button>
		
		<button id="adBannerAddCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				core.js.base.controllers.Subscriber.unsubscribe("/app/ad/banner/add", "/app/global/dnd/onDropImage");
				core.js.base.controllers.Subscriber.unsubscribe("/app/ad/banner/add", "/app/global/dnd/onDropLink");
				dojoTopic.publish("/app/ad/banner/add/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- Form -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('banner.add.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<div id="adBannerAddForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('banner._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('banner._share.title'); ?>:</label>
							<input id="adBannerAddTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'title', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('banner._share.titleRequired'); ?>'" />			
						</div>
						
						<div class="app-form-row">
							<label for="banner_format"><?php echo $this->translator()->_('banner._share.format'); ?>:</label>
							<select id="adBannerAddFormatSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'banner_format', style: 'width: 100px'">
								<option value="<?php echo Ad_Models_Banner::FORMAT_IMAGE; ?>"><?php echo $this->translator()->_('banner._share.image'); ?></option>
								<option value="<?php echo Ad_Models_Banner::FORMAT_FLASH; ?>"><?php echo $this->translator()->_('banner._share.flash'); ?></option>
								<option value="<?php echo Ad_Models_Banner::FORMAT_HTML; ?>"><?php echo $this->translator()->_('banner._share.html'); ?></option>
								<option value="<?php echo Ad_Models_Banner::FORMAT_JAVASCRIPT; ?>"><?php echo $this->translator()->_('banner._share.javascript'); ?></option>
								
								<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
								require(["dijit/registry"], function(dijitRegistry) {
									dijitRegistry.byId("adBannerAddCodeTextarea").set("disabled", "image" == value);
								});
								</script>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="code"><?php echo $this->translator()->_('banner._share.code'); ?>:</label>
							<textarea id="adBannerAddCodeTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'code', disabled: true, style: 'width: 300px; height: 150px'"></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="url"><?php echo $this->translator()->_('banner._share.url'); ?>:</label>
							<div id="adBannerAddUrlTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'url', style: 'width: 300px'">
								<script type="dojo/on">
								var that = this;
								require([
									"dojo/dom-attr",
									"dijit/registry"
								], function(dojoDomAttr, dijitRegistry) {
									core.js.base.controllers.Subscriber.subscribe("/app/ad/banner/add", "/app/global/dnd/onDropImage", that, function(data) {
										if (dojoDomAttr.get(data.target, "id") == that.id) {
											dijitRegistry.byId("adBannerAddTitleTextBox").set("value", data.title);
										}
									});
									core.js.base.controllers.Subscriber.subscribe("/app/ad/banner/add", "/app/global/dnd/onDropLink", that, function(data) {
										if (dojoDomAttr.get(data.target, "id") == that.id) {
											dijitRegistry.byId("adBannerAddTitleTextBox").set("value", data.title);
										}
									});
								});
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="target"><?php echo $this->translator()->_('banner._share.target'); ?>:</label>
							<select id="adBannerAddTargetSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'target', style: 'width: 300px'">
								<option value="_blank"><?php echo $this->translator()->_('banner._share.targetBlank'); ?></option>
								<option value="_self"><?php echo $this->translator()->_('banner._share.targetSelf'); ?></option>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="target_url"><?php echo $this->translator()->_('banner._share.targetUrl'); ?>:</label>
							<input id="adBannerAddTargetUrlTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'target_url', style: 'width: 300px'" />
						</div>
						
						<div class="app-form-row">
							<label for="from_date"><?php echo $this->translator()->_('banner._share.fromDate'); ?>:</label>
							<input id="adBannerAddFromDateTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'from_date'" />
						</div>
						
						<div class="app-form-row">
							<label for="to_date"><?php echo $this->translator()->_('banner._share.toDate'); ?>:</label>
							<input id="adBannerAddToDateTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'to_date'" />
						</div>
					</div>
					<!-- /Properties -->
					
					<!-- Links -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('banner._share.links'); ?>', class: 'app-content-pane'">
						<div style="padding-bottom: 8px"><?php echo $this->translator()->_('banner._share.linksHelp'); ?></div>
						
						<div style="padding-bottom: 4px">
							<span style="width: 310px" class="app-left"><?php echo $this->translator()->_('banner._share.link'); ?>:</span>
							<span class="app-left"><?php echo $this->translator()->_('banner._share.zone'); ?>:</span>
						</div>
						
						<div class="app-clear"></div>
						
						<div style="padding-bottom: 4px">
							<input id="adBannerAddLinkTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', style: 'width: 300px'" />
							<select id="adBannerAddZoneSelect" data-dojo-type="dijit/form/Select" data-dojo-props="style: 'width: 200px', maxHeight: 200">
							<?php if ($this->zones) : ?>
								<?php foreach ($this->zones as $zone) : ?>
								<option value="<?php echo $zone->zone_id; ?>"><?php echo $zone->name; ?></option>
								<?php endforeach; ?>
							<?php endif; ?>
							</select>
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
								<?php echo $this->translator()->_('global._share.addAction'); ?>
								<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
								require([
									"dojo/dom-construct",
									"dojo/topic",
									"dijit/registry"
								], function(dojoDomConstruct, dojoTopic, dijitRegistry) {
									var link   = dijitRegistry.byId("adBannerAddLinkTextBox").get("value");
									var zoneId = dijitRegistry.byId("adBannerAddZoneSelect").get("value");
									var zone   = dijitRegistry.byId("adBannerAddZoneSelect").getOptions(zoneId);
									if ("" == link) {
										dojoTopic.publish("/app/global/notification", {
											message: "<?php echo $this->translator()->_('banner._share.linkRequired'); ?>",
											type: "error"
										});
										return;
									}
									// Add link item
									var div = dojoDomConstruct.create("div", {
										className: "adBannerAddLinkItem"
									}, "adBannerAddLinksContainer");
									new dijit.form.TextBox({
										name: "links[]",
										style: "width: 300px; margin-right: 5px",
										value: link,
										readOnly: true
									}).placeAt(div);
									new dijit.form.TextBox({
										style: "width: 200px; margin-right: 5px",
										value: zone.label,
										readOnly: true
									}).placeAt(div);
									dojoDomConstruct.create("input", {
										type: "hidden",
										name: "zones[]",
										value: zoneId
									}, div);
									new dijit.form.Button({
										type: "button",
										label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
										onClick: function() {
											dojoDomConstruct.destroy(div);
										}
									}).placeAt(div);
								});
								</script>
							</button>
						</div>
						
						<div id="adBannerAddLinksContainer"></div>
					</div>
					<!-- /Links -->
					
					<input type="hidden" name="format" value="json" />
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/DateTextBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/ValidationTextBox",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer"
]);
</script>
