<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		ad
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('banner.edit.title'));
?>

<div id="adBannerEditContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="adBannerEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic",
				"dijit/registry"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic, dijitRegistry) {
				if (dijitRegistry.byId("adBannerEditForm").validate()) {
					that.set("disabled", true);
					dojoTopic.publish("/app/ad/banner/edit/onStart");
					dojoRequestXhr("<?php echo $this->url(array(), 'ad_banner_edit'); ?>", {
						data: dojoDomForm.toObject("adBannerEditForm"),
						handleAs: "json",
						method: "POST"
					}).then(function(data) {
						that.set("disabled", false);
						dojoTopic.publish("/app/ad/banner/edit/onComplete", data);
					});
				}
			});
			</script>
		</button>
		
		<button id="adBannerEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				core.js.base.controllers.Subscriber.unsubscribe("/app/ad/banner/edit", "/app/global/dnd/onDropImage");
				core.js.base.controllers.Subscriber.unsubscribe("/app/ad/banner/edit", "/app/global/dnd/onDropLink");
				dojoTopic.publish("/app/ad/banner/edit/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- Form -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="app-heading" style="margin: 0"><span><?php echo $this->translator()->_('banner.edit.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<div id="adBannerEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
					<!-- Properties -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('banner._share.properties'); ?>', class: 'app-content-pane'">
						<div class="app-form-row">
							<label for="title"><?php echo $this->translator()->_('banner._share.title'); ?>:</label>
							<input id="adBannerEditTitleTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'title', value: '<?php echo addslashes($this->banner->title); ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('banner._share.titleRequired'); ?>'" />			
						</div>
						
						<div class="app-form-row">
							<label for="banner_format"><?php echo $this->translator()->_('banner._share.format'); ?>:</label>
							<select id="adBannerEditFormatSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'banner_format', value: '<?php echo $this->banner->format; ?>', style: 'width: 100px'">
								<option value="<?php echo Ad_Models_Banner::FORMAT_IMAGE; ?>"><?php echo $this->translator()->_('banner._share.image'); ?></option>
								<option value="<?php echo Ad_Models_Banner::FORMAT_FLASH; ?>"><?php echo $this->translator()->_('banner._share.flash'); ?></option>
								<option value="<?php echo Ad_Models_Banner::FORMAT_HTML; ?>"><?php echo $this->translator()->_('banner._share.html'); ?></option>
								<option value="<?php echo Ad_Models_Banner::FORMAT_JAVASCRIPT; ?>"><?php echo $this->translator()->_('banner._share.javascript'); ?></option>
								
								<script type="dojo/on" data-dojo-event="change" data-dojo-args="value">
								require(["dijit/registry"], function(dijitRegistry) {
									dijitRegistry.byId("adBannerEditCodeTextarea").set("disabled", "image" == value);
								});
								</script>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="code"><?php echo $this->translator()->_('banner._share.code'); ?>:</label>
							<textarea id="adBannerEditCodeTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'code', disabled: <?php if ($this->banner->format == Ad_Models_Banner::FORMAT_IMAGE) : ?>true<?php else : ?>false<?php endif; ?>, style: 'width: 300px; height: 150px'"><?php if ($this->banner->code) : ?><?php echo htmlspecialchars($this->banner->code); ?><?php endif; ?></textarea>
						</div>
						
						<div class="app-form-row">
							<label for="url"><?php echo $this->translator()->_('banner._share.url'); ?>:</label>
							<div id="adBannerEditUrlTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'url', value: '<?php echo addslashes($this->banner->url); ?>', style: 'width: 300px'">
								<script type="dojo/on">
								var that = this;
								require([
									"dojo/dom-attr",
									"dijit/registry"
								], function(dojoDomAttr, dijitRegistry) {
									core.js.base.controllers.Subscriber.subscribe("/app/ad/banner/edit", "/app/global/dnd/onDropImage", that, function(data) {
										if (dojoDomAttr.get(data.target, "id") == that.id) {
											dijitRegistry.byId("adBannerEditTitleTextBox").set("value", data.title);
										}
									});
									core.js.base.controllers.Subscriber.subscribe("/app/ad/banner/edit", "/app/global/dnd/onDropLink", that, function(data) {
										if (dojoDomAttr.get(data.target, "id") == that.id) {
											dijitRegistry.byId("adBannerEditTitleTextBox").set("value", data.title);
										}
									});
								});
								</script>
							</div>
						</div>
						
						<div class="app-form-row">
							<label for="target"><?php echo $this->translator()->_('banner._share.target'); ?>:</label>
							<select id="adBannerEditTargetSelect" data-dojo-type="dijit/form/Select" data-dojo-props="name: 'target', value: '<?php echo $this->banner->target; ?>', style: 'width: 300px'">
								<option value="_blank"><?php echo $this->translator()->_('banner._share.targetBlank'); ?></option>
								<option value="_self"><?php echo $this->translator()->_('banner._share.targetSelf'); ?></option>
							</select>
						</div>
						
						<div class="app-form-row">
							<label for="target_url"><?php echo $this->translator()->_('banner._share.targetUrl'); ?>:</label>
							<input id="adBannerEditTargetUrlTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'target_url', value: '<?php if ($this->banner->target_url) : ?><?php echo addslashes($this->banner->target_url); ?><?php endif; ?>', style: 'width: 300px'" />
						</div>
						
						<div class="app-form-row">
							<label for="from_date"><?php echo $this->translator()->_('banner._share.fromDate'); ?>:</label>
							<input id="adBannerEditFromDateTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'from_date'<?php if ($this->banner->from_date) : ?>, value: '<?php echo date('Y-m-d', strtotime($this->banner->from_date)); ?>'<?php endif; ?>" />
						</div>
						
						<div class="app-form-row">
							<label for="to_date"><?php echo $this->translator()->_('banner._share.toDate'); ?>:</label>
							<input id="adBannerEditToDateTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'to_date'<?php if ($this->banner->to_date) : ?>, value: '<?php echo date('Y-m-d', strtotime($this->banner->to_date)); ?>'<?php endif; ?>" />
						</div>
					</div>
					<!-- /Properties -->
					
					<!-- Links -->
					<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('banner._share.links'); ?>', class: 'app-content-pane'">
						<div style="padding-bottom: 8px"><?php echo $this->translator()->_('banner._share.linksHelp'); ?></div>
						
						<div style="padding-bottom: 4px">
							<span style="width: 310px" class="app-left"><?php echo $this->translator()->_('banner._share.link'); ?>:</span>
							<span class="app-left"><?php echo $this->translator()->_('banner._share.zone'); ?>:</span>
						</div>
						
						<div class="app-clear"></div>
						
						<div style="padding-bottom: 4px">
							<input id="adBannerEditLinkTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', style: 'width: 300px'" />
							<select id="adBannerEditZoneSelect" data-dojo-type="dijit/form/Select" data-dojo-props="style: 'width: 200px', maxHeight: 200">
							<?php if ($this->zones) : ?>
								<?php foreach ($this->zones as $zone) : ?>
								<option value="<?php echo $zone->zone_id; ?>"><?php echo $zone->name; ?></option>
								<?php endforeach; ?>
							<?php endif; ?>
							</select>
							<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
								<?php echo $this->translator()->_('global._share.addAction'); ?>
								<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
								require([
									"dojo/dom-construct",
									"dojo/topic",
									"dijit/registry"
								], function(dojoDomConstruct, dojoTopic, dijitRegistry) {
									var link   = dijitRegistry.byId("adBannerEditLinkTextBox").get("value");
									var zoneId = dijitRegistry.byId("adBannerEditZoneSelect").get("value");
									var zone   = dijitRegistry.byId("adBannerEditZoneSelect").getOptions(zoneId);
									if ("" == link) {
										dojoTopic.publish("/app/global/notification", {
											message: "<?php echo $this->translator()->_('banner._share.linkRequired'); ?>",
											type: "error"
										});
										return;
									}
									// Add link item
									var div = dojoDomConstruct.create("div", {
										className: "adBannerEditLinkItem"
									}, "adBannerEditLinksContainer");
									new dijit.form.TextBox({
										name: "links[]",
										style: "width: 300px; margin-right: 5px",
										value: link,
										readOnly: true
									}).placeAt(div);
									new dijit.form.TextBox({
										style: "width: 200px; margin-right: 5px",
										value: zone.label,
										readOnly: true
									}).placeAt(div);
									dojoDomConstruct.create("input", {
										type: "hidden",
										name: "zones[]",
										value: zoneId
									}, div);
									new dijit.form.Button({
										type: "button",
										label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
										onClick: function() {
											dojoDomConstruct.destroy(div);
										}
									}).placeAt(div);
								});
								</script>
							</button>
						</div>
						
						<div id="adBannerEditLinksContainer">
						<?php if ($this->pages) : ?>
							<?php foreach ($this->pages as $page) : ?>
							<div class="adBannerEditLinkItem">
								<input data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'links[]', readOnly: true, value: '<?php echo $page['url']; ?>', style: 'width: 300px'" />
								<div data-dojo-type="dijit/form/TextBox" data-dojo-props="appZoneId: '<?php echo $page['zone_id']; ?>', type: 'text', readOnly: true, style: 'width: 200px'">
									<script type="dojo/on">
									var that = this;
									require(["dijit/registry"], function(dijitRegistry) {
										// LESSON: I can get the zone's title without using a view helper
										var zoneId = that.get("appZoneId");
										var option = dijitRegistry.byId("adBannerEditZoneSelect").getOptions(zoneId);
										if (option) {
											that.set("value", option.label);
										}
									});
									</script>
								</div>
								<input type="hidden" name="zones[]" value="<?php echo $page['zone_id']; ?>" />
								<button data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
									<?php echo $this->translator()->_('global._share.deleteAction'); ?>
									<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
									var that = this;
									require([
										"dojo/dom-construct",
										"dojo/NodeList-traverse",
										"dojo/query"
									], function(dojoDomConstruct) {
										dojoDomConstruct.destroy(dojo.query(that.domNode).closest(".adBannerEditLinkItem")[0]);
									});
									</script>
								</button>
							</div>
							<?php endforeach; ?>
						<?php endif; ?>
						</div>
					</div>
					<!-- /Links -->
					
					<input type="hidden" name="format" value="json" />
					<input type="hidden" name="banner_id" value="<?php echo $this->banner->banner_id; ?>" />
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/DateTextBox",
	"dijit/form/Form",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/ValidationTextBox",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer"	
]);
</script>
