<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-13
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('skin.edit.title'));
?>

<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="coreSkinEditSaveButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'submit'">
			<span class="app-icon app-icon-save"></span><br />
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/dom-form",
				"dojo/request/xhr",
				"dojo/topic"
			], function(dojoDomForm, dojoRequestXhr, dojoTopic) {
				that.set("disabled", true);
				dojoRequestXhr("<?php echo $this->url(array(), 'core_skin_edit'); ?>", {
					data: dojoDomForm.toObject("coreSkinEditForm"),
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					that.set("disabled", false);
					var message = ("APP_RESULT_OK" == data.result)
								? "<?php echo $this->translator()->_('skin.edit.success'); ?>"
								: "<?php echo $this->translator()->_('skin.edit.error'); ?>";
					dojoTopic.publish("/app/global/notification", {
						message: message,
						type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
					});
				});
			});
			</script>
		</button>
		
		<button id="coreSkinEditCancelButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/core/layout/edit/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- EditLayoutForm -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', class: 'app-content-pane'">
			<?php echo sprintf($this->translator()->_('skin.edit.help'), $this->path); ?>
		</div>
		
		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
			<div id="coreSkinEditForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
				<textarea id="coreSkinEditContentTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'content', region: 'center', style: 'height: 100%; width: 100%'"><?php echo $this->content; ?></textarea>
				
				<input type="hidden" name="format" value="json" />
				<input type="hidden" name="template" value="<?php echo $this->template; ?>" />
				<input type="hidden" name="skin" value="<?php echo $this->skin; ?>" />
				<input type="hidden" name="file" value="<?php echo $this->file; ?>" />
			</div>
		</div>
	</div>
	<!-- /EditLayoutForm -->
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar"
]);
</script>
