<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	views
 * @since		1.0
 * @version		2012-10-02
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('revision.view.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/layout/resources/GridContainer.css");
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/widget/Portlet/Portlet.css");
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/tag/css/admin/default/styles.css");
});
</script>

<div id="contentRevisionViewContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="contentRevisionViewCloseButton" data-dojo-type="dijit/form/Button" data-dojo-props="type: 'button'">
			<span class="app-icon app-icon-cancel"></span><br />
			<?php echo $this->translator()->_('global._share.closeAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/content/revision/view/onClose");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->

	<!-- Form -->
	<div id="contentRevisionViewContentPane" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', class: 'app-content-pane'">
		<?php if (!$this->revision) : ?>
			<?php echo $this->translator()->_('revision.view.notFound'); ?>
		<?php else : ?>
		
		<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
			<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="region: 'center', closable: true, nested: true">
				<!-- Properties -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.properties'); ?>', class: 'app-form app-content-pane'">
					<div class="app-form-row">
						<label for="type"><?php echo $this->translator()->_('article._share.type'); ?>:</label>
						<select id="contentRevisionViewTypeSelect" data-dojo-type="dijit/form/Select" data-dojo-props="disabled: true, name: 'type', value: '<?php echo $this->revision->type; ?>'">
							<option value="article"><?php echo $this->translator()->_('article._share.typeArticle'); ?></option>
							<option value="page"><?php echo $this->translator()->_('article._share.typePage'); ?></option>
						</select>
					</div>
				
					<div class="app-form-row">
						<label for="title"><?php echo $this->translator()->_('article._share.title'); ?>:</label>
						<input id="contentRevisionViewTitleTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'title', value: '<?php echo addslashes($this->revision->title); ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('article._share.titleRequired'); ?>'" />
					</div>
					
					<div class="app-form-row">
						<label for="sub_title"><?php echo $this->translator()->_('article._share.subTitle'); ?>:</label>
						<input id="contentRevisionViewSubTitleTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'sub_title', style: 'width: 300px'<?php if ($this->revision->sub_title) : ?>, value: '<?php echo addslashes($this->revision->sub_title); ?>'<?php endif; ?>">
					</div>
					
					<div class="app-form-row">
						<label for="slug"><?php echo $this->translator()->_('article._share.slug'); ?>:</label>
						<input id="contentRevisionViewSlugTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'slug', value: '<?php echo addslashes($this->revision->slug); ?>', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('article._share.slugRequired'); ?>'" />
					</div>
					
					<div class="app-form-row">
						<label for="description"><?php echo $this->translator()->_('article._share.description'); ?>:</label>
						<textarea id="contentRevisionViewDescTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'description', style: 'width: 250px; height: 150px'"><?php echo $this->revision->description; ?></textarea>
					</div>
					
					<div class="app-form-row">
						<label for="meta_keyword"><?php echo $this->translator()->_('article._share.metaKeywordTag'); ?>:</label>
						<textarea id="contentRevisionViewMetaKeywordTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'meta_keyword', style: 'width: 250px; height: 100px'"><?php echo $this->revision->meta_keyword; ?></textarea>
					</div>
					
					<div class="app-form-row">
						<label for="meta_description"><?php echo $this->translator()->_('article._share.metaDescriptionTag'); ?>:</label>
						<textarea id="contentRevisionViewMetaDescTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'meta_description', style: 'width: 250px; height: 100px'"><?php echo $this->revision->meta_description; ?></textarea>
					</div>
					
					<div class="app-form-row">
						<label for="author"><?php echo $this->translator()->_('article._share.author'); ?>:</label>
						<input id="contentRevisionViewAuthorTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'author', value: '<?php echo addslashes($this->revision->author); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('article._share.authorRequired'); ?>'">
					</div>
					
					<div class="app-form-row">
						<label for="credit"><?php echo $this->translator()->_('article._share.credit'); ?>:</label>
						<input id="contentRevisionViewCreditTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'credit', style: 'width: 200px'<?php if ($this->revision->credit) : ?>, value: '<?php echo addslashes($this->revision->credit); ?>'<?php endif; ?>">
					</div>
					
					<div class="app-form-row">
						<label><?php echo $this->translator()->_('article._share.icon'); ?>:</label>
						<input id="contentRevisionViewImageIconCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'image_icon', value: 1, checked: <?php if ($this->revision->image_icon == '1') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('article._share.iconImage'); ?>
						<input id="contentRevisionViewVideoIconCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'video_icon', value: 1, checked: <?php if ($this->revision->video_icon == '1') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('article._share.iconVideo'); ?>
					</div>
					
					<div class="app-form-row">
						<label for="publishing_date"><?php echo $this->translator()->_('article._share.publishingDate'); ?>:</label>
						<input id="contentRevisionViewPublishingDateTextBox" data-dojo-type="dijit/form/DateTextBox" data-dojo-props="type: 'text', name: 'publishing_date', value: '<?php if ($this->revision->publishing_date) : ?><?php echo date('Y-m-d', strtotime($this->revision->publishing_date)); ?><?php endif; ?>'" />
						<input id="contentRevisionViewPublishingTimeTextBox" data-dojo-type="dijit/form/TimeTextBox" data-dojo-props="type: 'text', name: 'publishing_time', value: 'T<?php if ($this->revision->publishing_date) : ?><?php echo date('H:i:s', strtotime($this->revision->publishing_date)); ?><?php endif; ?>', constraints: { timePattern: 'HH:mm:ss' }" />
					</div>
					
					<div class="app-form-row">
						<label for="featured">&nbsp;</label>
						<input id="contentRevisionViewFeaturedCheckBox" data-dojo-type="dijit/form/CheckBox" data-dojo-props="name: 'featured', value: 1, checked: <?php if ($this->revision->featured == '1') : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('article._share.markAsFeatured'); ?>
					</div>
					
					<div class="app-form-row">
						<label for="category"><?php echo $this->translator()->_('article._share.category'); ?>:</label>
						<?php 
						echo $this->helperLoader('category')
								  ->categorySelect('content', $this->revision->language, array(
										'name'	   => 'category',
										'selected' => $this->revision->category_id,
								  		'disabled' => true,
								  ));
						?>
					</div>
					
					<div class="app-form-row">
						<label for="categories"><?php echo $this->translator()->_('article._share.categories'); ?>:</label>
						<div id="contentRevisionViewCategories" class="app-left">
							<?php 
							echo $this->helperLoader('category')
									  ->categoryCheckboxTree('content', $this->revision->language, array(
											'id'	   => 'contentRevisionViewCategories',
											'name'	   => 'categories[]',
											'selected' => $this->revision->categories,
									  		'disabled' => true,
									  ));
							?>
						</div>
					</div>
				</div>
				<!-- /Properties -->
				
				<!-- Cover -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.cover'); ?>', class: 'app-content-pane'">
					<div class="app-container-border" style="height: 225px; width: 300px; margin-bottom: 8px">
						<?php if ($this->revision->image_crop) : ?>
						<img src="<?php echo $this->APP_ROOT_URL . $this->revision->image_crop; ?>" />
						<?php endif; ?>
					</div>
					
					<input id="contentRevisionViewCoverTitleTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', name: 'cover_title', style: 'width: 300px', placeHolder: '<?php echo $this->translator(true)->_('article._share.coverTitleHelp'); ?>', value: '<?php if ($this->revision->cover_title) : ?><?php echo addslashes($this->revision->cover_title); ?><?php endif; ?>'" />
				</div>
				<!-- /Cover -->
			
				<!-- Content -->
				<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="selected: true, gutters: true, style: 'height: 100%; width: 100%', title: '<?php echo $this->translator(true)->_('article._share.content'); ?>'">
					<div id="contentRevisionViewContentEditor" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', style: 'height: 100%; width: 100%', class: 'app-container-border'">
					</div>
				</div>
				<!-- /Content -->
				
				<!-- Tags -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.tags'); ?>', class: 'app-content-pane'">
					<div id="contentRevisionViewTagsContainer" style="height: 300px; width: 100%; margin-bottom: 8px">
					</div>
				</div>
				<!-- /Tags -->
				
				<!-- Revision -->
				<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('article._share.revision'); ?>', class: 'app-form app-content-pane'">
					<div class="app-form-row">
						<label for="comment"><?php echo $this->translator()->_('revision._share.comment'); ?>:</label>
						<textarea id="contentRevisionViewCommentTextarea" data-dojo-type="dijit/form/SimpleTextarea" data-dojo-props="name: 'comment', style: 'width: 250px; height: 150px'"><?php if ($this->revision->comment) : ?><?php echo $this->revision->comment; ?><?php endif; ?></textarea>
					</div>
				</div>
				<!-- /Revision -->
			</div>
		</div>
		
		<?php endif; ?>
	</div>
	<!-- /Form -->
</div>

<script type="text/javascript">
require({
	paths: {
		"tag": "<?php echo $this->APP_STATIC_URL; ?>/modules/tag"
	}
});
							
require([
	"dojo/dom-attr",
	"dojo/ready",
	"dojo/parser",
	"dojo/query",
	"dijit/form/Button",
	"dijit/form/CheckBox",
	"dijit/form/DateTextBox",
	"dijit/form/Select",
	"dijit/form/SimpleTextarea",
	"dijit/form/TextBox",
	"dijit/form/TimeTextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"core/js/Constant",
	"core/js/base/controllers/ActionProvider",
	"core/js/controllers/LayoutController",
	"core/js/views/LayoutToolbar",
	"tag/js/views/TagCollectionView"	
], function(dojoDomAttr, dojoReady) {
	<?php if ($this->revision) : ?>

	dojoReady(function() {
		// Provide the actions
		<?php foreach (array(
						'core_extension_render',	// Required by the content editor
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
		});	
		<?php endforeach; ?>

		// Show article's tags
		var tagCollectionView = new tag.js.views.TagCollectionView("contentRevisionViewTagsContainer", "tags[]");
		<?php foreach ($this->tags as $tag) : ?>
		tagCollectionView.addTag(core.js.base.Encoder.decode("<?php echo $this->encoder()->encode($tag); ?>"));
		<?php endforeach; ?>

		// Disable all fields
		dojo.query("input, select, textarea, button", "contentRevisionViewContentPane").forEach(function(node, index) {
			dojoDomAttr.set(node, "disabled", "disabled");
		});
		
		var editorController = new core.js.controllers.LayoutController("contentRevisionViewContentEditor");
		// editorController.setLayoutToolbar(new core.js.views.LayoutToolbar("contentRevisionViewContentToolbar"));
		editorController.setLayoutData(<?php echo $this->revision->layout; ?>);
		setTimeout(function() {
			editorController.switchToMode("view");
		}, 200);
	});

	<?php endif; ?>	
});
</script>
