<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/password-meter.css");	
});
</script>

<!-- 
DO NOT REMOVE THE ID ATTRIBUTE OF THE FORM. It is used to identify the form in the main layout view script
(/template/admin/layouts/install.phtml)
 -->
<div id="coreInstallCompleteForm" data-dojo-type="dijit/form/Form" data-dojo-props="action: '', method: 'POST', class: 'app-form'">
	<!-- AdminSettings -->
	<h2><?php echo $this->translator()->_('install.complete.admin'); ?></h2>
	
	<div class="app-form-row">
		<label for="prefix"><?php echo $this->translator()->_('install.complete.adminPrefixUrl'); ?>:</label>
		<input id="coreInstallCompletePrefixTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', value: 'admin', name: 'prefix', width: '200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('install.complete.adminPrefixUrlRequired'); ?>'" />
	</div>

	<div class="app-form-row">
		<label for="username"><?php echo $this->translator()->_('install.complete.adminUsername'); ?>:</label>
		<input id="coreInstallCompleteUsernameTextBox" data-dojo-type="dijit/form/TextBox" data-dojo-props="type: 'text', value: 'admin', name: 'username', width: '200px', required: true, disabled: true" />
	</div>

	<div class="app-form-row">
		<label for="password"><?php echo $this->translator()->_('install.complete.adminPassword'); ?>:</label>
		<input id="coreInstallCompletePasswordTextbox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', value: '<?php echo $this->password; ?>', name: 'password', width: '200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('install.complete.adminPasswordRequired'); ?>', class: 'app-left'" />
			
		<!-- PasswordStrengthMeter -->
		<div class="app-left" id="coreInstallCompletePasswordStrengthMeter"></div>
		<!-- /PasswordStrengthMeter -->
		
		<div class="app-clear"></div>
	</div>
	
	<div class="app-form-row">
		<label>&nbsp;</label>
		<a href="javascript: void(0);" id="coreInstallCompleteGeneratePassword"><?php echo $this->translator()->_('install.complete.generatePasswordAction'); ?></a>
	</div>

	<div class="app-form-row">
		<label for="email"><?php echo $this->translator()->_('install.complete.adminEmail'); ?>:</label>
		<input id="coreInstallCompleteEmailTextBox" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-props="type: 'text', name: 'email', width: '200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('install.complete.adminEmailRequired'); ?>'" />
	</div>
	<!-- /AdminSettings -->
</div>

<script type="text/javascript">
require([
	"dojo/dom",
	"dojo/on",
	"dojo/ready",
	"dojo/request/xhr",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dijit/form/Form",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"core/js/views/PasswordStrengthMeter"
], function(dojoDom, dojoOn, dojoReady, dojoRequestXhr, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		// TODO: Do I really need to subscribe this topic
		// or it will work when the DOM ready?
		var handler = dojoTopic.subscribe("/app/global/onLoadComplete/core_install_complete", function() {
			var passwordStrengthMeter = new core.js.views.PasswordStrengthMeter("coreInstallCompletePasswordStrengthMeter");
			passwordStrengthMeter.setUsername(dijitRegistry.byId("coreInstallCompleteUsernameTextBox").get("value"));
		
			dojoOn(dijitRegistry.byId("coreInstallCompletePasswordTextbox"), "keyup", function() {
				passwordStrengthMeter.checkPassword(dijitRegistry.byId("coreInstallCompletePasswordTextbox").get("value"));
			});

			// Generate password handler
			dojoOn(dojoDom.byId("coreInstallCompleteGeneratePassword"), "click", function() {
				dojoRequestXhr("<?php echo $this->url(array(), 'core_password_generate'); ?>", {
					data: {
						hash: false,
						length: 10
					},
					handleAs: "json",
					method: "POST"
				}).then(function(data) {
					dijitRegistry.byId("coreInstallCompletePasswordTextbox").set("value", data.password);
					passwordStrengthMeter.checkPassword(data.password);
				});
			});
		});
	});
});
</script>
