<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	plugins
 * @since		1.0
 * @version		2012-09-15
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/plugins/debug/styles.css");	
});
</script>

<div id="corePluginsDebugContainer" class="corePluginsDebugContainer" data-app-selected="<?php echo $this->selected; ?>" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'center', iconClass: 'app-icon corePluginsDebugIcon', title: '<?php echo $this->translator(true)->_('debug.title'); ?>'">
	<div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="closable: true, nested: true, title: '<?php echo $this->translator(true)->_('debug.title'); ?>'">
		<?php if ($this->plugins) : ?>
		<?php foreach ($this->plugins as $plugin) : ?>
			<?php echo $this->partial('_' . $plugin . '.phtml', array('selected' => $plugin == $this->selected, 'data' => isset($this->data[$plugin]) ? $this->data[$plugin] : null)); ?>
		<?php endforeach; ?>
		<?php endif; ?>
		<script type="dojo/connect" data-dojo-event="selectChild" data-dojo-args="child">
		require([
			"dojo/dom-attr",
			"dijit/registry"
		], function(dojoDomAttr, dijitRegistry) {
			var plugin = dojoDomAttr.get(child.domNode, "data-app-plugin");
			dojoDomAttr.set(dijitRegistry.byId("corePluginsDebugContainer").domNode, "data-app-selected", plugin);
		});
		</script>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/_base/window",
	"dojo/dom-attr",
	"dojo/dom-construct",
	"dojo/ready",
	"dojo/request/xhr",
	"dojo/topic",
	"dijit/registry",
	"dojo/parser",
	"dojo/query",
	"dijit/layout/TabContainer",
	"dojox/layout/ContentPane"	
], function(dojoWindow, dojoDomAttr, dojoDomConstruct, dojoReady, dojoRequestXhr, dojoTopic, dijitRegistry) {
	dojoReady(function() {
		var codePluginsDebugIoHanlder = dojoTopic.subscribe("/dojo/io/load", function(dfd, response) {
			var pluginRenderUrl = "<?php echo $this->url(array(), 'core_extension_render'); ?>";
			var url = dfd.ioArgs.url;
			if (url != pluginRenderUrl) {
				var selected = dojoDomAttr.get(dijitRegistry.byId("corePluginsDebugContainer").domNode, "data-app-selected");
				dojoRequestXhr(pluginRenderUrl, {
					data: {
						_type: "plugin",
						_mod: "core",
						_name: "debug",
						_method: "debug",
						selected: selected
					},
					method: "POST"
				}).then(function(data) {
					if (dijit.byId("corePluginsDebugContainer")) {
						var div	= dojoDomConstruct.create("div", {
							innerHTML: data,
							style: "display: 'none'"
						}, dojoWindow.body());
						var node = dojo.query(".corePluginsDebugContainer", div)[0];
						var html = node.innerHTML;
						dojoDomConstruct.destroy(div);
						dijitRegistry.byId("corePluginsDebugContainer").set("content", html);
					}
				});
			}
		});

		// Remove the debug tab from the toolbox after uninstalling the plugin 
		dojoTopic.subscribe("/app/core/plugin/uninstall/core_debug", function(data) {
			codePluginsDebugIoHanlder.remove();
		});	
	});
});
</script>
