<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		category
 * @subpackage	views
 * @since		1.0
 * @version		2012-09-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('folder.list.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/category/css/admin/default/styles.css");	
});
</script>

<div id="categoryFolderListContainer" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', gutters: false">
	<!-- Toolbar -->
	<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top'">
		<div id="categoryFolderListToolbar"></div>
	</div>
	<!-- /Toolbar -->
	
	<!-- Folders -->
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div id="categoryFolderListView" data-dojo-type="dojox/layout/ContentPane" data-dojo-props="region: 'center', splitter: false">
			<?php echo $this->render('folder/list.ajax.phtml'); ?>
		</div>
	</div>
	<!-- /Folders -->
</div>

<script type="text/javascript">
require({
	paths: {
		"category": "<?php echo $this->APP_STATIC_URL; ?>/modules/category"
	}	
});

require([
	"dojo/ready",
	"dojo/parser",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dojox/layout/ContentPane",
	"core/js/base/Config",
	"core/js/base/controllers/ActionProvider",
	"category/js/controllers/FolderController",
	"category/js/views/FolderContextMenu",
	"category/js/views/FolderListView",
	"category/js/views/FolderToolbar"	
], function(dojoReady) {
	dojoReady(function() {
		// Provide the actions
		<?php foreach (array(
						'category_folder_add', 'category_folder_delete', 'category_folder_list', 'category_folder_rename',
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
		});	
		<?php endforeach; ?>

		// Localization
		core.js.base.Config.set("core", "localization_languages", <?php echo $this->config("core", "localization_languages", '{"en_US":"English"}'); ?>);
		
		var folderController = new category.js.controllers.FolderController("categoryFolderListContainer");
		folderController.setEntityClass("<?php echo $this->entityClass; ?>")
						.setLanguage("<?php echo $this->language; ?>")
						.setHelperContainer("<?php echo $this->helperContainer; ?>")
						.setFolderToolbar(new category.js.views.FolderToolbar("categoryFolderListToolbar"))
						.setFolderListView(new category.js.views.FolderListView("categoryFolderListView"))
						.setFolderContextMenu(new category.js.views.FolderContextMenu());
	});	
});
</script>
